server {
    listen 8443 ssl;
    server_name _;
    ssl_protocols TLSv1.3;
    ssl_certificate /run/tls/tls.crt;
    ssl_certificate_key /run/tls/tls.key;

    location = /m7/linux-arm64.tar.gz {
        root /usr/share/nginx/html;
        limit_except GET { deny all; }
    }

    location / { return 404; }
}
