releaseId: argus
namespace: argus-observability
images:
  clickhouse: clickhouse/clickhouse-server:26.3.17.110-alpine
clickhouse:
  endpoint: argus-clickhouse-client:9000
kafka:
  brokers: argus-kafka-kafka-bootstrap:9092
