// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: automation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceAutomation = `-- name: AdvanceAutomation :one
UPDATE automations SET next_run_at = $3, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 RETURNING id, enterprise_id, name, service_account_id, authorization_version, tool_id, tool_input, cron, timezone, status, next_run_at, revision, version, created_at, updated_at
`

type AdvanceAutomationParams struct {
	ID           uuid.UUID          `json:"id"`
	EnterpriseID uuid.UUID          `json:"enterprise_id"`
	NextRunAt    pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) AdvanceAutomation(ctx context.Context, arg AdvanceAutomationParams) (Automation, error) {
	row := q.db.QueryRow(ctx, advanceAutomation, arg.ID, arg.EnterpriseID, arg.NextRunAt)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.ServiceAccountID,
		&i.AuthorizationVersion,
		&i.ToolID,
		&i.ToolInput,
		&i.Cron,
		&i.Timezone,
		&i.Status,
		&i.NextRunAt,
		&i.Revision,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimDueAutomations = `-- name: ClaimDueAutomations :many
SELECT id, enterprise_id, name, service_account_id, authorization_version, tool_id, tool_input, cron, timezone, status, next_run_at, revision, version, created_at, updated_at FROM automations WHERE status = 'enabled' AND next_run_at <= $1
ORDER BY next_run_at, id FOR UPDATE SKIP LOCKED LIMIT $2
`

type ClaimDueAutomationsParams struct {
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ClaimDueAutomations(ctx context.Context, arg ClaimDueAutomationsParams) ([]Automation, error) {
	rows, err := q.db.Query(ctx, claimDueAutomations, arg.NextRunAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Automation{}
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.Name,
			&i.ServiceAccountID,
			&i.AuthorizationVersion,
			&i.ToolID,
			&i.ToolInput,
			&i.Cron,
			&i.Timezone,
			&i.Status,
			&i.NextRunAt,
			&i.Revision,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAutomation = `-- name: CreateAutomation :one
INSERT INTO automations (id, enterprise_id, name, service_account_id, authorization_version, tool_id, tool_input, cron, timezone, next_run_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, enterprise_id, name, service_account_id, authorization_version, tool_id, tool_input, cron, timezone, status, next_run_at, revision, version, created_at, updated_at
`

type CreateAutomationParams struct {
	ID                   uuid.UUID          `json:"id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	Name                 string             `json:"name"`
	ServiceAccountID     uuid.UUID          `json:"service_account_id"`
	AuthorizationVersion int64              `json:"authorization_version"`
	ToolID               string             `json:"tool_id"`
	ToolInput            []byte             `json:"tool_input"`
	Cron                 string             `json:"cron"`
	Timezone             string             `json:"timezone"`
	NextRunAt            pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) CreateAutomation(ctx context.Context, arg CreateAutomationParams) (Automation, error) {
	row := q.db.QueryRow(ctx, createAutomation,
		arg.ID,
		arg.EnterpriseID,
		arg.Name,
		arg.ServiceAccountID,
		arg.AuthorizationVersion,
		arg.ToolID,
		arg.ToolInput,
		arg.Cron,
		arg.Timezone,
		arg.NextRunAt,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.ServiceAccountID,
		&i.AuthorizationVersion,
		&i.ToolID,
		&i.ToolInput,
		&i.Cron,
		&i.Timezone,
		&i.Status,
		&i.NextRunAt,
		&i.Revision,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAutomationRevision = `-- name: CreateAutomationRevision :one
INSERT INTO automation_revisions (
    automation_id, enterprise_id, revision, service_account_id, authorization_version,
    tool_id, tool_input, cron, timezone
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING automation_id, enterprise_id, revision, service_account_id, authorization_version, tool_id, tool_input, cron, timezone, created_at
`

type CreateAutomationRevisionParams struct {
	AutomationID         uuid.UUID `json:"automation_id"`
	EnterpriseID         uuid.UUID `json:"enterprise_id"`
	Revision             int32     `json:"revision"`
	ServiceAccountID     uuid.UUID `json:"service_account_id"`
	AuthorizationVersion int64     `json:"authorization_version"`
	ToolID               string    `json:"tool_id"`
	ToolInput            []byte    `json:"tool_input"`
	Cron                 string    `json:"cron"`
	Timezone             string    `json:"timezone"`
}

func (q *Queries) CreateAutomationRevision(ctx context.Context, arg CreateAutomationRevisionParams) (AutomationRevision, error) {
	row := q.db.QueryRow(ctx, createAutomationRevision,
		arg.AutomationID,
		arg.EnterpriseID,
		arg.Revision,
		arg.ServiceAccountID,
		arg.AuthorizationVersion,
		arg.ToolID,
		arg.ToolInput,
		arg.Cron,
		arg.Timezone,
	)
	var i AutomationRevision
	err := row.Scan(
		&i.AutomationID,
		&i.EnterpriseID,
		&i.Revision,
		&i.ServiceAccountID,
		&i.AuthorizationVersion,
		&i.ToolID,
		&i.ToolInput,
		&i.Cron,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const createAutomationRun = `-- name: CreateAutomationRun :one
INSERT INTO automation_runs (id, automation_id, enterprise_id, automation_revision, scheduled_for, status)
VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT (automation_id, scheduled_for) DO UPDATE SET updated_at = automation_runs.updated_at
RETURNING id, automation_id, enterprise_id, automation_revision, scheduled_for, status, task_id, pending_action_id, result_ref, error_code, created_at, updated_at
`

type CreateAutomationRunParams struct {
	ID                 uuid.UUID          `json:"id"`
	AutomationID       uuid.UUID          `json:"automation_id"`
	EnterpriseID       uuid.UUID          `json:"enterprise_id"`
	AutomationRevision int32              `json:"automation_revision"`
	ScheduledFor       pgtype.Timestamptz `json:"scheduled_for"`
	Status             string             `json:"status"`
}

func (q *Queries) CreateAutomationRun(ctx context.Context, arg CreateAutomationRunParams) (AutomationRun, error) {
	row := q.db.QueryRow(ctx, createAutomationRun,
		arg.ID,
		arg.AutomationID,
		arg.EnterpriseID,
		arg.AutomationRevision,
		arg.ScheduledFor,
		arg.Status,
	)
	var i AutomationRun
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.EnterpriseID,
		&i.AutomationRevision,
		&i.ScheduledFor,
		&i.Status,
		&i.TaskID,
		&i.PendingActionID,
		&i.ResultRef,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishAutomationRunByPendingAction = `-- name: FinishAutomationRunByPendingAction :exec
UPDATE automation_runs SET status = $3, error_code = $4, updated_at = now()
WHERE pending_action_id = $1 AND enterprise_id = $2 AND status IN ('waiting_approval','running')
`

type FinishAutomationRunByPendingActionParams struct {
	PendingActionID uuid.NullUUID `json:"pending_action_id"`
	EnterpriseID    uuid.UUID     `json:"enterprise_id"`
	Status          string        `json:"status"`
	ErrorCode       pgtype.Text   `json:"error_code"`
}

func (q *Queries) FinishAutomationRunByPendingAction(ctx context.Context, arg FinishAutomationRunByPendingActionParams) error {
	_, err := q.db.Exec(ctx, finishAutomationRunByPendingAction,
		arg.PendingActionID,
		arg.EnterpriseID,
		arg.Status,
		arg.ErrorCode,
	)
	return err
}

const getActiveAutomationRun = `-- name: GetActiveAutomationRun :one
SELECT id, automation_id, enterprise_id, automation_revision, scheduled_for, status, task_id, pending_action_id, result_ref, error_code, created_at, updated_at FROM automation_runs WHERE automation_id = $1 AND enterprise_id = $2
  AND status IN ('pending','running','waiting_approval') ORDER BY scheduled_for DESC LIMIT 1
`

type GetActiveAutomationRunParams struct {
	AutomationID uuid.UUID `json:"automation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetActiveAutomationRun(ctx context.Context, arg GetActiveAutomationRunParams) (AutomationRun, error) {
	row := q.db.QueryRow(ctx, getActiveAutomationRun, arg.AutomationID, arg.EnterpriseID)
	var i AutomationRun
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.EnterpriseID,
		&i.AutomationRevision,
		&i.ScheduledFor,
		&i.Status,
		&i.TaskID,
		&i.PendingActionID,
		&i.ResultRef,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAutomation = `-- name: GetAutomation :one
SELECT id, enterprise_id, name, service_account_id, authorization_version, tool_id, tool_input, cron, timezone, status, next_run_at, revision, version, created_at, updated_at FROM automations WHERE id = $1 AND enterprise_id = $2
`

type GetAutomationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetAutomation(ctx context.Context, arg GetAutomationParams) (Automation, error) {
	row := q.db.QueryRow(ctx, getAutomation, arg.ID, arg.EnterpriseID)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.ServiceAccountID,
		&i.AuthorizationVersion,
		&i.ToolID,
		&i.ToolInput,
		&i.Cron,
		&i.Timezone,
		&i.Status,
		&i.NextRunAt,
		&i.Revision,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAutomationForUpdate = `-- name: GetAutomationForUpdate :one
SELECT id, enterprise_id, name, service_account_id, authorization_version, tool_id, tool_input, cron, timezone, status, next_run_at, revision, version, created_at, updated_at FROM automations WHERE id = $1 AND enterprise_id = $2 FOR UPDATE
`

type GetAutomationForUpdateParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetAutomationForUpdate(ctx context.Context, arg GetAutomationForUpdateParams) (Automation, error) {
	row := q.db.QueryRow(ctx, getAutomationForUpdate, arg.ID, arg.EnterpriseID)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.ServiceAccountID,
		&i.AuthorizationVersion,
		&i.ToolID,
		&i.ToolInput,
		&i.Cron,
		&i.Timezone,
		&i.Status,
		&i.NextRunAt,
		&i.Revision,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAutomationRevision = `-- name: GetAutomationRevision :one
SELECT automation_id, enterprise_id, revision, service_account_id, authorization_version, tool_id, tool_input, cron, timezone, created_at FROM automation_revisions
WHERE automation_id = $1 AND enterprise_id = $2 AND revision = $3
`

type GetAutomationRevisionParams struct {
	AutomationID uuid.UUID `json:"automation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Revision     int32     `json:"revision"`
}

func (q *Queries) GetAutomationRevision(ctx context.Context, arg GetAutomationRevisionParams) (AutomationRevision, error) {
	row := q.db.QueryRow(ctx, getAutomationRevision, arg.AutomationID, arg.EnterpriseID, arg.Revision)
	var i AutomationRevision
	err := row.Scan(
		&i.AutomationID,
		&i.EnterpriseID,
		&i.Revision,
		&i.ServiceAccountID,
		&i.AuthorizationVersion,
		&i.ToolID,
		&i.ToolInput,
		&i.Cron,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getAutomationRun = `-- name: GetAutomationRun :one
SELECT id, automation_id, enterprise_id, automation_revision, scheduled_for, status, task_id, pending_action_id, result_ref, error_code, created_at, updated_at FROM automation_runs WHERE id = $1 AND enterprise_id = $2
`

type GetAutomationRunParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetAutomationRun(ctx context.Context, arg GetAutomationRunParams) (AutomationRun, error) {
	row := q.db.QueryRow(ctx, getAutomationRun, arg.ID, arg.EnterpriseID)
	var i AutomationRun
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.EnterpriseID,
		&i.AutomationRevision,
		&i.ScheduledFor,
		&i.Status,
		&i.TaskID,
		&i.PendingActionID,
		&i.ResultRef,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAutomationRuns = `-- name: ListAutomationRuns :many
SELECT id, automation_id, enterprise_id, automation_revision, scheduled_for, status, task_id, pending_action_id, result_ref, error_code, created_at, updated_at FROM automation_runs WHERE automation_id = $1 AND enterprise_id = $2 ORDER BY scheduled_for DESC LIMIT $3
`

type ListAutomationRunsParams struct {
	AutomationID uuid.UUID `json:"automation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Limit        int32     `json:"limit"`
}

func (q *Queries) ListAutomationRuns(ctx context.Context, arg ListAutomationRunsParams) ([]AutomationRun, error) {
	rows, err := q.db.Query(ctx, listAutomationRuns, arg.AutomationID, arg.EnterpriseID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationRun{}
	for rows.Next() {
		var i AutomationRun
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.EnterpriseID,
			&i.AutomationRevision,
			&i.ScheduledFor,
			&i.Status,
			&i.TaskID,
			&i.PendingActionID,
			&i.ResultRef,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomations = `-- name: ListAutomations :many
SELECT id, enterprise_id, name, service_account_id, authorization_version, tool_id, tool_input, cron, timezone, status, next_run_at, revision, version, created_at, updated_at FROM automations WHERE enterprise_id = $1 ORDER BY name, id
`

func (q *Queries) ListAutomations(ctx context.Context, enterpriseID uuid.UUID) ([]Automation, error) {
	rows, err := q.db.Query(ctx, listAutomations, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Automation{}
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.Name,
			&i.ServiceAccountID,
			&i.AuthorizationVersion,
			&i.ToolID,
			&i.ToolInput,
			&i.Cron,
			&i.Timezone,
			&i.Status,
			&i.NextRunAt,
			&i.Revision,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAutomationRunExecuting = `-- name: MarkAutomationRunExecuting :exec
UPDATE automation_runs SET status = 'running', updated_at = now()
WHERE pending_action_id = $1 AND enterprise_id = $2 AND status = 'waiting_approval'
`

type MarkAutomationRunExecutingParams struct {
	PendingActionID uuid.NullUUID `json:"pending_action_id"`
	EnterpriseID    uuid.UUID     `json:"enterprise_id"`
}

func (q *Queries) MarkAutomationRunExecuting(ctx context.Context, arg MarkAutomationRunExecutingParams) error {
	_, err := q.db.Exec(ctx, markAutomationRunExecuting, arg.PendingActionID, arg.EnterpriseID)
	return err
}

const setAutomationStatus = `-- name: SetAutomationStatus :one
UPDATE automations SET status = $3, version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND version = $4
RETURNING id, enterprise_id, name, service_account_id, authorization_version, tool_id, tool_input, cron, timezone, status, next_run_at, revision, version, created_at, updated_at
`

type SetAutomationStatusParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Status       string    `json:"status"`
	Version      int64     `json:"version"`
}

func (q *Queries) SetAutomationStatus(ctx context.Context, arg SetAutomationStatusParams) (Automation, error) {
	row := q.db.QueryRow(ctx, setAutomationStatus,
		arg.ID,
		arg.EnterpriseID,
		arg.Status,
		arg.Version,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.ServiceAccountID,
		&i.AuthorizationVersion,
		&i.ToolID,
		&i.ToolInput,
		&i.Cron,
		&i.Timezone,
		&i.Status,
		&i.NextRunAt,
		&i.Revision,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAutomation = `-- name: UpdateAutomation :one
UPDATE automations SET name = $3, service_account_id = $4, authorization_version = $5, tool_id = $6, tool_input = $7,
    cron = $8, timezone = $9, next_run_at = $10, revision = revision + 1,
    version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND version = $11
RETURNING id, enterprise_id, name, service_account_id, authorization_version, tool_id, tool_input, cron, timezone, status, next_run_at, revision, version, created_at, updated_at
`

type UpdateAutomationParams struct {
	ID                   uuid.UUID          `json:"id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	Name                 string             `json:"name"`
	ServiceAccountID     uuid.UUID          `json:"service_account_id"`
	AuthorizationVersion int64              `json:"authorization_version"`
	ToolID               string             `json:"tool_id"`
	ToolInput            []byte             `json:"tool_input"`
	Cron                 string             `json:"cron"`
	Timezone             string             `json:"timezone"`
	NextRunAt            pgtype.Timestamptz `json:"next_run_at"`
	Version              int64              `json:"version"`
}

func (q *Queries) UpdateAutomation(ctx context.Context, arg UpdateAutomationParams) (Automation, error) {
	row := q.db.QueryRow(ctx, updateAutomation,
		arg.ID,
		arg.EnterpriseID,
		arg.Name,
		arg.ServiceAccountID,
		arg.AuthorizationVersion,
		arg.ToolID,
		arg.ToolInput,
		arg.Cron,
		arg.Timezone,
		arg.NextRunAt,
		arg.Version,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.ServiceAccountID,
		&i.AuthorizationVersion,
		&i.ToolID,
		&i.ToolInput,
		&i.Cron,
		&i.Timezone,
		&i.Status,
		&i.NextRunAt,
		&i.Revision,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAutomationRun = `-- name: UpdateAutomationRun :one
UPDATE automation_runs SET status = $3, task_id = $4, pending_action_id = $5, result_ref = $6,
    error_code = $7, updated_at = now() WHERE id = $1 AND enterprise_id = $2 RETURNING id, automation_id, enterprise_id, automation_revision, scheduled_for, status, task_id, pending_action_id, result_ref, error_code, created_at, updated_at
`

type UpdateAutomationRunParams struct {
	ID              uuid.UUID     `json:"id"`
	EnterpriseID    uuid.UUID     `json:"enterprise_id"`
	Status          string        `json:"status"`
	TaskID          uuid.NullUUID `json:"task_id"`
	PendingActionID uuid.NullUUID `json:"pending_action_id"`
	ResultRef       pgtype.Text   `json:"result_ref"`
	ErrorCode       pgtype.Text   `json:"error_code"`
}

func (q *Queries) UpdateAutomationRun(ctx context.Context, arg UpdateAutomationRunParams) (AutomationRun, error) {
	row := q.db.QueryRow(ctx, updateAutomationRun,
		arg.ID,
		arg.EnterpriseID,
		arg.Status,
		arg.TaskID,
		arg.PendingActionID,
		arg.ResultRef,
		arg.ErrorCode,
	)
	var i AutomationRun
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.EnterpriseID,
		&i.AutomationRevision,
		&i.ScheduledFor,
		&i.Status,
		&i.TaskID,
		&i.PendingActionID,
		&i.ResultRef,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
