// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: card.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateInteractiveCard = `-- name: ActivateInteractiveCard :one
UPDATE interactive_cards SET active_version_id = $3, lifecycle = 'active', enabled = true,
    availability = 'available', version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND source = 'enterprise' AND lifecycle <> 'deprecated' AND version = $4
RETURNING id, enterprise_id, source, slug, name, description, lifecycle, enabled, availability, active_version_id, latest_revision, version, created_by, created_at, updated_at
`

type ActivateInteractiveCardParams struct {
	ID              uuid.UUID     `json:"id"`
	EnterpriseID    uuid.NullUUID `json:"enterprise_id"`
	ActiveVersionID uuid.NullUUID `json:"active_version_id"`
	Version         int64         `json:"version"`
}

func (q *Queries) ActivateInteractiveCard(ctx context.Context, arg ActivateInteractiveCardParams) (InteractiveCard, error) {
	row := q.db.QueryRow(ctx, activateInteractiveCard,
		arg.ID,
		arg.EnterpriseID,
		arg.ActiveVersionID,
		arg.Version,
	)
	var i InteractiveCard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Source,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Lifecycle,
		&i.Enabled,
		&i.Availability,
		&i.ActiveVersionID,
		&i.LatestRevision,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeCardActionBinding = `-- name: ConsumeCardActionBinding :one
UPDATE action_bindings SET status = 'consumed', consumed_at = now()
WHERE id = $1 AND enterprise_id = $2 AND status = 'pending' AND expires_at > now()
RETURNING id, binding_ref, pending_action_id, enterprise_id, actor_user_id, action, request_id, status, expires_at, consumed_at, created_at, card_instance_id, conversation_id, authorization_version, binding_source
`

type ConsumeCardActionBindingParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ConsumeCardActionBinding(ctx context.Context, arg ConsumeCardActionBindingParams) (ActionBinding, error) {
	row := q.db.QueryRow(ctx, consumeCardActionBinding, arg.ID, arg.EnterpriseID)
	var i ActionBinding
	err := row.Scan(
		&i.ID,
		&i.BindingRef,
		&i.PendingActionID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.Action,
		&i.RequestID,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.CardInstanceID,
		&i.ConversationID,
		&i.AuthorizationVersion,
		&i.BindingSource,
	)
	return i, err
}

const createCardActionBinding = `-- name: CreateCardActionBinding :one
INSERT INTO action_bindings (id, binding_ref, pending_action_id, enterprise_id, actor_user_id, action,
    request_id, expires_at, card_instance_id, conversation_id, authorization_version, binding_source)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'card')
RETURNING id, binding_ref, pending_action_id, enterprise_id, actor_user_id, action, request_id, status, expires_at, consumed_at, created_at, card_instance_id, conversation_id, authorization_version, binding_source
`

type CreateCardActionBindingParams struct {
	ID                   uuid.UUID          `json:"id"`
	BindingRef           string             `json:"binding_ref"`
	PendingActionID      uuid.UUID          `json:"pending_action_id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	ActorUserID          uuid.NullUUID      `json:"actor_user_id"`
	Action               string             `json:"action"`
	RequestID            string             `json:"request_id"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	CardInstanceID       uuid.NullUUID      `json:"card_instance_id"`
	ConversationID       uuid.NullUUID      `json:"conversation_id"`
	AuthorizationVersion pgtype.Int8        `json:"authorization_version"`
}

func (q *Queries) CreateCardActionBinding(ctx context.Context, arg CreateCardActionBindingParams) (ActionBinding, error) {
	row := q.db.QueryRow(ctx, createCardActionBinding,
		arg.ID,
		arg.BindingRef,
		arg.PendingActionID,
		arg.EnterpriseID,
		arg.ActorUserID,
		arg.Action,
		arg.RequestID,
		arg.ExpiresAt,
		arg.CardInstanceID,
		arg.ConversationID,
		arg.AuthorizationVersion,
	)
	var i ActionBinding
	err := row.Scan(
		&i.ID,
		&i.BindingRef,
		&i.PendingActionID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.Action,
		&i.RequestID,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.CardInstanceID,
		&i.ConversationID,
		&i.AuthorizationVersion,
		&i.BindingSource,
	)
	return i, err
}

const createCardDataSource = `-- name: CreateCardDataSource :one
INSERT INTO card_data_sources (id, card_instance_id, slot_name, tool_call_id, result_ref,
    field_path, output_schema_version, source_hash)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, card_instance_id, slot_name, tool_call_id, result_ref, field_path, output_schema_version, source_hash, created_at
`

type CreateCardDataSourceParams struct {
	ID                  uuid.UUID `json:"id"`
	CardInstanceID      uuid.UUID `json:"card_instance_id"`
	SlotName            string    `json:"slot_name"`
	ToolCallID          uuid.UUID `json:"tool_call_id"`
	ResultRef           string    `json:"result_ref"`
	FieldPath           string    `json:"field_path"`
	OutputSchemaVersion string    `json:"output_schema_version"`
	SourceHash          []byte    `json:"source_hash"`
}

func (q *Queries) CreateCardDataSource(ctx context.Context, arg CreateCardDataSourceParams) (CardDataSource, error) {
	row := q.db.QueryRow(ctx, createCardDataSource,
		arg.ID,
		arg.CardInstanceID,
		arg.SlotName,
		arg.ToolCallID,
		arg.ResultRef,
		arg.FieldPath,
		arg.OutputSchemaVersion,
		arg.SourceHash,
	)
	var i CardDataSource
	err := row.Scan(
		&i.ID,
		&i.CardInstanceID,
		&i.SlotName,
		&i.ToolCallID,
		&i.ResultRef,
		&i.FieldPath,
		&i.OutputSchemaVersion,
		&i.SourceHash,
		&i.CreatedAt,
	)
	return i, err
}

const createCardDemoScenario = `-- name: CreateCardDemoScenario :one
INSERT INTO card_demo_scenarios (id, card_version_id, scenario, data, byte_size)
VALUES ($1,$2,$3,$4,$5) RETURNING id, card_version_id, scenario, data, byte_size, created_at
`

type CreateCardDemoScenarioParams struct {
	ID            uuid.UUID `json:"id"`
	CardVersionID uuid.UUID `json:"card_version_id"`
	Scenario      string    `json:"scenario"`
	Data          []byte    `json:"data"`
	ByteSize      int32     `json:"byte_size"`
}

func (q *Queries) CreateCardDemoScenario(ctx context.Context, arg CreateCardDemoScenarioParams) (CardDemoScenario, error) {
	row := q.db.QueryRow(ctx, createCardDemoScenario,
		arg.ID,
		arg.CardVersionID,
		arg.Scenario,
		arg.Data,
		arg.ByteSize,
	)
	var i CardDemoScenario
	err := row.Scan(
		&i.ID,
		&i.CardVersionID,
		&i.Scenario,
		&i.Data,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const createCardInstance = `-- name: CreateCardInstance :one
INSERT INTO card_instances (id, enterprise_id, conversation_id, run_id, card_id, card_version_id,
    actor_user_id, presentation_kind, render_spec, render_spec_hash)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, enterprise_id, conversation_id, run_id, card_id, card_version_id, actor_user_id, presentation_kind, render_spec, render_spec_hash, status, created_at
`

type CreateCardInstanceParams struct {
	ID               uuid.UUID     `json:"id"`
	EnterpriseID     uuid.UUID     `json:"enterprise_id"`
	ConversationID   uuid.UUID     `json:"conversation_id"`
	RunID            uuid.NullUUID `json:"run_id"`
	CardID           uuid.UUID     `json:"card_id"`
	CardVersionID    uuid.UUID     `json:"card_version_id"`
	ActorUserID      uuid.UUID     `json:"actor_user_id"`
	PresentationKind string        `json:"presentation_kind"`
	RenderSpec       []byte        `json:"render_spec"`
	RenderSpecHash   []byte        `json:"render_spec_hash"`
}

func (q *Queries) CreateCardInstance(ctx context.Context, arg CreateCardInstanceParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, createCardInstance,
		arg.ID,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.RunID,
		arg.CardID,
		arg.CardVersionID,
		arg.ActorUserID,
		arg.PresentationKind,
		arg.RenderSpec,
		arg.RenderSpecHash,
	)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.RunID,
		&i.CardID,
		&i.CardVersionID,
		&i.ActorUserID,
		&i.PresentationKind,
		&i.RenderSpec,
		&i.RenderSpecHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createCardPresentation = `-- name: CreateCardPresentation :one
INSERT INTO card_presentations (id, card_instance_id, enterprise_id, viewer_user_id, authorization_version,
    locale, color_scheme, locale_fallback, initial_data, partial, expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, card_instance_id, enterprise_id, viewer_user_id, authorization_version, locale, color_scheme, locale_fallback, initial_data, partial, expires_at, created_at
`

type CreateCardPresentationParams struct {
	ID                   uuid.UUID          `json:"id"`
	CardInstanceID       uuid.UUID          `json:"card_instance_id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	ViewerUserID         uuid.UUID          `json:"viewer_user_id"`
	AuthorizationVersion int64              `json:"authorization_version"`
	Locale               string             `json:"locale"`
	ColorScheme          string             `json:"color_scheme"`
	LocaleFallback       bool               `json:"locale_fallback"`
	InitialData          []byte             `json:"initial_data"`
	Partial              bool               `json:"partial"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCardPresentation(ctx context.Context, arg CreateCardPresentationParams) (CardPresentation, error) {
	row := q.db.QueryRow(ctx, createCardPresentation,
		arg.ID,
		arg.CardInstanceID,
		arg.EnterpriseID,
		arg.ViewerUserID,
		arg.AuthorizationVersion,
		arg.Locale,
		arg.ColorScheme,
		arg.LocaleFallback,
		arg.InitialData,
		arg.Partial,
		arg.ExpiresAt,
	)
	var i CardPresentation
	err := row.Scan(
		&i.ID,
		&i.CardInstanceID,
		&i.EnterpriseID,
		&i.ViewerUserID,
		&i.AuthorizationVersion,
		&i.Locale,
		&i.ColorScheme,
		&i.LocaleFallback,
		&i.InitialData,
		&i.Partial,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCardQueryBinding = `-- name: CreateCardQueryBinding :one
INSERT INTO card_query_bindings (id, binding_ref, presentation_id, binding_spec_id, enterprise_id,
    viewer_user_id, authorization_version, expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, binding_ref, presentation_id, binding_spec_id, enterprise_id, viewer_user_id, authorization_version, status, expires_at, last_invoked_at, created_at
`

type CreateCardQueryBindingParams struct {
	ID                   uuid.UUID          `json:"id"`
	BindingRef           string             `json:"binding_ref"`
	PresentationID       uuid.UUID          `json:"presentation_id"`
	BindingSpecID        uuid.UUID          `json:"binding_spec_id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	ViewerUserID         uuid.UUID          `json:"viewer_user_id"`
	AuthorizationVersion int64              `json:"authorization_version"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCardQueryBinding(ctx context.Context, arg CreateCardQueryBindingParams) (CardQueryBinding, error) {
	row := q.db.QueryRow(ctx, createCardQueryBinding,
		arg.ID,
		arg.BindingRef,
		arg.PresentationID,
		arg.BindingSpecID,
		arg.EnterpriseID,
		arg.ViewerUserID,
		arg.AuthorizationVersion,
		arg.ExpiresAt,
	)
	var i CardQueryBinding
	err := row.Scan(
		&i.ID,
		&i.BindingRef,
		&i.PresentationID,
		&i.BindingSpecID,
		&i.EnterpriseID,
		&i.ViewerUserID,
		&i.AuthorizationVersion,
		&i.Status,
		&i.ExpiresAt,
		&i.LastInvokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCardQueryBindingSpec = `-- name: CreateCardQueryBindingSpec :one
INSERT INTO card_query_binding_specs (id, card_instance_id, slot_name, tool_id, fixed_input,
    input_hash, output_schema_version, schema_hash)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, card_instance_id, slot_name, tool_id, fixed_input, input_hash, output_schema_version, schema_hash, created_at
`

type CreateCardQueryBindingSpecParams struct {
	ID                  uuid.UUID `json:"id"`
	CardInstanceID      uuid.UUID `json:"card_instance_id"`
	SlotName            string    `json:"slot_name"`
	ToolID              string    `json:"tool_id"`
	FixedInput          []byte    `json:"fixed_input"`
	InputHash           []byte    `json:"input_hash"`
	OutputSchemaVersion string    `json:"output_schema_version"`
	SchemaHash          []byte    `json:"schema_hash"`
}

func (q *Queries) CreateCardQueryBindingSpec(ctx context.Context, arg CreateCardQueryBindingSpecParams) (CardQueryBindingSpec, error) {
	row := q.db.QueryRow(ctx, createCardQueryBindingSpec,
		arg.ID,
		arg.CardInstanceID,
		arg.SlotName,
		arg.ToolID,
		arg.FixedInput,
		arg.InputHash,
		arg.OutputSchemaVersion,
		arg.SchemaHash,
	)
	var i CardQueryBindingSpec
	err := row.Scan(
		&i.ID,
		&i.CardInstanceID,
		&i.SlotName,
		&i.ToolID,
		&i.FixedInput,
		&i.InputHash,
		&i.OutputSchemaVersion,
		&i.SchemaHash,
		&i.CreatedAt,
	)
	return i, err
}

const createCardSlotBinding = `-- name: CreateCardSlotBinding :one
INSERT INTO card_slot_bindings (id, card_version_id, slot_name, slot_kind, mode, tool_id,
    output_schema_version, schema_hash, field_path, value_type, semantic_type)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, card_version_id, slot_name, slot_kind, mode, tool_id, output_schema_version, schema_hash, field_path, value_type, semantic_type, created_at
`

type CreateCardSlotBindingParams struct {
	ID                  uuid.UUID   `json:"id"`
	CardVersionID       uuid.UUID   `json:"card_version_id"`
	SlotName            string      `json:"slot_name"`
	SlotKind            string      `json:"slot_kind"`
	Mode                string      `json:"mode"`
	ToolID              string      `json:"tool_id"`
	OutputSchemaVersion string      `json:"output_schema_version"`
	SchemaHash          []byte      `json:"schema_hash"`
	FieldPath           string      `json:"field_path"`
	ValueType           string      `json:"value_type"`
	SemanticType        pgtype.Text `json:"semantic_type"`
}

func (q *Queries) CreateCardSlotBinding(ctx context.Context, arg CreateCardSlotBindingParams) (CardSlotBinding, error) {
	row := q.db.QueryRow(ctx, createCardSlotBinding,
		arg.ID,
		arg.CardVersionID,
		arg.SlotName,
		arg.SlotKind,
		arg.Mode,
		arg.ToolID,
		arg.OutputSchemaVersion,
		arg.SchemaHash,
		arg.FieldPath,
		arg.ValueType,
		arg.SemanticType,
	)
	var i CardSlotBinding
	err := row.Scan(
		&i.ID,
		&i.CardVersionID,
		&i.SlotName,
		&i.SlotKind,
		&i.Mode,
		&i.ToolID,
		&i.OutputSchemaVersion,
		&i.SchemaHash,
		&i.FieldPath,
		&i.ValueType,
		&i.SemanticType,
		&i.CreatedAt,
	)
	return i, err
}

const createCardValidationRun = `-- name: CreateCardValidationRun :one
INSERT INTO card_validation_runs (id, card_version_id, enterprise_id, actor_user_id, content_hash,
    runtime_version, nonce_hash, required_scenarios, expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, card_version_id, enterprise_id, actor_user_id, content_hash, runtime_version, nonce_hash, status, required_scenarios, passed_scenarios, issues, expires_at, completed_at, created_at
`

type CreateCardValidationRunParams struct {
	ID                uuid.UUID          `json:"id"`
	CardVersionID     uuid.UUID          `json:"card_version_id"`
	EnterpriseID      uuid.UUID          `json:"enterprise_id"`
	ActorUserID       uuid.UUID          `json:"actor_user_id"`
	ContentHash       []byte             `json:"content_hash"`
	RuntimeVersion    string             `json:"runtime_version"`
	NonceHash         []byte             `json:"nonce_hash"`
	RequiredScenarios []string           `json:"required_scenarios"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCardValidationRun(ctx context.Context, arg CreateCardValidationRunParams) (CardValidationRun, error) {
	row := q.db.QueryRow(ctx, createCardValidationRun,
		arg.ID,
		arg.CardVersionID,
		arg.EnterpriseID,
		arg.ActorUserID,
		arg.ContentHash,
		arg.RuntimeVersion,
		arg.NonceHash,
		arg.RequiredScenarios,
		arg.ExpiresAt,
	)
	var i CardValidationRun
	err := row.Scan(
		&i.ID,
		&i.CardVersionID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ContentHash,
		&i.RuntimeVersion,
		&i.NonceHash,
		&i.Status,
		&i.RequiredScenarios,
		&i.PassedScenarios,
		&i.Issues,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCardVersion = `-- name: CreateCardVersion :one
INSERT INTO card_versions (id, card_id, revision, status, manifest, entrypoint_html, content_hash, manifest_hash, created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, card_id, revision, status, manifest, entrypoint_html, content_hash, manifest_hash, created_by, created_at
`

type CreateCardVersionParams struct {
	ID             uuid.UUID     `json:"id"`
	CardID         uuid.UUID     `json:"card_id"`
	Revision       int32         `json:"revision"`
	Status         string        `json:"status"`
	Manifest       []byte        `json:"manifest"`
	EntrypointHtml []byte        `json:"entrypoint_html"`
	ContentHash    []byte        `json:"content_hash"`
	ManifestHash   []byte        `json:"manifest_hash"`
	CreatedBy      uuid.NullUUID `json:"created_by"`
}

func (q *Queries) CreateCardVersion(ctx context.Context, arg CreateCardVersionParams) (CardVersion, error) {
	row := q.db.QueryRow(ctx, createCardVersion,
		arg.ID,
		arg.CardID,
		arg.Revision,
		arg.Status,
		arg.Manifest,
		arg.EntrypointHtml,
		arg.ContentHash,
		arg.ManifestHash,
		arg.CreatedBy,
	)
	var i CardVersion
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Revision,
		&i.Status,
		&i.Manifest,
		&i.EntrypointHtml,
		&i.ContentHash,
		&i.ManifestHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createInteractiveCard = `-- name: CreateInteractiveCard :one
INSERT INTO interactive_cards (id, enterprise_id, source, slug, name, description, lifecycle, enabled,
    availability, latest_revision, created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, enterprise_id, source, slug, name, description, lifecycle, enabled, availability, active_version_id, latest_revision, version, created_by, created_at, updated_at
`

type CreateInteractiveCardParams struct {
	ID             uuid.UUID     `json:"id"`
	EnterpriseID   uuid.NullUUID `json:"enterprise_id"`
	Source         string        `json:"source"`
	Slug           string        `json:"slug"`
	Name           string        `json:"name"`
	Description    string        `json:"description"`
	Lifecycle      string        `json:"lifecycle"`
	Enabled        bool          `json:"enabled"`
	Availability   string        `json:"availability"`
	LatestRevision int32         `json:"latest_revision"`
	CreatedBy      uuid.NullUUID `json:"created_by"`
}

func (q *Queries) CreateInteractiveCard(ctx context.Context, arg CreateInteractiveCardParams) (InteractiveCard, error) {
	row := q.db.QueryRow(ctx, createInteractiveCard,
		arg.ID,
		arg.EnterpriseID,
		arg.Source,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Lifecycle,
		arg.Enabled,
		arg.Availability,
		arg.LatestRevision,
		arg.CreatedBy,
	)
	var i InteractiveCard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Source,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Lifecycle,
		&i.Enabled,
		&i.Availability,
		&i.ActiveVersionID,
		&i.LatestRevision,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSystemCardVersionIfMissing = `-- name: CreateSystemCardVersionIfMissing :one
INSERT INTO card_versions (id, card_id, revision, status, manifest, entrypoint_html, content_hash, manifest_hash)
VALUES ($1,$2,$3,'active',$4,$5,$6,$7)
ON CONFLICT (card_id, revision) DO UPDATE SET status = card_versions.status
RETURNING id, card_id, revision, status, manifest, entrypoint_html, content_hash, manifest_hash, created_by, created_at
`

type CreateSystemCardVersionIfMissingParams struct {
	ID             uuid.UUID `json:"id"`
	CardID         uuid.UUID `json:"card_id"`
	Revision       int32     `json:"revision"`
	Manifest       []byte    `json:"manifest"`
	EntrypointHtml []byte    `json:"entrypoint_html"`
	ContentHash    []byte    `json:"content_hash"`
	ManifestHash   []byte    `json:"manifest_hash"`
}

func (q *Queries) CreateSystemCardVersionIfMissing(ctx context.Context, arg CreateSystemCardVersionIfMissingParams) (CardVersion, error) {
	row := q.db.QueryRow(ctx, createSystemCardVersionIfMissing,
		arg.ID,
		arg.CardID,
		arg.Revision,
		arg.Manifest,
		arg.EntrypointHtml,
		arg.ContentHash,
		arg.ManifestHash,
	)
	var i CardVersion
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Revision,
		&i.Status,
		&i.Manifest,
		&i.EntrypointHtml,
		&i.ContentHash,
		&i.ManifestHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deprecateInteractiveCard = `-- name: DeprecateInteractiveCard :one
UPDATE interactive_cards SET enabled = false, availability = 'disabled', lifecycle = 'deprecated',
    version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND source = 'enterprise' AND lifecycle <> 'deprecated' AND version = $3
RETURNING id, enterprise_id, source, slug, name, description, lifecycle, enabled, availability, active_version_id, latest_revision, version, created_by, created_at, updated_at
`

type DeprecateInteractiveCardParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.NullUUID `json:"enterprise_id"`
	Version      int64         `json:"version"`
}

func (q *Queries) DeprecateInteractiveCard(ctx context.Context, arg DeprecateInteractiveCardParams) (InteractiveCard, error) {
	row := q.db.QueryRow(ctx, deprecateInteractiveCard, arg.ID, arg.EnterpriseID, arg.Version)
	var i InteractiveCard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Source,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Lifecycle,
		&i.Enabled,
		&i.Availability,
		&i.ActiveVersionID,
		&i.LatestRevision,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableInteractiveCard = `-- name: DisableInteractiveCard :one
UPDATE interactive_cards SET enabled = false, availability = 'disabled', version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND source = 'enterprise' AND lifecycle <> 'deprecated' AND version = $3
RETURNING id, enterprise_id, source, slug, name, description, lifecycle, enabled, availability, active_version_id, latest_revision, version, created_by, created_at, updated_at
`

type DisableInteractiveCardParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.NullUUID `json:"enterprise_id"`
	Version      int64         `json:"version"`
}

func (q *Queries) DisableInteractiveCard(ctx context.Context, arg DisableInteractiveCardParams) (InteractiveCard, error) {
	row := q.db.QueryRow(ctx, disableInteractiveCard, arg.ID, arg.EnterpriseID, arg.Version)
	var i InteractiveCard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Source,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Lifecycle,
		&i.Enabled,
		&i.Availability,
		&i.ActiveVersionID,
		&i.LatestRevision,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishCardValidationRun = `-- name: FinishCardValidationRun :one
UPDATE card_validation_runs SET status = $3, passed_scenarios = $4, issues = $5,
    completed_at = now()
WHERE id = $1 AND enterprise_id = $2 AND status = 'pending'
RETURNING id, card_version_id, enterprise_id, actor_user_id, content_hash, runtime_version, nonce_hash, status, required_scenarios, passed_scenarios, issues, expires_at, completed_at, created_at
`

type FinishCardValidationRunParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	Status          string    `json:"status"`
	PassedScenarios []string  `json:"passed_scenarios"`
	Issues          []byte    `json:"issues"`
}

func (q *Queries) FinishCardValidationRun(ctx context.Context, arg FinishCardValidationRunParams) (CardValidationRun, error) {
	row := q.db.QueryRow(ctx, finishCardValidationRun,
		arg.ID,
		arg.EnterpriseID,
		arg.Status,
		arg.PassedScenarios,
		arg.Issues,
	)
	var i CardValidationRun
	err := row.Scan(
		&i.ID,
		&i.CardVersionID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ContentHash,
		&i.RuntimeVersion,
		&i.NonceHash,
		&i.Status,
		&i.RequiredScenarios,
		&i.PassedScenarios,
		&i.Issues,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCardActionBindingForUpdate = `-- name: GetCardActionBindingForUpdate :one
SELECT binding.id, binding.binding_ref, binding.pending_action_id, binding.enterprise_id, binding.actor_user_id, binding.action, binding.request_id, binding.status, binding.expires_at, binding.consumed_at, binding.created_at, binding.card_instance_id, binding.conversation_id, binding.authorization_version, binding.binding_source FROM action_bindings binding
WHERE binding.binding_ref = $1 AND binding.enterprise_id = $2 AND binding.binding_source = 'card'
FOR UPDATE
`

type GetCardActionBindingForUpdateParams struct {
	BindingRef   string    `json:"binding_ref"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetCardActionBindingForUpdate(ctx context.Context, arg GetCardActionBindingForUpdateParams) (ActionBinding, error) {
	row := q.db.QueryRow(ctx, getCardActionBindingForUpdate, arg.BindingRef, arg.EnterpriseID)
	var i ActionBinding
	err := row.Scan(
		&i.ID,
		&i.BindingRef,
		&i.PendingActionID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.Action,
		&i.RequestID,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.CardInstanceID,
		&i.ConversationID,
		&i.AuthorizationVersion,
		&i.BindingSource,
	)
	return i, err
}

const getCardInstanceForViewer = `-- name: GetCardInstanceForViewer :one
SELECT instance.id, instance.enterprise_id, instance.conversation_id, instance.run_id, instance.card_id, instance.card_version_id, instance.actor_user_id, instance.presentation_kind, instance.render_spec, instance.render_spec_hash, instance.status, instance.created_at FROM card_instances instance
JOIN conversations conversation ON conversation.id = instance.conversation_id AND conversation.enterprise_id = instance.enterprise_id
WHERE instance.id = $1 AND instance.enterprise_id = $2 AND conversation.owner_user_id = $3
`

type GetCardInstanceForViewerParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	OwnerUserID  uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetCardInstanceForViewer(ctx context.Context, arg GetCardInstanceForViewerParams) (CardInstance, error) {
	row := q.db.QueryRow(ctx, getCardInstanceForViewer, arg.ID, arg.EnterpriseID, arg.OwnerUserID)
	var i CardInstance
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.RunID,
		&i.CardID,
		&i.CardVersionID,
		&i.ActorUserID,
		&i.PresentationKind,
		&i.RenderSpec,
		&i.RenderSpecHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCardQueryBindingForInvoke = `-- name: GetCardQueryBindingForInvoke :one
SELECT binding.id, binding.binding_ref, binding.presentation_id, binding.binding_spec_id, binding.enterprise_id, binding.viewer_user_id, binding.authorization_version, binding.status, binding.expires_at, binding.last_invoked_at, binding.created_at, spec.card_instance_id, spec.slot_name, spec.tool_id, spec.fixed_input,
    spec.input_hash, spec.output_schema_version, spec.schema_hash
FROM card_query_bindings binding
JOIN card_query_binding_specs spec ON spec.id = binding.binding_spec_id
WHERE binding.binding_ref = $1 AND binding.enterprise_id = $2
`

type GetCardQueryBindingForInvokeParams struct {
	BindingRef   string    `json:"binding_ref"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

type GetCardQueryBindingForInvokeRow struct {
	ID                   uuid.UUID          `json:"id"`
	BindingRef           string             `json:"binding_ref"`
	PresentationID       uuid.UUID          `json:"presentation_id"`
	BindingSpecID        uuid.UUID          `json:"binding_spec_id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	ViewerUserID         uuid.UUID          `json:"viewer_user_id"`
	AuthorizationVersion int64              `json:"authorization_version"`
	Status               string             `json:"status"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	LastInvokedAt        pgtype.Timestamptz `json:"last_invoked_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CardInstanceID       uuid.UUID          `json:"card_instance_id"`
	SlotName             string             `json:"slot_name"`
	ToolID               string             `json:"tool_id"`
	FixedInput           []byte             `json:"fixed_input"`
	InputHash            []byte             `json:"input_hash"`
	OutputSchemaVersion  string             `json:"output_schema_version"`
	SchemaHash           []byte             `json:"schema_hash"`
}

func (q *Queries) GetCardQueryBindingForInvoke(ctx context.Context, arg GetCardQueryBindingForInvokeParams) (GetCardQueryBindingForInvokeRow, error) {
	row := q.db.QueryRow(ctx, getCardQueryBindingForInvoke, arg.BindingRef, arg.EnterpriseID)
	var i GetCardQueryBindingForInvokeRow
	err := row.Scan(
		&i.ID,
		&i.BindingRef,
		&i.PresentationID,
		&i.BindingSpecID,
		&i.EnterpriseID,
		&i.ViewerUserID,
		&i.AuthorizationVersion,
		&i.Status,
		&i.ExpiresAt,
		&i.LastInvokedAt,
		&i.CreatedAt,
		&i.CardInstanceID,
		&i.SlotName,
		&i.ToolID,
		&i.FixedInput,
		&i.InputHash,
		&i.OutputSchemaVersion,
		&i.SchemaHash,
	)
	return i, err
}

const getCardRenderSource = `-- name: GetCardRenderSource :one
SELECT call.id AS tool_call_id, call.run_id, call.tool_id, call.input,
       result.projection, result.partial, artifact.result_ref, artifact.content_hash
FROM tool_calls call
JOIN tool_results result ON result.tool_call_id = call.id
JOIN artifacts artifact ON artifact.id = result.artifact_id
WHERE call.id = $1 AND call.run_id = $2 AND call.enterprise_id = $3
  AND call.status = 'succeeded'
`

type GetCardRenderSourceParams struct {
	ID           uuid.UUID `json:"id"`
	RunID        uuid.UUID `json:"run_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

type GetCardRenderSourceRow struct {
	ToolCallID  uuid.UUID `json:"tool_call_id"`
	RunID       uuid.UUID `json:"run_id"`
	ToolID      string    `json:"tool_id"`
	Input       []byte    `json:"input"`
	Projection  []byte    `json:"projection"`
	Partial     bool      `json:"partial"`
	ResultRef   string    `json:"result_ref"`
	ContentHash []byte    `json:"content_hash"`
}

func (q *Queries) GetCardRenderSource(ctx context.Context, arg GetCardRenderSourceParams) (GetCardRenderSourceRow, error) {
	row := q.db.QueryRow(ctx, getCardRenderSource, arg.ID, arg.RunID, arg.EnterpriseID)
	var i GetCardRenderSourceRow
	err := row.Scan(
		&i.ToolCallID,
		&i.RunID,
		&i.ToolID,
		&i.Input,
		&i.Projection,
		&i.Partial,
		&i.ResultRef,
		&i.ContentHash,
	)
	return i, err
}

const getCardValidationRun = `-- name: GetCardValidationRun :one
SELECT id, card_version_id, enterprise_id, actor_user_id, content_hash, runtime_version, nonce_hash, status, required_scenarios, passed_scenarios, issues, expires_at, completed_at, created_at FROM card_validation_runs WHERE id = $1 AND enterprise_id = $2
`

type GetCardValidationRunParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetCardValidationRun(ctx context.Context, arg GetCardValidationRunParams) (CardValidationRun, error) {
	row := q.db.QueryRow(ctx, getCardValidationRun, arg.ID, arg.EnterpriseID)
	var i CardValidationRun
	err := row.Scan(
		&i.ID,
		&i.CardVersionID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ContentHash,
		&i.RuntimeVersion,
		&i.NonceHash,
		&i.Status,
		&i.RequiredScenarios,
		&i.PassedScenarios,
		&i.Issues,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCardValidationRunForUpdate = `-- name: GetCardValidationRunForUpdate :one
SELECT id, card_version_id, enterprise_id, actor_user_id, content_hash, runtime_version, nonce_hash, status, required_scenarios, passed_scenarios, issues, expires_at, completed_at, created_at FROM card_validation_runs WHERE id = $1 AND enterprise_id = $2 FOR UPDATE
`

type GetCardValidationRunForUpdateParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetCardValidationRunForUpdate(ctx context.Context, arg GetCardValidationRunForUpdateParams) (CardValidationRun, error) {
	row := q.db.QueryRow(ctx, getCardValidationRunForUpdate, arg.ID, arg.EnterpriseID)
	var i CardValidationRun
	err := row.Scan(
		&i.ID,
		&i.CardVersionID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ContentHash,
		&i.RuntimeVersion,
		&i.NonceHash,
		&i.Status,
		&i.RequiredScenarios,
		&i.PassedScenarios,
		&i.Issues,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCardVersion = `-- name: GetCardVersion :one
SELECT version.id, version.card_id, version.revision, version.status, version.manifest, version.entrypoint_html, version.content_hash, version.manifest_hash, version.created_by, version.created_at FROM card_versions version
JOIN interactive_cards card ON card.id = version.card_id
WHERE version.card_id = $1 AND version.revision = $2
  AND (card.source = 'system' OR card.enterprise_id = $3)
`

type GetCardVersionParams struct {
	CardID       uuid.UUID     `json:"card_id"`
	Revision     int32         `json:"revision"`
	EnterpriseID uuid.NullUUID `json:"enterprise_id"`
}

func (q *Queries) GetCardVersion(ctx context.Context, arg GetCardVersionParams) (CardVersion, error) {
	row := q.db.QueryRow(ctx, getCardVersion, arg.CardID, arg.Revision, arg.EnterpriseID)
	var i CardVersion
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Revision,
		&i.Status,
		&i.Manifest,
		&i.EntrypointHtml,
		&i.ContentHash,
		&i.ManifestHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCardVersionByID = `-- name: GetCardVersionByID :one
SELECT id, card_id, revision, status, manifest, entrypoint_html, content_hash, manifest_hash, created_by, created_at FROM card_versions WHERE id = $1
`

func (q *Queries) GetCardVersionByID(ctx context.Context, id uuid.UUID) (CardVersion, error) {
	row := q.db.QueryRow(ctx, getCardVersionByID, id)
	var i CardVersion
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Revision,
		&i.Status,
		&i.Manifest,
		&i.EntrypointHtml,
		&i.ContentHash,
		&i.ManifestHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCardVersionForEnterprise = `-- name: GetCardVersionForEnterprise :one
SELECT version.id, version.card_id, version.revision, version.status, version.manifest, version.entrypoint_html, version.content_hash, version.manifest_hash, version.created_by, version.created_at FROM card_versions version
JOIN interactive_cards card ON card.id = version.card_id
WHERE version.id = $1 AND version.card_id = $2
  AND (card.source = 'system' OR card.enterprise_id = $3)
`

type GetCardVersionForEnterpriseParams struct {
	ID           uuid.UUID     `json:"id"`
	CardID       uuid.UUID     `json:"card_id"`
	EnterpriseID uuid.NullUUID `json:"enterprise_id"`
}

func (q *Queries) GetCardVersionForEnterprise(ctx context.Context, arg GetCardVersionForEnterpriseParams) (CardVersion, error) {
	row := q.db.QueryRow(ctx, getCardVersionForEnterprise, arg.ID, arg.CardID, arg.EnterpriseID)
	var i CardVersion
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Revision,
		&i.Status,
		&i.Manifest,
		&i.EntrypointHtml,
		&i.ContentHash,
		&i.ManifestHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getInteractiveCard = `-- name: GetInteractiveCard :one
SELECT id, enterprise_id, source, slug, name, description, lifecycle, enabled, availability, active_version_id, latest_revision, version, created_by, created_at, updated_at FROM interactive_cards
WHERE id = $1 AND (source = 'system' OR enterprise_id = $2)
`

type GetInteractiveCardParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.NullUUID `json:"enterprise_id"`
}

func (q *Queries) GetInteractiveCard(ctx context.Context, arg GetInteractiveCardParams) (InteractiveCard, error) {
	row := q.db.QueryRow(ctx, getInteractiveCard, arg.ID, arg.EnterpriseID)
	var i InteractiveCard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Source,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Lifecycle,
		&i.Enabled,
		&i.Availability,
		&i.ActiveVersionID,
		&i.LatestRevision,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInteractiveCardForUpdate = `-- name: GetInteractiveCardForUpdate :one
SELECT id, enterprise_id, source, slug, name, description, lifecycle, enabled, availability, active_version_id, latest_revision, version, created_by, created_at, updated_at FROM interactive_cards
WHERE id = $1 AND (source = 'system' OR enterprise_id = $2)
FOR UPDATE
`

type GetInteractiveCardForUpdateParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.NullUUID `json:"enterprise_id"`
}

func (q *Queries) GetInteractiveCardForUpdate(ctx context.Context, arg GetInteractiveCardForUpdateParams) (InteractiveCard, error) {
	row := q.db.QueryRow(ctx, getInteractiveCardForUpdate, arg.ID, arg.EnterpriseID)
	var i InteractiveCard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Source,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Lifecycle,
		&i.Enabled,
		&i.Availability,
		&i.ActiveVersionID,
		&i.LatestRevision,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPassedCardValidation = `-- name: GetLatestPassedCardValidation :one
SELECT id, card_version_id, enterprise_id, actor_user_id, content_hash, runtime_version, nonce_hash, status, required_scenarios, passed_scenarios, issues, expires_at, completed_at, created_at FROM card_validation_runs
WHERE card_version_id = $1 AND enterprise_id = $2 AND status = 'passed' AND expires_at > now()
ORDER BY completed_at DESC LIMIT 1
`

type GetLatestPassedCardValidationParams struct {
	CardVersionID uuid.UUID `json:"card_version_id"`
	EnterpriseID  uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetLatestPassedCardValidation(ctx context.Context, arg GetLatestPassedCardValidationParams) (CardValidationRun, error) {
	row := q.db.QueryRow(ctx, getLatestPassedCardValidation, arg.CardVersionID, arg.EnterpriseID)
	var i CardValidationRun
	err := row.Scan(
		&i.ID,
		&i.CardVersionID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ContentHash,
		&i.RuntimeVersion,
		&i.NonceHash,
		&i.Status,
		&i.RequiredScenarios,
		&i.PassedScenarios,
		&i.Issues,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSystemCardBySlug = `-- name: GetSystemCardBySlug :one
SELECT id, enterprise_id, source, slug, name, description, lifecycle, enabled, availability, active_version_id, latest_revision, version, created_by, created_at, updated_at FROM interactive_cards WHERE source = 'system' AND slug = $1
`

func (q *Queries) GetSystemCardBySlug(ctx context.Context, slug string) (InteractiveCard, error) {
	row := q.db.QueryRow(ctx, getSystemCardBySlug, slug)
	var i InteractiveCard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Source,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Lifecycle,
		&i.Enabled,
		&i.Availability,
		&i.ActiveVersionID,
		&i.LatestRevision,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardDataSources = `-- name: ListCardDataSources :many
SELECT source.id, source.card_instance_id, source.slot_name, source.tool_call_id, source.result_ref, source.field_path, source.output_schema_version, source.source_hash, source.created_at, artifact.content, result.projection, call.input, call.tool_id
FROM card_data_sources source
JOIN artifacts artifact ON artifact.result_ref = source.result_ref
JOIN tool_results result ON result.artifact_id = artifact.id
JOIN tool_calls call ON call.id = source.tool_call_id
WHERE source.card_instance_id = $1
ORDER BY source.slot_name
`

type ListCardDataSourcesRow struct {
	ID                  uuid.UUID          `json:"id"`
	CardInstanceID      uuid.UUID          `json:"card_instance_id"`
	SlotName            string             `json:"slot_name"`
	ToolCallID          uuid.UUID          `json:"tool_call_id"`
	ResultRef           string             `json:"result_ref"`
	FieldPath           string             `json:"field_path"`
	OutputSchemaVersion string             `json:"output_schema_version"`
	SourceHash          []byte             `json:"source_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Content             []byte             `json:"content"`
	Projection          []byte             `json:"projection"`
	Input               []byte             `json:"input"`
	ToolID              string             `json:"tool_id"`
}

func (q *Queries) ListCardDataSources(ctx context.Context, cardInstanceID uuid.UUID) ([]ListCardDataSourcesRow, error) {
	rows, err := q.db.Query(ctx, listCardDataSources, cardInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCardDataSourcesRow{}
	for rows.Next() {
		var i ListCardDataSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.CardInstanceID,
			&i.SlotName,
			&i.ToolCallID,
			&i.ResultRef,
			&i.FieldPath,
			&i.OutputSchemaVersion,
			&i.SourceHash,
			&i.CreatedAt,
			&i.Content,
			&i.Projection,
			&i.Input,
			&i.ToolID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardDemoScenarios = `-- name: ListCardDemoScenarios :many
SELECT id, card_version_id, scenario, data, byte_size, created_at FROM card_demo_scenarios WHERE card_version_id = $1 ORDER BY scenario
`

func (q *Queries) ListCardDemoScenarios(ctx context.Context, cardVersionID uuid.UUID) ([]CardDemoScenario, error) {
	rows, err := q.db.Query(ctx, listCardDemoScenarios, cardVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardDemoScenario{}
	for rows.Next() {
		var i CardDemoScenario
		if err := rows.Scan(
			&i.ID,
			&i.CardVersionID,
			&i.Scenario,
			&i.Data,
			&i.ByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardQueryBindingSpecs = `-- name: ListCardQueryBindingSpecs :many
SELECT id, card_instance_id, slot_name, tool_id, fixed_input, input_hash, output_schema_version, schema_hash, created_at FROM card_query_binding_specs WHERE card_instance_id = $1 ORDER BY slot_name
`

func (q *Queries) ListCardQueryBindingSpecs(ctx context.Context, cardInstanceID uuid.UUID) ([]CardQueryBindingSpec, error) {
	rows, err := q.db.Query(ctx, listCardQueryBindingSpecs, cardInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardQueryBindingSpec{}
	for rows.Next() {
		var i CardQueryBindingSpec
		if err := rows.Scan(
			&i.ID,
			&i.CardInstanceID,
			&i.SlotName,
			&i.ToolID,
			&i.FixedInput,
			&i.InputHash,
			&i.OutputSchemaVersion,
			&i.SchemaHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardSlotBindings = `-- name: ListCardSlotBindings :many
SELECT id, card_version_id, slot_name, slot_kind, mode, tool_id, output_schema_version, schema_hash, field_path, value_type, semantic_type, created_at FROM card_slot_bindings WHERE card_version_id = $1 ORDER BY slot_name
`

func (q *Queries) ListCardSlotBindings(ctx context.Context, cardVersionID uuid.UUID) ([]CardSlotBinding, error) {
	rows, err := q.db.Query(ctx, listCardSlotBindings, cardVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardSlotBinding{}
	for rows.Next() {
		var i CardSlotBinding
		if err := rows.Scan(
			&i.ID,
			&i.CardVersionID,
			&i.SlotName,
			&i.SlotKind,
			&i.Mode,
			&i.ToolID,
			&i.OutputSchemaVersion,
			&i.SchemaHash,
			&i.FieldPath,
			&i.ValueType,
			&i.SemanticType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardVersions = `-- name: ListCardVersions :many
SELECT version.id, version.card_id, version.revision, version.status, version.manifest, version.entrypoint_html, version.content_hash, version.manifest_hash, version.created_by, version.created_at FROM card_versions version
JOIN interactive_cards card ON card.id = version.card_id
WHERE version.card_id = $1 AND (card.source = 'system' OR card.enterprise_id = $2)
ORDER BY version.revision DESC
`

type ListCardVersionsParams struct {
	CardID       uuid.UUID     `json:"card_id"`
	EnterpriseID uuid.NullUUID `json:"enterprise_id"`
}

func (q *Queries) ListCardVersions(ctx context.Context, arg ListCardVersionsParams) ([]CardVersion, error) {
	rows, err := q.db.Query(ctx, listCardVersions, arg.CardID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardVersion{}
	for rows.Next() {
		var i CardVersion
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Revision,
			&i.Status,
			&i.Manifest,
			&i.EntrypointHtml,
			&i.ContentHash,
			&i.ManifestHash,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInteractiveCards = `-- name: ListInteractiveCards :many
SELECT id, enterprise_id, source, slug, name, description, lifecycle, enabled, availability, active_version_id, latest_revision, version, created_by, created_at, updated_at FROM interactive_cards
WHERE source = 'system' OR enterprise_id = $1
ORDER BY source, slug, id
`

func (q *Queries) ListInteractiveCards(ctx context.Context, enterpriseID uuid.NullUUID) ([]InteractiveCard, error) {
	rows, err := q.db.Query(ctx, listInteractiveCards, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InteractiveCard{}
	for rows.Next() {
		var i InteractiveCard
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.Source,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Lifecycle,
			&i.Enabled,
			&i.Availability,
			&i.ActiveVersionID,
			&i.LatestRevision,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCardQueryBindingInvoked = `-- name: MarkCardQueryBindingInvoked :one
UPDATE card_query_bindings SET last_invoked_at = now()
WHERE id = $1 AND enterprise_id = $2 AND status = 'active' AND expires_at > now()
RETURNING id, binding_ref, presentation_id, binding_spec_id, enterprise_id, viewer_user_id, authorization_version, status, expires_at, last_invoked_at, created_at
`

type MarkCardQueryBindingInvokedParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) MarkCardQueryBindingInvoked(ctx context.Context, arg MarkCardQueryBindingInvokedParams) (CardQueryBinding, error) {
	row := q.db.QueryRow(ctx, markCardQueryBindingInvoked, arg.ID, arg.EnterpriseID)
	var i CardQueryBinding
	err := row.Scan(
		&i.ID,
		&i.BindingRef,
		&i.PresentationID,
		&i.BindingSpecID,
		&i.EnterpriseID,
		&i.ViewerUserID,
		&i.AuthorizationVersion,
		&i.Status,
		&i.ExpiresAt,
		&i.LastInvokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const retireActiveCardVersions = `-- name: RetireActiveCardVersions :exec
UPDATE card_versions SET status = 'retired'
WHERE card_id = $1 AND status = 'active' AND id <> $2
`

type RetireActiveCardVersionsParams struct {
	CardID uuid.UUID `json:"card_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) RetireActiveCardVersions(ctx context.Context, arg RetireActiveCardVersionsParams) error {
	_, err := q.db.Exec(ctx, retireActiveCardVersions, arg.CardID, arg.ID)
	return err
}

const setCardVersionStatus = `-- name: SetCardVersionStatus :one
UPDATE card_versions SET status = $2 WHERE id = $1 RETURNING id, card_id, revision, status, manifest, entrypoint_html, content_hash, manifest_hash, created_by, created_at
`

type SetCardVersionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetCardVersionStatus(ctx context.Context, arg SetCardVersionStatusParams) (CardVersion, error) {
	row := q.db.QueryRow(ctx, setCardVersionStatus, arg.ID, arg.Status)
	var i CardVersion
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Revision,
		&i.Status,
		&i.Manifest,
		&i.EntrypointHtml,
		&i.ContentHash,
		&i.ManifestHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const setSystemCardActiveVersion = `-- name: SetSystemCardActiveVersion :one
UPDATE interactive_cards SET active_version_id = $2, lifecycle = 'active', updated_at = now()
WHERE id = $1 AND source = 'system' AND active_version_id IS DISTINCT FROM $2 RETURNING id, enterprise_id, source, slug, name, description, lifecycle, enabled, availability, active_version_id, latest_revision, version, created_by, created_at, updated_at
`

type SetSystemCardActiveVersionParams struct {
	ID              uuid.UUID     `json:"id"`
	ActiveVersionID uuid.NullUUID `json:"active_version_id"`
}

func (q *Queries) SetSystemCardActiveVersion(ctx context.Context, arg SetSystemCardActiveVersionParams) (InteractiveCard, error) {
	row := q.db.QueryRow(ctx, setSystemCardActiveVersion, arg.ID, arg.ActiveVersionID)
	var i InteractiveCard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Source,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Lifecycle,
		&i.Enabled,
		&i.Availability,
		&i.ActiveVersionID,
		&i.LatestRevision,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInteractiveCardDraft = `-- name: UpdateInteractiveCardDraft :one
UPDATE interactive_cards SET name = $3, description = $4, latest_revision = $5,
    version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND source = 'enterprise' AND lifecycle <> 'deprecated' AND version = $6
RETURNING id, enterprise_id, source, slug, name, description, lifecycle, enabled, availability, active_version_id, latest_revision, version, created_by, created_at, updated_at
`

type UpdateInteractiveCardDraftParams struct {
	ID             uuid.UUID     `json:"id"`
	EnterpriseID   uuid.NullUUID `json:"enterprise_id"`
	Name           string        `json:"name"`
	Description    string        `json:"description"`
	LatestRevision int32         `json:"latest_revision"`
	Version        int64         `json:"version"`
}

func (q *Queries) UpdateInteractiveCardDraft(ctx context.Context, arg UpdateInteractiveCardDraftParams) (InteractiveCard, error) {
	row := q.db.QueryRow(ctx, updateInteractiveCardDraft,
		arg.ID,
		arg.EnterpriseID,
		arg.Name,
		arg.Description,
		arg.LatestRevision,
		arg.Version,
	)
	var i InteractiveCard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Source,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Lifecycle,
		&i.Enabled,
		&i.Availability,
		&i.ActiveVersionID,
		&i.LatestRevision,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSystemInteractiveCard = `-- name: UpsertSystemInteractiveCard :one
INSERT INTO interactive_cards (id, source, slug, name, description, lifecycle, enabled, availability, latest_revision)
VALUES ($1,'system',$2,$3,$4,'active',$5,$6,$7)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description,
    enabled = EXCLUDED.enabled, availability = EXCLUDED.availability,
    latest_revision = GREATEST(interactive_cards.latest_revision, EXCLUDED.latest_revision),
    version = interactive_cards.version + 1, updated_at = now()
WHERE (interactive_cards.name, interactive_cards.description, interactive_cards.enabled, interactive_cards.availability, interactive_cards.latest_revision)
    IS DISTINCT FROM (EXCLUDED.name, EXCLUDED.description, EXCLUDED.enabled, EXCLUDED.availability, EXCLUDED.latest_revision)
RETURNING id, enterprise_id, source, slug, name, description, lifecycle, enabled, availability, active_version_id, latest_revision, version, created_by, created_at, updated_at
`

type UpsertSystemInteractiveCardParams struct {
	ID             uuid.UUID `json:"id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	Enabled        bool      `json:"enabled"`
	Availability   string    `json:"availability"`
	LatestRevision int32     `json:"latest_revision"`
}

func (q *Queries) UpsertSystemInteractiveCard(ctx context.Context, arg UpsertSystemInteractiveCardParams) (InteractiveCard, error) {
	row := q.db.QueryRow(ctx, upsertSystemInteractiveCard,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Availability,
		arg.LatestRevision,
	)
	var i InteractiveCard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Source,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Lifecycle,
		&i.Enabled,
		&i.Availability,
		&i.ActiveVersionID,
		&i.LatestRevision,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
