// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connector_install_operations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceConnectorInstallOperation = `-- name: AdvanceConnectorInstallOperation :one
UPDATE connector_install_operations SET
  stage = $4, lease_expires_at = now() + interval '90 seconds', updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND fence = $3
  AND lease_owner <> '' AND status = 'running'
RETURNING id, enterprise_id, connector_id, bastion_scope_id, host_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_mode, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at
`

type AdvanceConnectorInstallOperationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Fence        int64     `json:"fence"`
	Stage        string    `json:"stage"`
}

func (q *Queries) AdvanceConnectorInstallOperation(ctx context.Context, arg AdvanceConnectorInstallOperationParams) (ConnectorInstallOperation, error) {
	row := q.db.QueryRow(ctx, advanceConnectorInstallOperation,
		arg.ID,
		arg.EnterpriseID,
		arg.Fence,
		arg.Stage,
	)
	var i ConnectorInstallOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.BastionScopeID,
		&i.HostID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMode,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimConnectorControlTunnels = `-- name: ClaimConnectorControlTunnels :many
WITH claimed AS (
  SELECT id FROM connector_control_tunnels
  WHERE status IN ('desired','degraded','down')
    AND (lease_expires_at IS NULL OR lease_expires_at < now())
    AND (next_claim_at IS NULL OR next_claim_at <= now())
  ORDER BY last_claim_at ASC NULLS FIRST, id
  LIMIT $1 FOR UPDATE SKIP LOCKED
)
UPDATE connector_control_tunnels AS tunnel SET
  status = 'establishing', lease_owner = $2, fence = fence + 1,
  epoch = epoch + 1, lease_expires_at = now() + interval '90 seconds',
  last_claim_at = now(), updated_at = now()
FROM claimed WHERE tunnel.id = claimed.id RETURNING tunnel.id, tunnel.enterprise_id, tunnel.connector_id, tunnel.bastion_scope_id, tunnel.host_id, tunnel.credential_id, tunnel.credential_version, tunnel.target_address, tunnel.target_port, tunnel.target_username, tunnel.pinned_host_key, tunnel.enroll_forward_target, tunnel.gateway_forward_target, tunnel.status, tunnel.epoch, tunnel.fence, tunnel.lease_owner, tunnel.lease_expires_at, tunnel.last_claim_at, tunnel.last_established_at, tunnel.last_heartbeat_at, tunnel.last_drop_reason, tunnel.reconnect_attempt, tunnel.next_claim_at, tunnel.bytes_relayed, tunnel.throttled_events, tunnel.created_at, tunnel.updated_at
`

type ClaimConnectorControlTunnelsParams struct {
	Limit      int32  `json:"limit"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) ClaimConnectorControlTunnels(ctx context.Context, arg ClaimConnectorControlTunnelsParams) ([]ConnectorControlTunnel, error) {
	rows, err := q.db.Query(ctx, claimConnectorControlTunnels, arg.Limit, arg.LeaseOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorControlTunnel{}
	for rows.Next() {
		var i ConnectorControlTunnel
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.ConnectorID,
			&i.BastionScopeID,
			&i.HostID,
			&i.CredentialID,
			&i.CredentialVersion,
			&i.TargetAddress,
			&i.TargetPort,
			&i.TargetUsername,
			&i.PinnedHostKey,
			&i.EnrollForwardTarget,
			&i.GatewayForwardTarget,
			&i.Status,
			&i.Epoch,
			&i.Fence,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.LastClaimAt,
			&i.LastEstablishedAt,
			&i.LastHeartbeatAt,
			&i.LastDropReason,
			&i.ReconnectAttempt,
			&i.NextClaimAt,
			&i.BytesRelayed,
			&i.ThrottledEvents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimConnectorInstallOperations = `-- name: ClaimConnectorInstallOperations :many
WITH claimed AS (
  SELECT id FROM connector_install_operations
  WHERE status = 'queued' AND attempts < 3 AND expires_at > now()
  ORDER BY created_at, id LIMIT $1 FOR UPDATE SKIP LOCKED
)
UPDATE connector_install_operations AS operation SET
  status = 'running', stage = 'ssh_connecting', lease_owner = $2,
  fence = fence + 1, lease_expires_at = now() + interval '90 seconds',
  attempts = attempts + 1, updated_at = now()
FROM claimed WHERE operation.id = claimed.id RETURNING operation.id, operation.enterprise_id, operation.connector_id, operation.bastion_scope_id, operation.host_id, operation.pending_action_id, operation.retry_of, operation.release_version_id, operation.connection_test_id, operation.install_mode, operation.status, operation.stage, operation.plan, operation.plan_hash, operation.attempts, operation.lease_owner, operation.fence, operation.lease_expires_at, operation.error_code, operation.connector_online_at, operation.expires_at, operation.completed_at, operation.created_at, operation.updated_at
`

type ClaimConnectorInstallOperationsParams struct {
	Limit      int32  `json:"limit"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) ClaimConnectorInstallOperations(ctx context.Context, arg ClaimConnectorInstallOperationsParams) ([]ConnectorInstallOperation, error) {
	rows, err := q.db.Query(ctx, claimConnectorInstallOperations, arg.Limit, arg.LeaseOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorInstallOperation{}
	for rows.Next() {
		var i ConnectorInstallOperation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.ConnectorID,
			&i.BastionScopeID,
			&i.HostID,
			&i.PendingActionID,
			&i.RetryOf,
			&i.ReleaseVersionID,
			&i.ConnectionTestID,
			&i.InstallMode,
			&i.Status,
			&i.Stage,
			&i.Plan,
			&i.PlanHash,
			&i.Attempts,
			&i.LeaseOwner,
			&i.Fence,
			&i.LeaseExpiresAt,
			&i.ErrorCode,
			&i.ConnectorOnlineAt,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const consumeConnectorInstallOperationSecret = `-- name: ConsumeConnectorInstallOperationSecret :execrows
UPDATE connector_install_operation_secrets SET consumed_at = now()
WHERE operation_id = $1 AND enterprise_id = $2 AND consumed_at IS NULL
`

type ConsumeConnectorInstallOperationSecretParams struct {
	OperationID  uuid.UUID `json:"operation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ConsumeConnectorInstallOperationSecret(ctx context.Context, arg ConsumeConnectorInstallOperationSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeConnectorInstallOperationSecret, arg.OperationID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOwnedConnectorControlTunnels = `-- name: CountOwnedConnectorControlTunnels :one
SELECT count(*)::bigint FROM connector_control_tunnels
WHERE lease_owner = $1 AND status IN ('establishing','established')
`

func (q *Queries) CountOwnedConnectorControlTunnels(ctx context.Context, leaseOwner string) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedConnectorControlTunnels, leaseOwner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createConnectorControlTunnel = `-- name: CreateConnectorControlTunnel :one
INSERT INTO connector_control_tunnels (
  id, enterprise_id, connector_id, bastion_scope_id, host_id,
  credential_id, credential_version, target_address, target_port,
  target_username, pinned_host_key, enroll_forward_target,
  gateway_forward_target, status
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'desired')
ON CONFLICT (connector_id) DO UPDATE SET
  credential_id = EXCLUDED.credential_id,
  credential_version = EXCLUDED.credential_version,
  target_address = EXCLUDED.target_address,
  target_port = EXCLUDED.target_port,
  target_username = EXCLUDED.target_username,
  pinned_host_key = EXCLUDED.pinned_host_key,
  enroll_forward_target = EXCLUDED.enroll_forward_target,
  gateway_forward_target = EXCLUDED.gateway_forward_target,
  status = 'desired', epoch = connector_control_tunnels.epoch + 1,
  lease_owner = '', lease_expires_at = NULL, last_drop_reason = '',
  reconnect_attempt = 0, next_claim_at = NULL, updated_at = now()
RETURNING id, enterprise_id, connector_id, bastion_scope_id, host_id, credential_id, credential_version, target_address, target_port, target_username, pinned_host_key, enroll_forward_target, gateway_forward_target, status, epoch, fence, lease_owner, lease_expires_at, last_claim_at, last_established_at, last_heartbeat_at, last_drop_reason, reconnect_attempt, next_claim_at, bytes_relayed, throttled_events, created_at, updated_at
`

type CreateConnectorControlTunnelParams struct {
	ID                   uuid.UUID `json:"id"`
	EnterpriseID         uuid.UUID `json:"enterprise_id"`
	ConnectorID          uuid.UUID `json:"connector_id"`
	BastionScopeID       uuid.UUID `json:"bastion_scope_id"`
	HostID               uuid.UUID `json:"host_id"`
	CredentialID         uuid.UUID `json:"credential_id"`
	CredentialVersion    int64     `json:"credential_version"`
	TargetAddress        string    `json:"target_address"`
	TargetPort           int32     `json:"target_port"`
	TargetUsername       string    `json:"target_username"`
	PinnedHostKey        string    `json:"pinned_host_key"`
	EnrollForwardTarget  string    `json:"enroll_forward_target"`
	GatewayForwardTarget string    `json:"gateway_forward_target"`
}

func (q *Queries) CreateConnectorControlTunnel(ctx context.Context, arg CreateConnectorControlTunnelParams) (ConnectorControlTunnel, error) {
	row := q.db.QueryRow(ctx, createConnectorControlTunnel,
		arg.ID,
		arg.EnterpriseID,
		arg.ConnectorID,
		arg.BastionScopeID,
		arg.HostID,
		arg.CredentialID,
		arg.CredentialVersion,
		arg.TargetAddress,
		arg.TargetPort,
		arg.TargetUsername,
		arg.PinnedHostKey,
		arg.EnrollForwardTarget,
		arg.GatewayForwardTarget,
	)
	var i ConnectorControlTunnel
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.BastionScopeID,
		&i.HostID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.TargetAddress,
		&i.TargetPort,
		&i.TargetUsername,
		&i.PinnedHostKey,
		&i.EnrollForwardTarget,
		&i.GatewayForwardTarget,
		&i.Status,
		&i.Epoch,
		&i.Fence,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.LastClaimAt,
		&i.LastEstablishedAt,
		&i.LastHeartbeatAt,
		&i.LastDropReason,
		&i.ReconnectAttempt,
		&i.NextClaimAt,
		&i.BytesRelayed,
		&i.ThrottledEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConnectorInstallOperation = `-- name: CreateConnectorInstallOperation :one
INSERT INTO connector_install_operations (
  id, enterprise_id, connector_id, bastion_scope_id, host_id, pending_action_id,
  retry_of, release_version_id, connection_test_id, install_mode, plan, plan_hash,
  expires_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
RETURNING id, enterprise_id, connector_id, bastion_scope_id, host_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_mode, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at
`

type CreateConnectorInstallOperationParams struct {
	ID               uuid.UUID          `json:"id"`
	EnterpriseID     uuid.UUID          `json:"enterprise_id"`
	ConnectorID      uuid.UUID          `json:"connector_id"`
	BastionScopeID   uuid.UUID          `json:"bastion_scope_id"`
	HostID           uuid.UUID          `json:"host_id"`
	PendingActionID  uuid.UUID          `json:"pending_action_id"`
	RetryOf          uuid.NullUUID      `json:"retry_of"`
	ReleaseVersionID uuid.UUID          `json:"release_version_id"`
	ConnectionTestID uuid.UUID          `json:"connection_test_id"`
	InstallMode      string             `json:"install_mode"`
	Plan             []byte             `json:"plan"`
	PlanHash         []byte             `json:"plan_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateConnectorInstallOperation(ctx context.Context, arg CreateConnectorInstallOperationParams) (ConnectorInstallOperation, error) {
	row := q.db.QueryRow(ctx, createConnectorInstallOperation,
		arg.ID,
		arg.EnterpriseID,
		arg.ConnectorID,
		arg.BastionScopeID,
		arg.HostID,
		arg.PendingActionID,
		arg.RetryOf,
		arg.ReleaseVersionID,
		arg.ConnectionTestID,
		arg.InstallMode,
		arg.Plan,
		arg.PlanHash,
		arg.ExpiresAt,
	)
	var i ConnectorInstallOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.BastionScopeID,
		&i.HostID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMode,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConnectorInstallOperationEvent = `-- name: CreateConnectorInstallOperationEvent :one
INSERT INTO connector_install_operation_events (
  id, operation_id, enterprise_id, sequence, stage, status, error_code
) VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, operation_id, enterprise_id, sequence, stage, status, error_code, occurred_at
`

type CreateConnectorInstallOperationEventParams struct {
	ID           uuid.UUID   `json:"id"`
	OperationID  uuid.UUID   `json:"operation_id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	Sequence     int64       `json:"sequence"`
	Stage        string      `json:"stage"`
	Status       string      `json:"status"`
	ErrorCode    pgtype.Text `json:"error_code"`
}

func (q *Queries) CreateConnectorInstallOperationEvent(ctx context.Context, arg CreateConnectorInstallOperationEventParams) (ConnectorInstallOperationEvent, error) {
	row := q.db.QueryRow(ctx, createConnectorInstallOperationEvent,
		arg.ID,
		arg.OperationID,
		arg.EnterpriseID,
		arg.Sequence,
		arg.Stage,
		arg.Status,
		arg.ErrorCode,
	)
	var i ConnectorInstallOperationEvent
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.EnterpriseID,
		&i.Sequence,
		&i.Stage,
		&i.Status,
		&i.ErrorCode,
		&i.OccurredAt,
	)
	return i, err
}

const createConnectorInstallOperationSecret = `-- name: CreateConnectorInstallOperationSecret :one
INSERT INTO connector_install_operation_secrets (
  operation_id, enterprise_id, key_version, nonce, ciphertext, expires_at
) VALUES ($1,$2,$3,$4,$5,$6)
RETURNING operation_id, enterprise_id, key_version, nonce, ciphertext, expires_at, consumed_at, created_at
`

type CreateConnectorInstallOperationSecretParams struct {
	OperationID  uuid.UUID          `json:"operation_id"`
	EnterpriseID uuid.UUID          `json:"enterprise_id"`
	KeyVersion   int32              `json:"key_version"`
	Nonce        []byte             `json:"nonce"`
	Ciphertext   []byte             `json:"ciphertext"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateConnectorInstallOperationSecret(ctx context.Context, arg CreateConnectorInstallOperationSecretParams) (ConnectorInstallOperationSecret, error) {
	row := q.db.QueryRow(ctx, createConnectorInstallOperationSecret,
		arg.OperationID,
		arg.EnterpriseID,
		arg.KeyVersion,
		arg.Nonce,
		arg.Ciphertext,
		arg.ExpiresAt,
	)
	var i ConnectorInstallOperationSecret
	err := row.Scan(
		&i.OperationID,
		&i.EnterpriseID,
		&i.KeyVersion,
		&i.Nonce,
		&i.Ciphertext,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createConnectorReleaseVersion = `-- name: CreateConnectorReleaseVersion :one

INSERT INTO connector_release_versions (id, version, status, manifest, manifest_hash)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (version) DO UPDATE SET
  status = EXCLUDED.status, updated_at = now()
WHERE connector_release_versions.manifest_hash = EXCLUDED.manifest_hash
RETURNING id, version, status, manifest, manifest_hash, created_at, updated_at
`

type CreateConnectorReleaseVersionParams struct {
	ID           uuid.UUID `json:"id"`
	Version      string    `json:"version"`
	Status       string    `json:"status"`
	Manifest     []byte    `json:"manifest"`
	ManifestHash []byte    `json:"manifest_hash"`
}

// PlanV4 Connector 发行、B/C 安装 operation 与模式 C 长期控制隧道。
func (q *Queries) CreateConnectorReleaseVersion(ctx context.Context, arg CreateConnectorReleaseVersionParams) (ConnectorReleaseVersion, error) {
	row := q.db.QueryRow(ctx, createConnectorReleaseVersion,
		arg.ID,
		arg.Version,
		arg.Status,
		arg.Manifest,
		arg.ManifestHash,
	)
	var i ConnectorReleaseVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Status,
		&i.Manifest,
		&i.ManifestHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnectorInstallOperationSecret = `-- name: DeleteConnectorInstallOperationSecret :execrows
DELETE FROM connector_install_operation_secrets WHERE operation_id = $1 AND enterprise_id = $2
`

type DeleteConnectorInstallOperationSecretParams struct {
	OperationID  uuid.UUID `json:"operation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) DeleteConnectorInstallOperationSecret(ctx context.Context, arg DeleteConnectorInstallOperationSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectorInstallOperationSecret, arg.OperationID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireConnectorInstallOperations = `-- name: ExpireConnectorInstallOperations :execrows
UPDATE connector_install_operations SET status = 'expired', error_code = 'CONNECTOR_INSTALL_EXPIRED', updated_at = now()
WHERE status = 'queued' AND expires_at <= now()
`

func (q *Queries) ExpireConnectorInstallOperations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireConnectorInstallOperations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishConnectorInstallOperation = `-- name: FinishConnectorInstallOperation :one
UPDATE connector_install_operations SET
  status = $4, stage = CASE WHEN $4 = 'succeeded' THEN 'completed' ELSE stage END,
  error_code = $5, lease_owner = '', lease_expires_at = NULL,
  completed_at = now(), updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND fence = $3
RETURNING id, enterprise_id, connector_id, bastion_scope_id, host_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_mode, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at
`

type FinishConnectorInstallOperationParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	Fence        int64       `json:"fence"`
	Status       string      `json:"status"`
	ErrorCode    pgtype.Text `json:"error_code"`
}

func (q *Queries) FinishConnectorInstallOperation(ctx context.Context, arg FinishConnectorInstallOperationParams) (ConnectorInstallOperation, error) {
	row := q.db.QueryRow(ctx, finishConnectorInstallOperation,
		arg.ID,
		arg.EnterpriseID,
		arg.Fence,
		arg.Status,
		arg.ErrorCode,
	)
	var i ConnectorInstallOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.BastionScopeID,
		&i.HostID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMode,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveConnectorReleaseVersion = `-- name: GetActiveConnectorReleaseVersion :one
SELECT id, version, status, manifest, manifest_hash, created_at, updated_at FROM connector_release_versions WHERE status = 'active'
ORDER BY created_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetActiveConnectorReleaseVersion(ctx context.Context) (ConnectorReleaseVersion, error) {
	row := q.db.QueryRow(ctx, getActiveConnectorReleaseVersion)
	var i ConnectorReleaseVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Status,
		&i.Manifest,
		&i.ManifestHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorControlTunnel = `-- name: GetConnectorControlTunnel :one
SELECT id, enterprise_id, connector_id, bastion_scope_id, host_id, credential_id, credential_version, target_address, target_port, target_username, pinned_host_key, enroll_forward_target, gateway_forward_target, status, epoch, fence, lease_owner, lease_expires_at, last_claim_at, last_established_at, last_heartbeat_at, last_drop_reason, reconnect_attempt, next_claim_at, bytes_relayed, throttled_events, created_at, updated_at FROM connector_control_tunnels WHERE id = $1 AND enterprise_id = $2
`

type GetConnectorControlTunnelParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetConnectorControlTunnel(ctx context.Context, arg GetConnectorControlTunnelParams) (ConnectorControlTunnel, error) {
	row := q.db.QueryRow(ctx, getConnectorControlTunnel, arg.ID, arg.EnterpriseID)
	var i ConnectorControlTunnel
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.BastionScopeID,
		&i.HostID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.TargetAddress,
		&i.TargetPort,
		&i.TargetUsername,
		&i.PinnedHostKey,
		&i.EnrollForwardTarget,
		&i.GatewayForwardTarget,
		&i.Status,
		&i.Epoch,
		&i.Fence,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.LastClaimAt,
		&i.LastEstablishedAt,
		&i.LastHeartbeatAt,
		&i.LastDropReason,
		&i.ReconnectAttempt,
		&i.NextClaimAt,
		&i.BytesRelayed,
		&i.ThrottledEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorControlTunnelByConnector = `-- name: GetConnectorControlTunnelByConnector :one
SELECT id, enterprise_id, connector_id, bastion_scope_id, host_id, credential_id, credential_version, target_address, target_port, target_username, pinned_host_key, enroll_forward_target, gateway_forward_target, status, epoch, fence, lease_owner, lease_expires_at, last_claim_at, last_established_at, last_heartbeat_at, last_drop_reason, reconnect_attempt, next_claim_at, bytes_relayed, throttled_events, created_at, updated_at FROM connector_control_tunnels WHERE connector_id = $1 AND enterprise_id = $2
`

type GetConnectorControlTunnelByConnectorParams struct {
	ConnectorID  uuid.UUID `json:"connector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetConnectorControlTunnelByConnector(ctx context.Context, arg GetConnectorControlTunnelByConnectorParams) (ConnectorControlTunnel, error) {
	row := q.db.QueryRow(ctx, getConnectorControlTunnelByConnector, arg.ConnectorID, arg.EnterpriseID)
	var i ConnectorControlTunnel
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.BastionScopeID,
		&i.HostID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.TargetAddress,
		&i.TargetPort,
		&i.TargetUsername,
		&i.PinnedHostKey,
		&i.EnrollForwardTarget,
		&i.GatewayForwardTarget,
		&i.Status,
		&i.Epoch,
		&i.Fence,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.LastClaimAt,
		&i.LastEstablishedAt,
		&i.LastHeartbeatAt,
		&i.LastDropReason,
		&i.ReconnectAttempt,
		&i.NextClaimAt,
		&i.BytesRelayed,
		&i.ThrottledEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorInstallOperation = `-- name: GetConnectorInstallOperation :one
SELECT id, enterprise_id, connector_id, bastion_scope_id, host_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_mode, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at FROM connector_install_operations WHERE id = $1 AND enterprise_id = $2
`

type GetConnectorInstallOperationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetConnectorInstallOperation(ctx context.Context, arg GetConnectorInstallOperationParams) (ConnectorInstallOperation, error) {
	row := q.db.QueryRow(ctx, getConnectorInstallOperation, arg.ID, arg.EnterpriseID)
	var i ConnectorInstallOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.BastionScopeID,
		&i.HostID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMode,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorInstallOperationSecret = `-- name: GetConnectorInstallOperationSecret :one
SELECT operation_id, enterprise_id, key_version, nonce, ciphertext, expires_at, consumed_at, created_at FROM connector_install_operation_secrets
WHERE operation_id = $1 AND enterprise_id = $2 AND expires_at > now()
`

type GetConnectorInstallOperationSecretParams struct {
	OperationID  uuid.UUID `json:"operation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetConnectorInstallOperationSecret(ctx context.Context, arg GetConnectorInstallOperationSecretParams) (ConnectorInstallOperationSecret, error) {
	row := q.db.QueryRow(ctx, getConnectorInstallOperationSecret, arg.OperationID, arg.EnterpriseID)
	var i ConnectorInstallOperationSecret
	err := row.Scan(
		&i.OperationID,
		&i.EnterpriseID,
		&i.KeyVersion,
		&i.Nonce,
		&i.Ciphertext,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getConnectorReleaseVersion = `-- name: GetConnectorReleaseVersion :one
SELECT id, version, status, manifest, manifest_hash, created_at, updated_at FROM connector_release_versions WHERE id = $1
`

func (q *Queries) GetConnectorReleaseVersion(ctx context.Context, id uuid.UUID) (ConnectorReleaseVersion, error) {
	row := q.db.QueryRow(ctx, getConnectorReleaseVersion, id)
	var i ConnectorReleaseVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Status,
		&i.Manifest,
		&i.ManifestHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestConnectorInstallOperation = `-- name: GetLatestConnectorInstallOperation :one
SELECT id, enterprise_id, connector_id, bastion_scope_id, host_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_mode, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at FROM connector_install_operations
WHERE connector_id = $1 AND enterprise_id = $2
ORDER BY created_at DESC, id DESC LIMIT 1
`

type GetLatestConnectorInstallOperationParams struct {
	ConnectorID  uuid.UUID `json:"connector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetLatestConnectorInstallOperation(ctx context.Context, arg GetLatestConnectorInstallOperationParams) (ConnectorInstallOperation, error) {
	row := q.db.QueryRow(ctx, getLatestConnectorInstallOperation, arg.ConnectorID, arg.EnterpriseID)
	var i ConnectorInstallOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.BastionScopeID,
		&i.HostID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMode,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestConnectorInstallOperationByScope = `-- name: GetLatestConnectorInstallOperationByScope :one
SELECT id, enterprise_id, connector_id, bastion_scope_id, host_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_mode, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at FROM connector_install_operations
WHERE bastion_scope_id = $1 AND enterprise_id = $2
ORDER BY created_at DESC, id DESC LIMIT 1
`

type GetLatestConnectorInstallOperationByScopeParams struct {
	BastionScopeID uuid.UUID `json:"bastion_scope_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetLatestConnectorInstallOperationByScope(ctx context.Context, arg GetLatestConnectorInstallOperationByScopeParams) (ConnectorInstallOperation, error) {
	row := q.db.QueryRow(ctx, getLatestConnectorInstallOperationByScope, arg.BastionScopeID, arg.EnterpriseID)
	var i ConnectorInstallOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.BastionScopeID,
		&i.HostID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMode,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatConnectorControlTunnel = `-- name: HeartbeatConnectorControlTunnel :execrows
UPDATE connector_control_tunnels SET
  last_heartbeat_at = now(), lease_expires_at = now() + interval '90 seconds',
  bytes_relayed = bytes_relayed + $5, throttled_events = throttled_events + $6, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND fence = $3 AND lease_owner = $4
  AND status = 'established'
`

type HeartbeatConnectorControlTunnelParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	Fence           int64     `json:"fence"`
	LeaseOwner      string    `json:"lease_owner"`
	BytesRelayed    int64     `json:"bytes_relayed"`
	ThrottledEvents int64     `json:"throttled_events"`
}

func (q *Queries) HeartbeatConnectorControlTunnel(ctx context.Context, arg HeartbeatConnectorControlTunnelParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatConnectorControlTunnel,
		arg.ID,
		arg.EnterpriseID,
		arg.Fence,
		arg.LeaseOwner,
		arg.BytesRelayed,
		arg.ThrottledEvents,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listConnectorInstallOperationEvents = `-- name: ListConnectorInstallOperationEvents :many
SELECT id, operation_id, enterprise_id, sequence, stage, status, error_code, occurred_at FROM connector_install_operation_events
WHERE operation_id = $1 AND enterprise_id = $2 ORDER BY sequence
`

type ListConnectorInstallOperationEventsParams struct {
	OperationID  uuid.UUID `json:"operation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ListConnectorInstallOperationEvents(ctx context.Context, arg ListConnectorInstallOperationEventsParams) ([]ConnectorInstallOperationEvent, error) {
	rows, err := q.db.Query(ctx, listConnectorInstallOperationEvents, arg.OperationID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorInstallOperationEvent{}
	for rows.Next() {
		var i ConnectorInstallOperationEvent
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.EnterpriseID,
			&i.Sequence,
			&i.Stage,
			&i.Status,
			&i.ErrorCode,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConnectorControlTunnelDropped = `-- name: MarkConnectorControlTunnelDropped :execrows
UPDATE connector_control_tunnels SET
  status = $5, last_drop_reason = $6, lease_owner = '', lease_expires_at = NULL,
  reconnect_attempt = LEAST(reconnect_attempt + 1, 30),
  next_claim_at = now() + make_interval(secs => CASE LEAST(reconnect_attempt + 1, 6)
    WHEN 1 THEN 1 WHEN 2 THEN 2 WHEN 3 THEN 4 WHEN 4 THEN 8 WHEN 5 THEN 16 ELSE 30 END),
  updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND fence = $3 AND lease_owner = $4
`

type MarkConnectorControlTunnelDroppedParams struct {
	ID             uuid.UUID `json:"id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	Fence          int64     `json:"fence"`
	LeaseOwner     string    `json:"lease_owner"`
	Status         string    `json:"status"`
	LastDropReason string    `json:"last_drop_reason"`
}

func (q *Queries) MarkConnectorControlTunnelDropped(ctx context.Context, arg MarkConnectorControlTunnelDroppedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConnectorControlTunnelDropped,
		arg.ID,
		arg.EnterpriseID,
		arg.Fence,
		arg.LeaseOwner,
		arg.Status,
		arg.LastDropReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markConnectorControlTunnelEstablished = `-- name: MarkConnectorControlTunnelEstablished :one
UPDATE connector_control_tunnels SET
  status = 'established', last_established_at = now(), last_heartbeat_at = now(),
  lease_expires_at = now() + interval '90 seconds', last_drop_reason = '',
  reconnect_attempt = 0, next_claim_at = NULL, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND fence = $3 AND lease_owner = $4
RETURNING id, enterprise_id, connector_id, bastion_scope_id, host_id, credential_id, credential_version, target_address, target_port, target_username, pinned_host_key, enroll_forward_target, gateway_forward_target, status, epoch, fence, lease_owner, lease_expires_at, last_claim_at, last_established_at, last_heartbeat_at, last_drop_reason, reconnect_attempt, next_claim_at, bytes_relayed, throttled_events, created_at, updated_at
`

type MarkConnectorControlTunnelEstablishedParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Fence        int64     `json:"fence"`
	LeaseOwner   string    `json:"lease_owner"`
}

func (q *Queries) MarkConnectorControlTunnelEstablished(ctx context.Context, arg MarkConnectorControlTunnelEstablishedParams) (ConnectorControlTunnel, error) {
	row := q.db.QueryRow(ctx, markConnectorControlTunnelEstablished,
		arg.ID,
		arg.EnterpriseID,
		arg.Fence,
		arg.LeaseOwner,
	)
	var i ConnectorControlTunnel
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.BastionScopeID,
		&i.HostID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.TargetAddress,
		&i.TargetPort,
		&i.TargetUsername,
		&i.PinnedHostKey,
		&i.EnrollForwardTarget,
		&i.GatewayForwardTarget,
		&i.Status,
		&i.Epoch,
		&i.Fence,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.LastClaimAt,
		&i.LastEstablishedAt,
		&i.LastHeartbeatAt,
		&i.LastDropReason,
		&i.ReconnectAttempt,
		&i.NextClaimAt,
		&i.BytesRelayed,
		&i.ThrottledEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markConnectorControlTunnelRemoved = `-- name: MarkConnectorControlTunnelRemoved :execrows
UPDATE connector_control_tunnels SET
  status = 'removed', last_drop_reason = $3, epoch = epoch + 1,
  lease_owner = '', lease_expires_at = NULL, next_claim_at = NULL, updated_at = now()
WHERE connector_id = $1 AND enterprise_id = $2 AND status <> 'removed'
`

type MarkConnectorControlTunnelRemovedParams struct {
	ConnectorID    uuid.UUID `json:"connector_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	LastDropReason string    `json:"last_drop_reason"`
}

func (q *Queries) MarkConnectorControlTunnelRemoved(ctx context.Context, arg MarkConnectorControlTunnelRemovedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConnectorControlTunnelRemoved, arg.ConnectorID, arg.EnterpriseID, arg.LastDropReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markConnectorControlTunnelsRemovedByScope = `-- name: MarkConnectorControlTunnelsRemovedByScope :execrows
UPDATE connector_control_tunnels SET
  status = 'removed', last_drop_reason = $3, epoch = epoch + 1,
  lease_owner = '', lease_expires_at = NULL, next_claim_at = NULL, updated_at = now()
WHERE bastion_scope_id = $1 AND enterprise_id = $2 AND status <> 'removed'
`

type MarkConnectorControlTunnelsRemovedByScopeParams struct {
	BastionScopeID uuid.UUID `json:"bastion_scope_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	LastDropReason string    `json:"last_drop_reason"`
}

func (q *Queries) MarkConnectorControlTunnelsRemovedByScope(ctx context.Context, arg MarkConnectorControlTunnelsRemovedByScopeParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConnectorControlTunnelsRemovedByScope, arg.BastionScopeID, arg.EnterpriseID, arg.LastDropReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markConnectorInstallOnline = `-- name: MarkConnectorInstallOnline :one
UPDATE connector_install_operations SET connector_online_at = now(), updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND status IN ('running','result_unknown')
RETURNING id, enterprise_id, connector_id, bastion_scope_id, host_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_mode, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at
`

type MarkConnectorInstallOnlineParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) MarkConnectorInstallOnline(ctx context.Context, arg MarkConnectorInstallOnlineParams) (ConnectorInstallOperation, error) {
	row := q.db.QueryRow(ctx, markConnectorInstallOnline, arg.ID, arg.EnterpriseID)
	var i ConnectorInstallOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.BastionScopeID,
		&i.HostID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMode,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOverdueConnectorControlTunnelQuota = `-- name: MarkOverdueConnectorControlTunnelQuota :execrows
WITH candidate AS (
  SELECT id FROM connector_control_tunnels
  WHERE status IN ('desired','down') AND lease_owner = ''
    AND created_at < now() - interval '30 seconds'
    AND (next_claim_at IS NULL OR next_claim_at <= now())
  ORDER BY created_at, id LIMIT 1 FOR UPDATE SKIP LOCKED
)
UPDATE connector_control_tunnels AS tunnel SET status = 'down', last_drop_reason = 'tunnel_quota_exceeded',
  reconnect_attempt = LEAST(reconnect_attempt + 1, 30), next_claim_at = now() + interval '30 seconds', updated_at = now()
FROM candidate WHERE tunnel.id = candidate.id
`

func (q *Queries) MarkOverdueConnectorControlTunnelQuota(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markOverdueConnectorControlTunnelQuota)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recoverConnectorInstallOperations = `-- name: RecoverConnectorInstallOperations :execrows
UPDATE connector_install_operations SET
  status = CASE
    WHEN expires_at <= now() THEN 'expired'
    WHEN attempts < 3 THEN 'queued'
    ELSE 'result_unknown'
  END,
  lease_owner = '', lease_expires_at = NULL,
  error_code = CASE WHEN attempts >= 3 THEN 'CONNECTOR_INSTALL_RESULT_UNKNOWN' ELSE error_code END,
  updated_at = now()
WHERE status = 'running' AND (lease_expires_at IS NULL OR lease_expires_at < now())
`

func (q *Queries) RecoverConnectorInstallOperations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverConnectorInstallOperations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recoverExpiredConnectorControlTunnels = `-- name: RecoverExpiredConnectorControlTunnels :execrows
UPDATE connector_control_tunnels SET
  status = 'down', last_drop_reason = 'lease_expired', lease_owner = '',
  lease_expires_at = NULL, reconnect_attempt = LEAST(reconnect_attempt + 1, 30),
  next_claim_at = now() + interval '1 second', updated_at = now()
WHERE status IN ('establishing','established') AND lease_expires_at < now()
`

func (q *Queries) RecoverExpiredConnectorControlTunnels(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverExpiredConnectorControlTunnels)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewConnectorInstallOperationLease = `-- name: RenewConnectorInstallOperationLease :execrows
UPDATE connector_install_operations SET lease_expires_at = now() + interval '90 seconds', updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND fence = $3 AND lease_owner = $4 AND status = 'running'
`

type RenewConnectorInstallOperationLeaseParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Fence        int64     `json:"fence"`
	LeaseOwner   string    `json:"lease_owner"`
}

func (q *Queries) RenewConnectorInstallOperationLease(ctx context.Context, arg RenewConnectorInstallOperationLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewConnectorInstallOperationLease,
		arg.ID,
		arg.EnterpriseID,
		arg.Fence,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueConnectorInstallOperation = `-- name: RequeueConnectorInstallOperation :one
UPDATE connector_install_operations SET
  status = 'queued', stage = 'queued', error_code = $4,
  lease_owner = '', lease_expires_at = NULL, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND fence = $3
  AND status = 'running' AND attempts < 3 AND expires_at > now()
RETURNING id, enterprise_id, connector_id, bastion_scope_id, host_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_mode, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at
`

type RequeueConnectorInstallOperationParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	Fence        int64       `json:"fence"`
	ErrorCode    pgtype.Text `json:"error_code"`
}

func (q *Queries) RequeueConnectorInstallOperation(ctx context.Context, arg RequeueConnectorInstallOperationParams) (ConnectorInstallOperation, error) {
	row := q.db.QueryRow(ctx, requeueConnectorInstallOperation,
		arg.ID,
		arg.EnterpriseID,
		arg.Fence,
		arg.ErrorCode,
	)
	var i ConnectorInstallOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.BastionScopeID,
		&i.HostID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMode,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeConnectorControlTunnelLeases = `-- name: RevokeConnectorControlTunnelLeases :execrows
UPDATE credential_leases AS lease SET status = 'revoked'
WHERE lease.enterprise_id = $2 AND lease.status = 'active'
  AND lease.operation_ref IN (
    SELECT 'connector_control_tunnel:' || tunnel.id::text
    FROM connector_control_tunnels AS tunnel
    WHERE tunnel.connector_id = $1 AND tunnel.enterprise_id = $2
  )
`

type RevokeConnectorControlTunnelLeasesParams struct {
	ConnectorID  uuid.UUID `json:"connector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) RevokeConnectorControlTunnelLeases(ctx context.Context, arg RevokeConnectorControlTunnelLeasesParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeConnectorControlTunnelLeases, arg.ConnectorID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeConnectorControlTunnelLeasesByScope = `-- name: RevokeConnectorControlTunnelLeasesByScope :execrows
UPDATE credential_leases AS lease SET status = 'revoked'
WHERE lease.enterprise_id = $2 AND lease.status = 'active'
  AND lease.operation_ref IN (
    SELECT 'connector_control_tunnel:' || tunnel.id::text
    FROM connector_control_tunnels AS tunnel
    WHERE tunnel.bastion_scope_id = $1 AND tunnel.enterprise_id = $2
  )
`

type RevokeConnectorControlTunnelLeasesByScopeParams struct {
	BastionScopeID uuid.UUID `json:"bastion_scope_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) RevokeConnectorControlTunnelLeasesByScope(ctx context.Context, arg RevokeConnectorControlTunnelLeasesByScopeParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeConnectorControlTunnelLeasesByScope, arg.BastionScopeID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
