// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyRecord = `-- name: CompleteIdempotencyRecord :execrows
UPDATE idempotency_records SET response_status = $5, response_nonce = $6, response_ciphertext = $7,
  response_provider = $8, response_key_id = $9, response_key_version = $10
WHERE audience = $1 AND subject_id = $2 AND operation = $3 AND idempotency_key = $4
  AND response_ciphertext IS NULL AND expires_at > now()
`

type CompleteIdempotencyRecordParams struct {
	Audience           string      `json:"audience"`
	SubjectID          string      `json:"subject_id"`
	Operation          string      `json:"operation"`
	IdempotencyKey     string      `json:"idempotency_key"`
	ResponseStatus     pgtype.Int4 `json:"response_status"`
	ResponseNonce      []byte      `json:"response_nonce"`
	ResponseCiphertext []byte      `json:"response_ciphertext"`
	ResponseProvider   pgtype.Text `json:"response_provider"`
	ResponseKeyID      pgtype.Text `json:"response_key_id"`
	ResponseKeyVersion pgtype.Int4 `json:"response_key_version"`
}

func (q *Queries) CompleteIdempotencyRecord(ctx context.Context, arg CompleteIdempotencyRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdempotencyRecord,
		arg.Audience,
		arg.SubjectID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseNonce,
		arg.ResponseCiphertext,
		arg.ResponseProvider,
		arg.ResponseKeyID,
		arg.ResponseKeyVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createIdempotencyRecord = `-- name: CreateIdempotencyRecord :execrows
INSERT INTO idempotency_records (audience, subject_id, operation, idempotency_key, request_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT DO NOTHING
`

type CreateIdempotencyRecordParams struct {
	Audience       string             `json:"audience"`
	SubjectID      string             `json:"subject_id"`
	Operation      string             `json:"operation"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    []byte             `json:"request_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, createIdempotencyRecord,
		arg.Audience,
		arg.SubjectID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEffectiveRoleBindings = `-- name: GetEffectiveRoleBindings :many
SELECT rb.id, rb.enterprise_id, rb.subject_type, rb.subject_id, rb.role_id, rb.valid_from, rb.valid_until, rb.status, rb.version, rb.created_at, rb.updated_at FROM role_bindings rb
WHERE rb.enterprise_id = $1 AND rb.status = 'active'
  AND (rb.valid_from IS NULL OR rb.valid_from <= now())
  AND (rb.valid_until IS NULL OR rb.valid_until > now())
  AND ((rb.subject_type = 'user' AND rb.subject_id = $2)
    OR (rb.subject_type = 'department' AND rb.subject_id = $3))
`

type GetEffectiveRoleBindingsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	UserID       uuid.UUID `json:"user_id"`
	DepartmentID uuid.UUID `json:"department_id"`
}

func (q *Queries) GetEffectiveRoleBindings(ctx context.Context, arg GetEffectiveRoleBindingsParams) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, getEffectiveRoleBindings, arg.EnterpriseID, arg.UserID, arg.DepartmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleBinding{}
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.SubjectType,
			&i.SubjectID,
			&i.RoleID,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT audience, subject_id, operation, idempotency_key, request_hash, response_status, response_nonce, response_ciphertext, expires_at, created_at, response_provider, response_key_id, response_key_version FROM idempotency_records
WHERE audience = $1 AND subject_id = $2 AND operation = $3 AND idempotency_key = $4
`

type GetIdempotencyRecordParams struct {
	Audience       string `json:"audience"`
	SubjectID      string `json:"subject_id"`
	Operation      string `json:"operation"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecord,
		arg.Audience,
		arg.SubjectID,
		arg.Operation,
		arg.IdempotencyKey,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.Audience,
		&i.SubjectID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseNonce,
		&i.ResponseCiphertext,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ResponseProvider,
		&i.ResponseKeyID,
		&i.ResponseKeyVersion,
	)
	return i, err
}
