// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRoleBindingDataScope(ctx context.Context, arg AddRoleBindingDataScopeParams) error
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	AddServiceAccountDataScope(ctx context.Context, arg AddServiceAccountDataScopeParams) error
	AdvanceAuditChain(ctx context.Context, arg AdvanceAuditChainParams) error
	BumpDepartmentUsersAuthorizationVersion(ctx context.Context, arg BumpDepartmentUsersAuthorizationVersionParams) ([]uuid.UUID, error)
	BumpEnterpriseServiceAccountsAuthorizationVersion(ctx context.Context, enterpriseID uuid.UUID) ([]uuid.UUID, error)
	BumpEnterpriseUsersAuthorizationVersion(ctx context.Context, enterpriseID uuid.UUID) ([]uuid.UUID, error)
	BumpUserAuthorizationVersion(ctx context.Context, arg BumpUserAuthorizationVersionParams) (int64, error)
	ChangeEnterpriseStatus(ctx context.Context, arg ChangeEnterpriseStatusParams) (Enterprise, error)
	ClaimOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	CompleteIdempotencyRecord(ctx context.Context, arg CompleteIdempotencyRecordParams) (int64, error)
	ConsumeTemporaryCredential(ctx context.Context, id uuid.UUID) (int64, error)
	CountDepartmentUsers(ctx context.Context, arg CountDepartmentUsersParams) (int64, error)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error)
	CreateDataScope(ctx context.Context, arg CreateDataScopeParams) (DataScope, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateEnterprise(ctx context.Context, arg CreateEnterpriseParams) (Enterprise, error)
	CreateEnterpriseUser(ctx context.Context, arg CreateEnterpriseUserParams) (EnterpriseUser, error)
	CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (int64, error)
	CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) (PasswordCredential, error)
	CreatePlatformSettings(ctx context.Context, arg CreatePlatformSettingsParams) (PlatformSetting, error)
	CreatePlatformUser(ctx context.Context, arg CreatePlatformUserParams) (PlatformUser, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateRoleBinding(ctx context.Context, arg CreateRoleBindingParams) (RoleBinding, error)
	CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (ServiceAccount, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTemporaryCredential(ctx context.Context, arg CreateTemporaryCredentialParams) (TemporaryCredential, error)
	DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error
	DisableEnterpriseUser(ctx context.Context, arg DisableEnterpriseUserParams) (EnterpriseUser, error)
	GetActiveTemporaryCredential(ctx context.Context, arg GetActiveTemporaryCredentialParams) (TemporaryCredential, error)
	GetApiKey(ctx context.Context, arg GetApiKeyParams) (ApiKey, error)
	GetApiKeyByPrefix(ctx context.Context, prefix string) (GetApiKeyByPrefixRow, error)
	GetBuiltinRole(ctx context.Context, arg GetBuiltinRoleParams) (Role, error)
	GetDataScope(ctx context.Context, arg GetDataScopeParams) (DataScope, error)
	GetDefaultDepartment(ctx context.Context, enterpriseID uuid.UUID) (Department, error)
	GetDepartment(ctx context.Context, arg GetDepartmentParams) (Department, error)
	GetEffectiveRoleBindings(ctx context.Context, arg GetEffectiveRoleBindingsParams) ([]RoleBinding, error)
	GetEnterprise(ctx context.Context, id uuid.UUID) (Enterprise, error)
	GetEnterpriseUser(ctx context.Context, arg GetEnterpriseUserParams) (EnterpriseUser, error)
	GetEnterpriseUserByID(ctx context.Context, id uuid.UUID) (EnterpriseUser, error)
	GetEnterpriseUserByUsername(ctx context.Context, lower string) (GetEnterpriseUserByUsernameRow, error)
	GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyRecord, error)
	GetPasswordCredential(ctx context.Context, arg GetPasswordCredentialParams) (PasswordCredential, error)
	GetPlatformSettings(ctx context.Context) (PlatformSetting, error)
	GetPlatformState(ctx context.Context) (GetPlatformStateRow, error)
	GetPlatformUser(ctx context.Context, id uuid.UUID) (PlatformUser, error)
	GetPlatformUserByUsername(ctx context.Context, lower string) (PlatformUser, error)
	GetRole(ctx context.Context, arg GetRoleParams) (Role, error)
	GetRoleBinding(ctx context.Context, arg GetRoleBindingParams) (RoleBinding, error)
	GetServiceAccount(ctx context.Context, arg GetServiceAccountParams) (ServiceAccount, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetTemporaryCredentialByChallenge(ctx context.Context, challengeHash []byte) (TemporaryCredential, error)
	InitializeAuditChain(ctx context.Context, arg InitializeAuditChainParams) error
	InitializeAuthorizationVersion(ctx context.Context, arg InitializeAuthorizationVersionParams) error
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	ListAllEnterpriseAuditEvents(ctx context.Context, enterpriseID uuid.NullUUID) ([]AuditEvent, error)
	ListAllEnterprises(ctx context.Context) ([]Enterprise, error)
	ListAllPlatformAuditEvents(ctx context.Context) ([]AuditEvent, error)
	ListApiKeys(ctx context.Context, arg ListApiKeysParams) ([]ApiKey, error)
	ListDataScopes(ctx context.Context, enterpriseID uuid.UUID) ([]DataScope, error)
	ListDepartments(ctx context.Context, enterpriseID uuid.UUID) ([]Department, error)
	ListEffectiveServiceAccountPermissions(ctx context.Context, arg ListEffectiveServiceAccountPermissionsParams) ([]string, error)
	ListEffectiveUserPermissions(ctx context.Context, arg ListEffectiveUserPermissionsParams) ([]string, error)
	ListEnterpriseAdmins(ctx context.Context, enterpriseID uuid.NullUUID) ([]EnterpriseUser, error)
	ListEnterpriseAuditEvents(ctx context.Context, arg ListEnterpriseAuditEventsParams) ([]AuditEvent, error)
	ListEnterpriseUsers(ctx context.Context, enterpriseID uuid.UUID) ([]EnterpriseUser, error)
	ListEnterprises(ctx context.Context, arg ListEnterprisesParams) ([]Enterprise, error)
	ListPermissions(ctx context.Context) ([]string, error)
	ListPlatformAuditEvents(ctx context.Context, limit int32) ([]AuditEvent, error)
	ListRoleBindingDataScopes(ctx context.Context, roleBindingID uuid.UUID) ([]uuid.UUID, error)
	ListRoleBindings(ctx context.Context, enterpriseID uuid.UUID) ([]RoleBinding, error)
	ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error)
	ListRoles(ctx context.Context, enterpriseID uuid.UUID) ([]Role, error)
	ListServiceAccountDataScopes(ctx context.Context, serviceAccountID uuid.UUID) ([]uuid.UUID, error)
	ListServiceAccounts(ctx context.Context, enterpriseID uuid.UUID) ([]ServiceAccount, error)
	LockAuditChain(ctx context.Context, chainKey string) (AuditChainHead, error)
	LockPlatformState(ctx context.Context) (LockPlatformStateRow, error)
	MarkApiKeyUsed(ctx context.Context, id uuid.UUID) error
	MarkEnterpriseLogin(ctx context.Context, id uuid.UUID) error
	MarkOutboxPublished(ctx context.Context, id uuid.UUID) error
	MarkPlatformInitialized(ctx context.Context) error
	MarkPlatformInitializing(ctx context.Context) (int64, error)
	MarkPlatformLogin(ctx context.Context, id uuid.UUID) error
	ReplaceRoleBindingDataScopes(ctx context.Context, roleBindingID uuid.UUID) error
	ReplaceServiceAccountDataScopes(ctx context.Context, serviceAccountID uuid.UUID) error
	RetryOutboxEvent(ctx context.Context, arg RetryOutboxEventParams) error
	RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (ApiKey, error)
	RevokeEnterpriseSessions(ctx context.Context, arg RevokeEnterpriseSessionsParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error)
	RevokeSubjectSessions(ctx context.Context, arg RevokeSubjectSessionsParams) error
	SetTemporaryCredentialChallenge(ctx context.Context, arg SetTemporaryCredentialChallengeParams) (TemporaryCredential, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) (Session, error)
	UpdateDataScope(ctx context.Context, arg UpdateDataScopeParams) (DataScope, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateEnterprise(ctx context.Context, arg UpdateEnterpriseParams) (Enterprise, error)
	UpdateEnterpriseUser(ctx context.Context, arg UpdateEnterpriseUserParams) (EnterpriseUser, error)
	UpdatePasswordCredential(ctx context.Context, arg UpdatePasswordCredentialParams) (PasswordCredential, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateRoleBinding(ctx context.Context, arg UpdateRoleBindingParams) (RoleBinding, error)
	UpdateServiceAccount(ctx context.Context, arg UpdateServiceAccountParams) (ServiceAccount, error)
	UpsertPermission(ctx context.Context, arg UpsertPermissionParams) error
}

var _ Querier = (*Queries)(nil)
