// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: remote_access_runtime.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceRemoteAccessRecording = `-- name: AdvanceRemoteAccessRecording :one
UPDATE remote_access_recordings SET chunk_count=$2,event_count=event_count+$3,size_bytes=size_bytes+$4,
    duration_ms=GREATEST(duration_ms,$5),final_hash=$6
WHERE id=$1 AND status='recording' AND chunk_count=$2-1 RETURNING id, enterprise_id, session_id, status, format, key_provider, key_id, key_version, wrapped_dek, chunk_count, event_count, size_bytes, duration_ms, final_hash, retention_until, created_at, completed_at
`

type AdvanceRemoteAccessRecordingParams struct {
	ID         uuid.UUID `json:"id"`
	ChunkCount int32     `json:"chunk_count"`
	EventCount int64     `json:"event_count"`
	SizeBytes  int64     `json:"size_bytes"`
	DurationMs int64     `json:"duration_ms"`
	FinalHash  []byte    `json:"final_hash"`
}

func (q *Queries) AdvanceRemoteAccessRecording(ctx context.Context, arg AdvanceRemoteAccessRecordingParams) (RemoteAccessRecording, error) {
	row := q.db.QueryRow(ctx, advanceRemoteAccessRecording,
		arg.ID,
		arg.ChunkCount,
		arg.EventCount,
		arg.SizeBytes,
		arg.DurationMs,
		arg.FinalHash,
	)
	var i RemoteAccessRecording
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.SessionID,
		&i.Status,
		&i.Format,
		&i.KeyProvider,
		&i.KeyID,
		&i.KeyVersion,
		&i.WrappedDek,
		&i.ChunkCount,
		&i.EventCount,
		&i.SizeBytes,
		&i.DurationMs,
		&i.FinalHash,
		&i.RetentionUntil,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const consumeRemoteAccessTicket = `-- name: ConsumeRemoteAccessTicket :one
UPDATE remote_access_tickets ticket SET consumed_at=now()
WHERE ticket_hash=$1 AND consumed_at IS NULL AND expires_at>$2 AND session_id=$3 AND http_session_id=$4 AND enterprise_id=$5
  AND user_id=$6 AND host_id=$7 AND managed_account_id=$8 AND protocol=$9 AND lease_id=$10
  AND authorization_version=$11 AND session_fence=$12
RETURNING id, session_id, ticket_hash, http_session_id, enterprise_id, user_id, host_id, managed_account_id, protocol, lease_id, authorization_version, session_fence, expires_at, consumed_at, created_at
`

type ConsumeRemoteAccessTicketParams struct {
	TicketHash           []byte             `json:"ticket_hash"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	SessionID            uuid.UUID          `json:"session_id"`
	HttpSessionID        uuid.UUID          `json:"http_session_id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	UserID               uuid.UUID          `json:"user_id"`
	HostID               uuid.UUID          `json:"host_id"`
	ManagedAccountID     uuid.UUID          `json:"managed_account_id"`
	Protocol             string             `json:"protocol"`
	LeaseID              uuid.UUID          `json:"lease_id"`
	AuthorizationVersion int64              `json:"authorization_version"`
	SessionFence         int64              `json:"session_fence"`
}

func (q *Queries) ConsumeRemoteAccessTicket(ctx context.Context, arg ConsumeRemoteAccessTicketParams) (RemoteAccessTicket, error) {
	row := q.db.QueryRow(ctx, consumeRemoteAccessTicket,
		arg.TicketHash,
		arg.ExpiresAt,
		arg.SessionID,
		arg.HttpSessionID,
		arg.EnterpriseID,
		arg.UserID,
		arg.HostID,
		arg.ManagedAccountID,
		arg.Protocol,
		arg.LeaseID,
		arg.AuthorizationVersion,
		arg.SessionFence,
	)
	var i RemoteAccessTicket
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TicketHash,
		&i.HttpSessionID,
		&i.EnterpriseID,
		&i.UserID,
		&i.HostID,
		&i.ManagedAccountID,
		&i.Protocol,
		&i.LeaseID,
		&i.AuthorizationVersion,
		&i.SessionFence,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeRemoteAccessTicketForGateway = `-- name: ConsumeRemoteAccessTicketForGateway :one
UPDATE remote_access_tickets ticket SET consumed_at=now()
FROM remote_access_sessions session, remote_access_leases lease, remote_access_grants access_grant,
     enterprise_users actor, enterprises enterprise
WHERE ticket.ticket_hash=$1 AND ticket.session_id=$2
  AND ticket.consumed_at IS NULL AND ticket.expires_at>$3
  AND session.id=ticket.session_id AND session.status='authorized' AND session.connect_before>$3
  AND session.session_fence=ticket.session_fence AND session.authorization_version=ticket.authorization_version
  AND lease.id=session.lease_id AND lease.revoked_at IS NULL AND lease.expires_at>$3
  AND access_grant.id=lease.grant_id AND access_grant.enabled=true AND access_grant.valid_until>$3
  AND actor.id=ticket.user_id AND actor.enterprise_id=ticket.enterprise_id AND actor.status='active'
  AND actor.authorization_version=ticket.authorization_version
  AND enterprise.id=ticket.enterprise_id AND enterprise.status='active'
RETURNING ticket.id, ticket.session_id, ticket.ticket_hash, ticket.http_session_id, ticket.enterprise_id, ticket.user_id, ticket.host_id, ticket.managed_account_id, ticket.protocol, ticket.lease_id, ticket.authorization_version, ticket.session_fence, ticket.expires_at, ticket.consumed_at, ticket.created_at
`

type ConsumeRemoteAccessTicketForGatewayParams struct {
	TicketHash []byte             `json:"ticket_hash"`
	SessionID  uuid.UUID          `json:"session_id"`
	Now        pgtype.Timestamptz `json:"now"`
}

func (q *Queries) ConsumeRemoteAccessTicketForGateway(ctx context.Context, arg ConsumeRemoteAccessTicketForGatewayParams) (RemoteAccessTicket, error) {
	row := q.db.QueryRow(ctx, consumeRemoteAccessTicketForGateway, arg.TicketHash, arg.SessionID, arg.Now)
	var i RemoteAccessTicket
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TicketHash,
		&i.HttpSessionID,
		&i.EnterpriseID,
		&i.UserID,
		&i.HostID,
		&i.ManagedAccountID,
		&i.Protocol,
		&i.LeaseID,
		&i.AuthorizationVersion,
		&i.SessionFence,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRemoteAccessCommandEvent = `-- name: CreateRemoteAccessCommandEvent :one
INSERT INTO remote_access_command_events (id,session_id,sequence,event_type,command_hash,occurred_at)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, session_id, sequence, event_type, command_hash, occurred_at
`

type CreateRemoteAccessCommandEventParams struct {
	ID          uuid.UUID          `json:"id"`
	SessionID   uuid.UUID          `json:"session_id"`
	Sequence    int64              `json:"sequence"`
	EventType   string             `json:"event_type"`
	CommandHash []byte             `json:"command_hash"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateRemoteAccessCommandEvent(ctx context.Context, arg CreateRemoteAccessCommandEventParams) (RemoteAccessCommandEvent, error) {
	row := q.db.QueryRow(ctx, createRemoteAccessCommandEvent,
		arg.ID,
		arg.SessionID,
		arg.Sequence,
		arg.EventType,
		arg.CommandHash,
		arg.OccurredAt,
	)
	var i RemoteAccessCommandEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Sequence,
		&i.EventType,
		&i.CommandHash,
		&i.OccurredAt,
	)
	return i, err
}

const createRemoteAccessRecording = `-- name: CreateRemoteAccessRecording :one
INSERT INTO remote_access_recordings (id,enterprise_id,session_id,key_provider,key_id,key_version,wrapped_dek)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, enterprise_id, session_id, status, format, key_provider, key_id, key_version, wrapped_dek, chunk_count, event_count, size_bytes, duration_ms, final_hash, retention_until, created_at, completed_at
`

type CreateRemoteAccessRecordingParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	SessionID    uuid.UUID `json:"session_id"`
	KeyProvider  string    `json:"key_provider"`
	KeyID        string    `json:"key_id"`
	KeyVersion   int32     `json:"key_version"`
	WrappedDek   []byte    `json:"wrapped_dek"`
}

func (q *Queries) CreateRemoteAccessRecording(ctx context.Context, arg CreateRemoteAccessRecordingParams) (RemoteAccessRecording, error) {
	row := q.db.QueryRow(ctx, createRemoteAccessRecording,
		arg.ID,
		arg.EnterpriseID,
		arg.SessionID,
		arg.KeyProvider,
		arg.KeyID,
		arg.KeyVersion,
		arg.WrappedDek,
	)
	var i RemoteAccessRecording
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.SessionID,
		&i.Status,
		&i.Format,
		&i.KeyProvider,
		&i.KeyID,
		&i.KeyVersion,
		&i.WrappedDek,
		&i.ChunkCount,
		&i.EventCount,
		&i.SizeBytes,
		&i.DurationMs,
		&i.FinalHash,
		&i.RetentionUntil,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createRemoteAccessRecordingChunk = `-- name: CreateRemoteAccessRecordingChunk :one
INSERT INTO remote_access_recording_chunks (recording_id,sequence,object_key,nonce,ciphertext_size,event_count,started_at,ended_at,previous_hash,chunk_hash)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING recording_id, sequence, object_key, nonce, ciphertext_size, event_count, started_at, ended_at, previous_hash, chunk_hash, created_at
`

type CreateRemoteAccessRecordingChunkParams struct {
	RecordingID    uuid.UUID          `json:"recording_id"`
	Sequence       int64              `json:"sequence"`
	ObjectKey      string             `json:"object_key"`
	Nonce          []byte             `json:"nonce"`
	CiphertextSize int64              `json:"ciphertext_size"`
	EventCount     int32              `json:"event_count"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	PreviousHash   []byte             `json:"previous_hash"`
	ChunkHash      []byte             `json:"chunk_hash"`
}

func (q *Queries) CreateRemoteAccessRecordingChunk(ctx context.Context, arg CreateRemoteAccessRecordingChunkParams) (RemoteAccessRecordingChunk, error) {
	row := q.db.QueryRow(ctx, createRemoteAccessRecordingChunk,
		arg.RecordingID,
		arg.Sequence,
		arg.ObjectKey,
		arg.Nonce,
		arg.CiphertextSize,
		arg.EventCount,
		arg.StartedAt,
		arg.EndedAt,
		arg.PreviousHash,
		arg.ChunkHash,
	)
	var i RemoteAccessRecordingChunk
	err := row.Scan(
		&i.RecordingID,
		&i.Sequence,
		&i.ObjectKey,
		&i.Nonce,
		&i.CiphertextSize,
		&i.EventCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.PreviousHash,
		&i.ChunkHash,
		&i.CreatedAt,
	)
	return i, err
}

const createRemoteAccessSession = `-- name: CreateRemoteAccessSession :one
INSERT INTO remote_access_sessions (id,enterprise_id,user_id,http_session_id,lease_id,host_id,managed_account_id,protocol,
    connection_mode,connector_id,status,authorization_version,idle_timeout_seconds,max_duration_seconds,connect_before)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'authorized',$11,$12,$13,$14) RETURNING id, enterprise_id, user_id, http_session_id, lease_id, host_id, managed_account_id, protocol, connection_mode, connector_id, connector_epoch, status, session_fence, authorization_version, idle_timeout_seconds, max_duration_seconds, connect_before, connected_at, terminated_at, termination_reason, created_at, updated_at
`

type CreateRemoteAccessSessionParams struct {
	ID                   uuid.UUID          `json:"id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	UserID               uuid.UUID          `json:"user_id"`
	HttpSessionID        uuid.UUID          `json:"http_session_id"`
	LeaseID              uuid.UUID          `json:"lease_id"`
	HostID               uuid.UUID          `json:"host_id"`
	ManagedAccountID     uuid.UUID          `json:"managed_account_id"`
	Protocol             string             `json:"protocol"`
	ConnectionMode       string             `json:"connection_mode"`
	ConnectorID          uuid.NullUUID      `json:"connector_id"`
	AuthorizationVersion int64              `json:"authorization_version"`
	IdleTimeoutSeconds   int32              `json:"idle_timeout_seconds"`
	MaxDurationSeconds   int32              `json:"max_duration_seconds"`
	ConnectBefore        pgtype.Timestamptz `json:"connect_before"`
}

func (q *Queries) CreateRemoteAccessSession(ctx context.Context, arg CreateRemoteAccessSessionParams) (RemoteAccessSession, error) {
	row := q.db.QueryRow(ctx, createRemoteAccessSession,
		arg.ID,
		arg.EnterpriseID,
		arg.UserID,
		arg.HttpSessionID,
		arg.LeaseID,
		arg.HostID,
		arg.ManagedAccountID,
		arg.Protocol,
		arg.ConnectionMode,
		arg.ConnectorID,
		arg.AuthorizationVersion,
		arg.IdleTimeoutSeconds,
		arg.MaxDurationSeconds,
		arg.ConnectBefore,
	)
	var i RemoteAccessSession
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.UserID,
		&i.HttpSessionID,
		&i.LeaseID,
		&i.HostID,
		&i.ManagedAccountID,
		&i.Protocol,
		&i.ConnectionMode,
		&i.ConnectorID,
		&i.ConnectorEpoch,
		&i.Status,
		&i.SessionFence,
		&i.AuthorizationVersion,
		&i.IdleTimeoutSeconds,
		&i.MaxDurationSeconds,
		&i.ConnectBefore,
		&i.ConnectedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRemoteAccessTicket = `-- name: CreateRemoteAccessTicket :one
INSERT INTO remote_access_tickets (id,session_id,ticket_hash,http_session_id,enterprise_id,user_id,host_id,managed_account_id,
    protocol,lease_id,authorization_version,session_fence,expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id, session_id, ticket_hash, http_session_id, enterprise_id, user_id, host_id, managed_account_id, protocol, lease_id, authorization_version, session_fence, expires_at, consumed_at, created_at
`

type CreateRemoteAccessTicketParams struct {
	ID                   uuid.UUID          `json:"id"`
	SessionID            uuid.UUID          `json:"session_id"`
	TicketHash           []byte             `json:"ticket_hash"`
	HttpSessionID        uuid.UUID          `json:"http_session_id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	UserID               uuid.UUID          `json:"user_id"`
	HostID               uuid.UUID          `json:"host_id"`
	ManagedAccountID     uuid.UUID          `json:"managed_account_id"`
	Protocol             string             `json:"protocol"`
	LeaseID              uuid.UUID          `json:"lease_id"`
	AuthorizationVersion int64              `json:"authorization_version"`
	SessionFence         int64              `json:"session_fence"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRemoteAccessTicket(ctx context.Context, arg CreateRemoteAccessTicketParams) (RemoteAccessTicket, error) {
	row := q.db.QueryRow(ctx, createRemoteAccessTicket,
		arg.ID,
		arg.SessionID,
		arg.TicketHash,
		arg.HttpSessionID,
		arg.EnterpriseID,
		arg.UserID,
		arg.HostID,
		arg.ManagedAccountID,
		arg.Protocol,
		arg.LeaseID,
		arg.AuthorizationVersion,
		arg.SessionFence,
		arg.ExpiresAt,
	)
	var i RemoteAccessTicket
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TicketHash,
		&i.HttpSessionID,
		&i.EnterpriseID,
		&i.UserID,
		&i.HostID,
		&i.ManagedAccountID,
		&i.Protocol,
		&i.LeaseID,
		&i.AuthorizationVersion,
		&i.SessionFence,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRemoteAccessRoute = `-- name: DeleteRemoteAccessRoute :execrows
DELETE FROM remote_access_routes WHERE session_id=$1 AND session_fence=$2
`

type DeleteRemoteAccessRouteParams struct {
	SessionID    uuid.UUID `json:"session_id"`
	SessionFence int64     `json:"session_fence"`
}

func (q *Queries) DeleteRemoteAccessRoute(ctx context.Context, arg DeleteRemoteAccessRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRemoteAccessRoute, arg.SessionID, arg.SessionFence)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishRemoteAccessRecording = `-- name: FinishRemoteAccessRecording :one
UPDATE remote_access_recordings SET status=$2,completed_at=now()
WHERE id=$1 AND status='recording' RETURNING id, enterprise_id, session_id, status, format, key_provider, key_id, key_version, wrapped_dek, chunk_count, event_count, size_bytes, duration_ms, final_hash, retention_until, created_at, completed_at
`

type FinishRemoteAccessRecordingParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) FinishRemoteAccessRecording(ctx context.Context, arg FinishRemoteAccessRecordingParams) (RemoteAccessRecording, error) {
	row := q.db.QueryRow(ctx, finishRemoteAccessRecording, arg.ID, arg.Status)
	var i RemoteAccessRecording
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.SessionID,
		&i.Status,
		&i.Format,
		&i.KeyProvider,
		&i.KeyID,
		&i.KeyVersion,
		&i.WrappedDek,
		&i.ChunkCount,
		&i.EventCount,
		&i.SizeBytes,
		&i.DurationMs,
		&i.FinalHash,
		&i.RetentionUntil,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const finishRemoteAccessSession = `-- name: FinishRemoteAccessSession :one
UPDATE remote_access_sessions SET status=$3,termination_reason=$4,terminated_at=now(),updated_at=now()
WHERE id=$1 AND session_fence=$2 AND status IN ('authorized','connecting','active','terminating') RETURNING id, enterprise_id, user_id, http_session_id, lease_id, host_id, managed_account_id, protocol, connection_mode, connector_id, connector_epoch, status, session_fence, authorization_version, idle_timeout_seconds, max_duration_seconds, connect_before, connected_at, terminated_at, termination_reason, created_at, updated_at
`

type FinishRemoteAccessSessionParams struct {
	ID                uuid.UUID   `json:"id"`
	SessionFence      int64       `json:"session_fence"`
	Status            string      `json:"status"`
	TerminationReason pgtype.Text `json:"termination_reason"`
}

func (q *Queries) FinishRemoteAccessSession(ctx context.Context, arg FinishRemoteAccessSessionParams) (RemoteAccessSession, error) {
	row := q.db.QueryRow(ctx, finishRemoteAccessSession,
		arg.ID,
		arg.SessionFence,
		arg.Status,
		arg.TerminationReason,
	)
	var i RemoteAccessSession
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.UserID,
		&i.HttpSessionID,
		&i.LeaseID,
		&i.HostID,
		&i.ManagedAccountID,
		&i.Protocol,
		&i.ConnectionMode,
		&i.ConnectorID,
		&i.ConnectorEpoch,
		&i.Status,
		&i.SessionFence,
		&i.AuthorizationVersion,
		&i.IdleTimeoutSeconds,
		&i.MaxDurationSeconds,
		&i.ConnectBefore,
		&i.ConnectedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentRemoteAccessAuthorizationVersion = `-- name: GetCurrentRemoteAccessAuthorizationVersion :one
SELECT actor.authorization_version FROM enterprise_users actor
JOIN enterprises enterprise ON enterprise.id=actor.enterprise_id AND enterprise.status='active'
WHERE actor.id=$1 AND actor.enterprise_id=$2 AND actor.status='active'
`

type GetCurrentRemoteAccessAuthorizationVersionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetCurrentRemoteAccessAuthorizationVersion(ctx context.Context, arg GetCurrentRemoteAccessAuthorizationVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCurrentRemoteAccessAuthorizationVersion, arg.UserID, arg.EnterpriseID)
	var authorization_version int64
	err := row.Scan(&authorization_version)
	return authorization_version, err
}

const getRemoteAccessRecording = `-- name: GetRemoteAccessRecording :one
SELECT id, enterprise_id, session_id, status, format, key_provider, key_id, key_version, wrapped_dek, chunk_count, event_count, size_bytes, duration_ms, final_hash, retention_until, created_at, completed_at FROM remote_access_recordings WHERE id=$1 AND enterprise_id=$2 AND retention_until>now()
`

type GetRemoteAccessRecordingParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetRemoteAccessRecording(ctx context.Context, arg GetRemoteAccessRecordingParams) (RemoteAccessRecording, error) {
	row := q.db.QueryRow(ctx, getRemoteAccessRecording, arg.ID, arg.EnterpriseID)
	var i RemoteAccessRecording
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.SessionID,
		&i.Status,
		&i.Format,
		&i.KeyProvider,
		&i.KeyID,
		&i.KeyVersion,
		&i.WrappedDek,
		&i.ChunkCount,
		&i.EventCount,
		&i.SizeBytes,
		&i.DurationMs,
		&i.FinalHash,
		&i.RetentionUntil,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRemoteAccessRecordingBySession = `-- name: GetRemoteAccessRecordingBySession :one
SELECT id, enterprise_id, session_id, status, format, key_provider, key_id, key_version, wrapped_dek, chunk_count, event_count, size_bytes, duration_ms, final_hash, retention_until, created_at, completed_at FROM remote_access_recordings WHERE session_id=$1 AND enterprise_id=$2 AND retention_until>now()
`

type GetRemoteAccessRecordingBySessionParams struct {
	SessionID    uuid.UUID `json:"session_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetRemoteAccessRecordingBySession(ctx context.Context, arg GetRemoteAccessRecordingBySessionParams) (RemoteAccessRecording, error) {
	row := q.db.QueryRow(ctx, getRemoteAccessRecordingBySession, arg.SessionID, arg.EnterpriseID)
	var i RemoteAccessRecording
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.SessionID,
		&i.Status,
		&i.Format,
		&i.KeyProvider,
		&i.KeyID,
		&i.KeyVersion,
		&i.WrappedDek,
		&i.ChunkCount,
		&i.EventCount,
		&i.SizeBytes,
		&i.DurationMs,
		&i.FinalHash,
		&i.RetentionUntil,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRemoteAccessRecordingForGateway = `-- name: GetRemoteAccessRecordingForGateway :one
SELECT id, enterprise_id, session_id, status, format, key_provider, key_id, key_version, wrapped_dek, chunk_count, event_count, size_bytes, duration_ms, final_hash, retention_until, created_at, completed_at FROM remote_access_recordings WHERE session_id=$1 AND status='recording' FOR UPDATE
`

func (q *Queries) GetRemoteAccessRecordingForGateway(ctx context.Context, sessionID uuid.UUID) (RemoteAccessRecording, error) {
	row := q.db.QueryRow(ctx, getRemoteAccessRecordingForGateway, sessionID)
	var i RemoteAccessRecording
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.SessionID,
		&i.Status,
		&i.Format,
		&i.KeyProvider,
		&i.KeyID,
		&i.KeyVersion,
		&i.WrappedDek,
		&i.ChunkCount,
		&i.EventCount,
		&i.SizeBytes,
		&i.DurationMs,
		&i.FinalHash,
		&i.RetentionUntil,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRemoteAccessRoute = `-- name: GetRemoteAccessRoute :one
SELECT session_id, gateway_instance, connector_id, connector_epoch, session_fence, lease_expires_at, updated_at FROM remote_access_routes WHERE session_id=$1 AND lease_expires_at>now()
`

func (q *Queries) GetRemoteAccessRoute(ctx context.Context, sessionID uuid.UUID) (RemoteAccessRoute, error) {
	row := q.db.QueryRow(ctx, getRemoteAccessRoute, sessionID)
	var i RemoteAccessRoute
	err := row.Scan(
		&i.SessionID,
		&i.GatewayInstance,
		&i.ConnectorID,
		&i.ConnectorEpoch,
		&i.SessionFence,
		&i.LeaseExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRemoteAccessSession = `-- name: GetRemoteAccessSession :one
SELECT id, enterprise_id, user_id, http_session_id, lease_id, host_id, managed_account_id, protocol, connection_mode, connector_id, connector_epoch, status, session_fence, authorization_version, idle_timeout_seconds, max_duration_seconds, connect_before, connected_at, terminated_at, termination_reason, created_at, updated_at FROM remote_access_sessions WHERE id=$1 AND enterprise_id=$2
`

type GetRemoteAccessSessionParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetRemoteAccessSession(ctx context.Context, arg GetRemoteAccessSessionParams) (RemoteAccessSession, error) {
	row := q.db.QueryRow(ctx, getRemoteAccessSession, arg.ID, arg.EnterpriseID)
	var i RemoteAccessSession
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.UserID,
		&i.HttpSessionID,
		&i.LeaseID,
		&i.HostID,
		&i.ManagedAccountID,
		&i.Protocol,
		&i.ConnectionMode,
		&i.ConnectorID,
		&i.ConnectorEpoch,
		&i.Status,
		&i.SessionFence,
		&i.AuthorizationVersion,
		&i.IdleTimeoutSeconds,
		&i.MaxDurationSeconds,
		&i.ConnectBefore,
		&i.ConnectedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRemoteAccessSessionTarget = `-- name: GetRemoteAccessSessionTarget :one
SELECT session.id, session.enterprise_id, session.user_id, session.http_session_id, session.lease_id, session.host_id, session.managed_account_id, session.protocol, session.connection_mode, session.connector_id, session.connector_epoch, session.status, session.session_fence, session.authorization_version, session.idle_timeout_seconds, session.max_duration_seconds, session.connect_before, session.connected_at, session.terminated_at, session.termination_reason, session.created_at, session.updated_at, host.address,host.hostname,host.port,host.pinned_host_key,account.username,account.credential_id,
       connector.connection_epoch,lease.expires_at AS lease_expires_at
FROM remote_access_sessions session
JOIN remote_access_leases lease ON lease.id=session.lease_id AND lease.enterprise_id=session.enterprise_id
JOIN hosts host ON host.id=session.host_id AND host.enterprise_id=session.enterprise_id AND host.status='active'
JOIN managed_accounts account ON account.id=session.managed_account_id AND account.enterprise_id=session.enterprise_id AND account.status='active'
LEFT JOIN connectors connector ON connector.id=session.connector_id AND connector.enterprise_id=session.enterprise_id AND connector.status='online'
WHERE session.id=$1
`

type GetRemoteAccessSessionTargetRow struct {
	ID                   uuid.UUID          `json:"id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	UserID               uuid.UUID          `json:"user_id"`
	HttpSessionID        uuid.UUID          `json:"http_session_id"`
	LeaseID              uuid.UUID          `json:"lease_id"`
	HostID               uuid.UUID          `json:"host_id"`
	ManagedAccountID     uuid.UUID          `json:"managed_account_id"`
	Protocol             string             `json:"protocol"`
	ConnectionMode       string             `json:"connection_mode"`
	ConnectorID          uuid.NullUUID      `json:"connector_id"`
	ConnectorEpoch       pgtype.Int8        `json:"connector_epoch"`
	Status               string             `json:"status"`
	SessionFence         int64              `json:"session_fence"`
	AuthorizationVersion int64              `json:"authorization_version"`
	IdleTimeoutSeconds   int32              `json:"idle_timeout_seconds"`
	MaxDurationSeconds   int32              `json:"max_duration_seconds"`
	ConnectBefore        pgtype.Timestamptz `json:"connect_before"`
	ConnectedAt          pgtype.Timestamptz `json:"connected_at"`
	TerminatedAt         pgtype.Timestamptz `json:"terminated_at"`
	TerminationReason    pgtype.Text        `json:"termination_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Address              string             `json:"address"`
	Hostname             string             `json:"hostname"`
	Port                 int32              `json:"port"`
	PinnedHostKey        string             `json:"pinned_host_key"`
	Username             string             `json:"username"`
	CredentialID         uuid.UUID          `json:"credential_id"`
	ConnectionEpoch      pgtype.Int8        `json:"connection_epoch"`
	LeaseExpiresAt       pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) GetRemoteAccessSessionTarget(ctx context.Context, id uuid.UUID) (GetRemoteAccessSessionTargetRow, error) {
	row := q.db.QueryRow(ctx, getRemoteAccessSessionTarget, id)
	var i GetRemoteAccessSessionTargetRow
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.UserID,
		&i.HttpSessionID,
		&i.LeaseID,
		&i.HostID,
		&i.ManagedAccountID,
		&i.Protocol,
		&i.ConnectionMode,
		&i.ConnectorID,
		&i.ConnectorEpoch,
		&i.Status,
		&i.SessionFence,
		&i.AuthorizationVersion,
		&i.IdleTimeoutSeconds,
		&i.MaxDurationSeconds,
		&i.ConnectBefore,
		&i.ConnectedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Address,
		&i.Hostname,
		&i.Port,
		&i.PinnedHostKey,
		&i.Username,
		&i.CredentialID,
		&i.ConnectionEpoch,
		&i.LeaseExpiresAt,
	)
	return i, err
}

const listRemoteAccessRecordingChunks = `-- name: ListRemoteAccessRecordingChunks :many
SELECT recording_id, sequence, object_key, nonce, ciphertext_size, event_count, started_at, ended_at, previous_hash, chunk_hash, created_at FROM remote_access_recording_chunks WHERE recording_id=$1 AND sequence>$2 ORDER BY sequence LIMIT $3
`

type ListRemoteAccessRecordingChunksParams struct {
	RecordingID uuid.UUID `json:"recording_id"`
	Sequence    int64     `json:"sequence"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) ListRemoteAccessRecordingChunks(ctx context.Context, arg ListRemoteAccessRecordingChunksParams) ([]RemoteAccessRecordingChunk, error) {
	rows, err := q.db.Query(ctx, listRemoteAccessRecordingChunks, arg.RecordingID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RemoteAccessRecordingChunk{}
	for rows.Next() {
		var i RemoteAccessRecordingChunk
		if err := rows.Scan(
			&i.RecordingID,
			&i.Sequence,
			&i.ObjectKey,
			&i.Nonce,
			&i.CiphertextSize,
			&i.EventCount,
			&i.StartedAt,
			&i.EndedAt,
			&i.PreviousHash,
			&i.ChunkHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemoteAccessSessions = `-- name: ListRemoteAccessSessions :many
SELECT id, enterprise_id, user_id, http_session_id, lease_id, host_id, managed_account_id, protocol, connection_mode, connector_id, connector_epoch, status, session_fence, authorization_version, idle_timeout_seconds, max_duration_seconds, connect_before, connected_at, terminated_at, termination_reason, created_at, updated_at FROM remote_access_sessions WHERE enterprise_id=$1 AND (user_id=$2 OR $3::boolean) ORDER BY created_at DESC,id DESC LIMIT $4
`

type ListRemoteAccessSessionsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	UserID       uuid.UUID `json:"user_id"`
	Column3      bool      `json:"column_3"`
	Limit        int32     `json:"limit"`
}

func (q *Queries) ListRemoteAccessSessions(ctx context.Context, arg ListRemoteAccessSessionsParams) ([]RemoteAccessSession, error) {
	rows, err := q.db.Query(ctx, listRemoteAccessSessions,
		arg.EnterpriseID,
		arg.UserID,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RemoteAccessSession{}
	for rows.Next() {
		var i RemoteAccessSession
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.UserID,
			&i.HttpSessionID,
			&i.LeaseID,
			&i.HostID,
			&i.ManagedAccountID,
			&i.Protocol,
			&i.ConnectionMode,
			&i.ConnectorID,
			&i.ConnectorEpoch,
			&i.Status,
			&i.SessionFence,
			&i.AuthorizationVersion,
			&i.IdleTimeoutSeconds,
			&i.MaxDurationSeconds,
			&i.ConnectBefore,
			&i.ConnectedAt,
			&i.TerminatedAt,
			&i.TerminationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRemoteAccessSessionActive = `-- name: MarkRemoteAccessSessionActive :one
UPDATE remote_access_sessions SET status='active',connected_at=COALESCE(connected_at,now()),updated_at=now()
WHERE id=$1 AND session_fence=$2 AND status='connecting' RETURNING id, enterprise_id, user_id, http_session_id, lease_id, host_id, managed_account_id, protocol, connection_mode, connector_id, connector_epoch, status, session_fence, authorization_version, idle_timeout_seconds, max_duration_seconds, connect_before, connected_at, terminated_at, termination_reason, created_at, updated_at
`

type MarkRemoteAccessSessionActiveParams struct {
	ID           uuid.UUID `json:"id"`
	SessionFence int64     `json:"session_fence"`
}

func (q *Queries) MarkRemoteAccessSessionActive(ctx context.Context, arg MarkRemoteAccessSessionActiveParams) (RemoteAccessSession, error) {
	row := q.db.QueryRow(ctx, markRemoteAccessSessionActive, arg.ID, arg.SessionFence)
	var i RemoteAccessSession
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.UserID,
		&i.HttpSessionID,
		&i.LeaseID,
		&i.HostID,
		&i.ManagedAccountID,
		&i.Protocol,
		&i.ConnectionMode,
		&i.ConnectorID,
		&i.ConnectorEpoch,
		&i.Status,
		&i.SessionFence,
		&i.AuthorizationVersion,
		&i.IdleTimeoutSeconds,
		&i.MaxDurationSeconds,
		&i.ConnectBefore,
		&i.ConnectedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRemoteAccessSessionConnecting = `-- name: MarkRemoteAccessSessionConnecting :one
UPDATE remote_access_sessions SET status='connecting',updated_at=now()
WHERE id=$1 AND session_fence=$2 AND status='authorized' RETURNING id, enterprise_id, user_id, http_session_id, lease_id, host_id, managed_account_id, protocol, connection_mode, connector_id, connector_epoch, status, session_fence, authorization_version, idle_timeout_seconds, max_duration_seconds, connect_before, connected_at, terminated_at, termination_reason, created_at, updated_at
`

type MarkRemoteAccessSessionConnectingParams struct {
	ID           uuid.UUID `json:"id"`
	SessionFence int64     `json:"session_fence"`
}

func (q *Queries) MarkRemoteAccessSessionConnecting(ctx context.Context, arg MarkRemoteAccessSessionConnectingParams) (RemoteAccessSession, error) {
	row := q.db.QueryRow(ctx, markRemoteAccessSessionConnecting, arg.ID, arg.SessionFence)
	var i RemoteAccessSession
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.UserID,
		&i.HttpSessionID,
		&i.LeaseID,
		&i.HostID,
		&i.ManagedAccountID,
		&i.Protocol,
		&i.ConnectionMode,
		&i.ConnectorID,
		&i.ConnectorEpoch,
		&i.Status,
		&i.SessionFence,
		&i.AuthorizationVersion,
		&i.IdleTimeoutSeconds,
		&i.MaxDurationSeconds,
		&i.ConnectBefore,
		&i.ConnectedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const terminateRemoteAccessSession = `-- name: TerminateRemoteAccessSession :one
UPDATE remote_access_sessions SET status='terminating',session_fence=session_fence+1,termination_reason=$3,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status IN ('authorized','connecting','active') RETURNING id, enterprise_id, user_id, http_session_id, lease_id, host_id, managed_account_id, protocol, connection_mode, connector_id, connector_epoch, status, session_fence, authorization_version, idle_timeout_seconds, max_duration_seconds, connect_before, connected_at, terminated_at, termination_reason, created_at, updated_at
`

type TerminateRemoteAccessSessionParams struct {
	ID                uuid.UUID   `json:"id"`
	EnterpriseID      uuid.UUID   `json:"enterprise_id"`
	TerminationReason pgtype.Text `json:"termination_reason"`
}

func (q *Queries) TerminateRemoteAccessSession(ctx context.Context, arg TerminateRemoteAccessSessionParams) (RemoteAccessSession, error) {
	row := q.db.QueryRow(ctx, terminateRemoteAccessSession, arg.ID, arg.EnterpriseID, arg.TerminationReason)
	var i RemoteAccessSession
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.UserID,
		&i.HttpSessionID,
		&i.LeaseID,
		&i.HostID,
		&i.ManagedAccountID,
		&i.Protocol,
		&i.ConnectionMode,
		&i.ConnectorID,
		&i.ConnectorEpoch,
		&i.Status,
		&i.SessionFence,
		&i.AuthorizationVersion,
		&i.IdleTimeoutSeconds,
		&i.MaxDurationSeconds,
		&i.ConnectBefore,
		&i.ConnectedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const terminateRemoteAccessSessionsByEnterprise = `-- name: TerminateRemoteAccessSessionsByEnterprise :many
UPDATE remote_access_sessions SET status='terminating',session_fence=session_fence+1,termination_reason=$1,updated_at=now()
WHERE enterprise_id=$2 AND status IN ('authorized','connecting','active') RETURNING id, enterprise_id, user_id, http_session_id, lease_id, host_id, managed_account_id, protocol, connection_mode, connector_id, connector_epoch, status, session_fence, authorization_version, idle_timeout_seconds, max_duration_seconds, connect_before, connected_at, terminated_at, termination_reason, created_at, updated_at
`

type TerminateRemoteAccessSessionsByEnterpriseParams struct {
	Reason       pgtype.Text `json:"reason"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
}

func (q *Queries) TerminateRemoteAccessSessionsByEnterprise(ctx context.Context, arg TerminateRemoteAccessSessionsByEnterpriseParams) ([]RemoteAccessSession, error) {
	rows, err := q.db.Query(ctx, terminateRemoteAccessSessionsByEnterprise, arg.Reason, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RemoteAccessSession{}
	for rows.Next() {
		var i RemoteAccessSession
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.UserID,
			&i.HttpSessionID,
			&i.LeaseID,
			&i.HostID,
			&i.ManagedAccountID,
			&i.Protocol,
			&i.ConnectionMode,
			&i.ConnectorID,
			&i.ConnectorEpoch,
			&i.Status,
			&i.SessionFence,
			&i.AuthorizationVersion,
			&i.IdleTimeoutSeconds,
			&i.MaxDurationSeconds,
			&i.ConnectBefore,
			&i.ConnectedAt,
			&i.TerminatedAt,
			&i.TerminationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const terminateRemoteAccessSessionsByGrant = `-- name: TerminateRemoteAccessSessionsByGrant :many
UPDATE remote_access_sessions session SET status='terminating',session_fence=session_fence+1,termination_reason=$1,updated_at=now()
FROM remote_access_leases lease
WHERE session.lease_id=lease.id AND lease.grant_id=$2 AND session.enterprise_id=$3
  AND session.status IN ('authorized','connecting','active') RETURNING session.id, session.enterprise_id, session.user_id, session.http_session_id, session.lease_id, session.host_id, session.managed_account_id, session.protocol, session.connection_mode, session.connector_id, session.connector_epoch, session.status, session.session_fence, session.authorization_version, session.idle_timeout_seconds, session.max_duration_seconds, session.connect_before, session.connected_at, session.terminated_at, session.termination_reason, session.created_at, session.updated_at
`

type TerminateRemoteAccessSessionsByGrantParams struct {
	Reason       pgtype.Text `json:"reason"`
	GrantID      uuid.UUID   `json:"grant_id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
}

func (q *Queries) TerminateRemoteAccessSessionsByGrant(ctx context.Context, arg TerminateRemoteAccessSessionsByGrantParams) ([]RemoteAccessSession, error) {
	rows, err := q.db.Query(ctx, terminateRemoteAccessSessionsByGrant, arg.Reason, arg.GrantID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RemoteAccessSession{}
	for rows.Next() {
		var i RemoteAccessSession
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.UserID,
			&i.HttpSessionID,
			&i.LeaseID,
			&i.HostID,
			&i.ManagedAccountID,
			&i.Protocol,
			&i.ConnectionMode,
			&i.ConnectorID,
			&i.ConnectorEpoch,
			&i.Status,
			&i.SessionFence,
			&i.AuthorizationVersion,
			&i.IdleTimeoutSeconds,
			&i.MaxDurationSeconds,
			&i.ConnectBefore,
			&i.ConnectedAt,
			&i.TerminatedAt,
			&i.TerminationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const terminateRemoteAccessSessionsByLease = `-- name: TerminateRemoteAccessSessionsByLease :many
UPDATE remote_access_sessions SET status='terminating',session_fence=session_fence+1,termination_reason=$1,updated_at=now()
WHERE lease_id=$2 AND enterprise_id=$3 AND status IN ('authorized','connecting','active') RETURNING id, enterprise_id, user_id, http_session_id, lease_id, host_id, managed_account_id, protocol, connection_mode, connector_id, connector_epoch, status, session_fence, authorization_version, idle_timeout_seconds, max_duration_seconds, connect_before, connected_at, terminated_at, termination_reason, created_at, updated_at
`

type TerminateRemoteAccessSessionsByLeaseParams struct {
	Reason       pgtype.Text `json:"reason"`
	LeaseID      uuid.UUID   `json:"lease_id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
}

func (q *Queries) TerminateRemoteAccessSessionsByLease(ctx context.Context, arg TerminateRemoteAccessSessionsByLeaseParams) ([]RemoteAccessSession, error) {
	rows, err := q.db.Query(ctx, terminateRemoteAccessSessionsByLease, arg.Reason, arg.LeaseID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RemoteAccessSession{}
	for rows.Next() {
		var i RemoteAccessSession
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.UserID,
			&i.HttpSessionID,
			&i.LeaseID,
			&i.HostID,
			&i.ManagedAccountID,
			&i.Protocol,
			&i.ConnectionMode,
			&i.ConnectorID,
			&i.ConnectorEpoch,
			&i.Status,
			&i.SessionFence,
			&i.AuthorizationVersion,
			&i.IdleTimeoutSeconds,
			&i.MaxDurationSeconds,
			&i.ConnectBefore,
			&i.ConnectedAt,
			&i.TerminatedAt,
			&i.TerminationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRemoteAccessRoute = `-- name: UpsertRemoteAccessRoute :one
INSERT INTO remote_access_routes (session_id,gateway_instance,connector_id,connector_epoch,session_fence,lease_expires_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,now())
ON CONFLICT (session_id) DO UPDATE SET gateway_instance=EXCLUDED.gateway_instance,connector_id=EXCLUDED.connector_id,
  connector_epoch=EXCLUDED.connector_epoch,session_fence=EXCLUDED.session_fence,lease_expires_at=EXCLUDED.lease_expires_at,updated_at=now()
WHERE remote_access_routes.session_fence <= EXCLUDED.session_fence
RETURNING session_id, gateway_instance, connector_id, connector_epoch, session_fence, lease_expires_at, updated_at
`

type UpsertRemoteAccessRouteParams struct {
	SessionID       uuid.UUID          `json:"session_id"`
	GatewayInstance string             `json:"gateway_instance"`
	ConnectorID     uuid.NullUUID      `json:"connector_id"`
	ConnectorEpoch  pgtype.Int8        `json:"connector_epoch"`
	SessionFence    int64              `json:"session_fence"`
	LeaseExpiresAt  pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) UpsertRemoteAccessRoute(ctx context.Context, arg UpsertRemoteAccessRouteParams) (RemoteAccessRoute, error) {
	row := q.db.QueryRow(ctx, upsertRemoteAccessRoute,
		arg.SessionID,
		arg.GatewayInstance,
		arg.ConnectorID,
		arg.ConnectorEpoch,
		arg.SessionFence,
		arg.LeaseExpiresAt,
	)
	var i RemoteAccessRoute
	err := row.Scan(
		&i.SessionID,
		&i.GatewayInstance,
		&i.ConnectorID,
		&i.ConnectorEpoch,
		&i.SessionFence,
		&i.LeaseExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}
