// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtime.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimRuntimeTask = `-- name: ClaimRuntimeTask :one
WITH candidate AS (
    SELECT runtime_tasks.id FROM runtime_tasks
    WHERE runtime_tasks.queue = $1
      AND runtime_tasks.attempt < runtime_tasks.max_attempts
      AND runtime_tasks.available_at <= now()
      AND (runtime_tasks.status = 'pending' OR (runtime_tasks.status IN ('leased','running') AND runtime_tasks.lease_until < now()))
    ORDER BY runtime_tasks.available_at, runtime_tasks.created_at
    FOR UPDATE SKIP LOCKED LIMIT 1
)
UPDATE runtime_tasks AS task SET
    status = 'leased', lease_owner = $2, lease_until = now() + $3::interval,
    fence_token = fence_token + 1, attempt = attempt + 1, updated_at = now()
FROM candidate WHERE task.id = candidate.id
RETURNING task.id, task.enterprise_id, task.queue, task.run_id, task.step_id, task.payload, task.status, task.attempt, task.max_attempts, task.lease_owner, task.lease_until, task.fence_token, task.available_at, task.last_error_code, task.created_at, task.updated_at
`

type ClaimRuntimeTaskParams struct {
	Queue      string          `json:"queue"`
	LeaseOwner pgtype.Text     `json:"lease_owner"`
	Column3    pgtype.Interval `json:"column_3"`
}

func (q *Queries) ClaimRuntimeTask(ctx context.Context, arg ClaimRuntimeTaskParams) (RuntimeTask, error) {
	row := q.db.QueryRow(ctx, claimRuntimeTask, arg.Queue, arg.LeaseOwner, arg.Column3)
	var i RuntimeTask
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Queue,
		&i.RunID,
		&i.StepID,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (id, result_ref, enterprise_id, conversation_id, run_id, content_type, data_classification, content, content_hash, byte_size)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, result_ref, enterprise_id, conversation_id, run_id, content_type, data_classification, content, content_hash, byte_size, created_at
`

type CreateArtifactParams struct {
	ID                 uuid.UUID     `json:"id"`
	ResultRef          string        `json:"result_ref"`
	EnterpriseID       uuid.UUID     `json:"enterprise_id"`
	ConversationID     uuid.NullUUID `json:"conversation_id"`
	RunID              uuid.NullUUID `json:"run_id"`
	ContentType        string        `json:"content_type"`
	DataClassification string        `json:"data_classification"`
	Content            []byte        `json:"content"`
	ContentHash        []byte        `json:"content_hash"`
	ByteSize           int32         `json:"byte_size"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ID,
		arg.ResultRef,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.RunID,
		arg.ContentType,
		arg.DataClassification,
		arg.Content,
		arg.ContentHash,
		arg.ByteSize,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ResultRef,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.RunID,
		&i.ContentType,
		&i.DataClassification,
		&i.Content,
		&i.ContentHash,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const createContextSnapshot = `-- name: CreateContextSnapshot :one
INSERT INTO context_snapshots (id, enterprise_id, conversation_id, run_id, revision, source_from_sequence, source_through_sequence,
    first_kept_sequence, typed_checkpoint, narrative_summary, compaction_model_id, compaction_model_revision, prompt_version,
    estimated_tokens_before, actual_tokens_after, source_hash, snapshot_hash, status, error_code)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)
RETURNING id, enterprise_id, conversation_id, run_id, revision, source_from_sequence, source_through_sequence, first_kept_sequence, typed_checkpoint, narrative_summary, compaction_model_id, compaction_model_revision, prompt_version, estimated_tokens_before, actual_tokens_after, source_hash, snapshot_hash, status, error_code, created_at
`

type CreateContextSnapshotParams struct {
	ID                      uuid.UUID   `json:"id"`
	EnterpriseID            uuid.UUID   `json:"enterprise_id"`
	ConversationID          uuid.UUID   `json:"conversation_id"`
	RunID                   uuid.UUID   `json:"run_id"`
	Revision                int32       `json:"revision"`
	SourceFromSequence      int64       `json:"source_from_sequence"`
	SourceThroughSequence   int64       `json:"source_through_sequence"`
	FirstKeptSequence       int64       `json:"first_kept_sequence"`
	TypedCheckpoint         []byte      `json:"typed_checkpoint"`
	NarrativeSummary        string      `json:"narrative_summary"`
	CompactionModelID       uuid.UUID   `json:"compaction_model_id"`
	CompactionModelRevision int32       `json:"compaction_model_revision"`
	PromptVersion           string      `json:"prompt_version"`
	EstimatedTokensBefore   int32       `json:"estimated_tokens_before"`
	ActualTokensAfter       int32       `json:"actual_tokens_after"`
	SourceHash              []byte      `json:"source_hash"`
	SnapshotHash            []byte      `json:"snapshot_hash"`
	Status                  string      `json:"status"`
	ErrorCode               pgtype.Text `json:"error_code"`
}

func (q *Queries) CreateContextSnapshot(ctx context.Context, arg CreateContextSnapshotParams) (ContextSnapshot, error) {
	row := q.db.QueryRow(ctx, createContextSnapshot,
		arg.ID,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.RunID,
		arg.Revision,
		arg.SourceFromSequence,
		arg.SourceThroughSequence,
		arg.FirstKeptSequence,
		arg.TypedCheckpoint,
		arg.NarrativeSummary,
		arg.CompactionModelID,
		arg.CompactionModelRevision,
		arg.PromptVersion,
		arg.EstimatedTokensBefore,
		arg.ActualTokensAfter,
		arg.SourceHash,
		arg.SnapshotHash,
		arg.Status,
		arg.ErrorCode,
	)
	var i ContextSnapshot
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.RunID,
		&i.Revision,
		&i.SourceFromSequence,
		&i.SourceThroughSequence,
		&i.FirstKeptSequence,
		&i.TypedCheckpoint,
		&i.NarrativeSummary,
		&i.CompactionModelID,
		&i.CompactionModelRevision,
		&i.PromptVersion,
		&i.EstimatedTokensBefore,
		&i.ActualTokensAfter,
		&i.SourceHash,
		&i.SnapshotHash,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, enterprise_id, owner_user_id, title, selected_model_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, enterprise_id, owner_user_id, title, selected_model_id, status, version, created_at, updated_at
`

type CreateConversationParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	OwnerUserID     uuid.UUID `json:"owner_user_id"`
	Title           string    `json:"title"`
	SelectedModelID uuid.UUID `json:"selected_model_id"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.EnterpriseID,
		arg.OwnerUserID,
		arg.Title,
		arg.SelectedModelID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.OwnerUserID,
		&i.Title,
		&i.SelectedModelID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConversationEvent = `-- name: CreateConversationEvent :one
INSERT INTO conversation_events (id, enterprise_id, conversation_id, run_id, step_id, sequence, event_type, actor_type, actor_id, payload, content_hash, artifact_ref, data_classification)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, enterprise_id, conversation_id, run_id, step_id, sequence, event_type, actor_type, actor_id, payload, content_hash, artifact_ref, data_classification, occurred_at
`

type CreateConversationEventParams struct {
	ID                 uuid.UUID     `json:"id"`
	EnterpriseID       uuid.UUID     `json:"enterprise_id"`
	ConversationID     uuid.UUID     `json:"conversation_id"`
	RunID              uuid.NullUUID `json:"run_id"`
	StepID             uuid.NullUUID `json:"step_id"`
	Sequence           int64         `json:"sequence"`
	EventType          string        `json:"event_type"`
	ActorType          string        `json:"actor_type"`
	ActorID            pgtype.Text   `json:"actor_id"`
	Payload            []byte        `json:"payload"`
	ContentHash        []byte        `json:"content_hash"`
	ArtifactRef        pgtype.Text   `json:"artifact_ref"`
	DataClassification string        `json:"data_classification"`
}

func (q *Queries) CreateConversationEvent(ctx context.Context, arg CreateConversationEventParams) (ConversationEvent, error) {
	row := q.db.QueryRow(ctx, createConversationEvent,
		arg.ID,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.RunID,
		arg.StepID,
		arg.Sequence,
		arg.EventType,
		arg.ActorType,
		arg.ActorID,
		arg.Payload,
		arg.ContentHash,
		arg.ArtifactRef,
		arg.DataClassification,
	)
	var i ConversationEvent
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.RunID,
		&i.StepID,
		&i.Sequence,
		&i.EventType,
		&i.ActorType,
		&i.ActorID,
		&i.Payload,
		&i.ContentHash,
		&i.ArtifactRef,
		&i.DataClassification,
		&i.OccurredAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, conversation_id, enterprise_id, actor_user_id, model_id, model_revision, locale, authorization_version, checkpoint)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, conversation_id, enterprise_id, actor_user_id, model_id, model_revision, locale, status, current_step_id, authorization_version, checkpoint, stop_reason, error_code, version, created_at, updated_at
`

type CreateRunParams struct {
	ID                   uuid.UUID `json:"id"`
	ConversationID       uuid.UUID `json:"conversation_id"`
	EnterpriseID         uuid.UUID `json:"enterprise_id"`
	ActorUserID          uuid.UUID `json:"actor_user_id"`
	ModelID              uuid.UUID `json:"model_id"`
	ModelRevision        int32     `json:"model_revision"`
	Locale               string    `json:"locale"`
	AuthorizationVersion int64     `json:"authorization_version"`
	Checkpoint           []byte    `json:"checkpoint"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.ConversationID,
		arg.EnterpriseID,
		arg.ActorUserID,
		arg.ModelID,
		arg.ModelRevision,
		arg.Locale,
		arg.AuthorizationVersion,
		arg.Checkpoint,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ModelID,
		&i.ModelRevision,
		&i.Locale,
		&i.Status,
		&i.CurrentStepID,
		&i.AuthorizationVersion,
		&i.Checkpoint,
		&i.StopReason,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRunStep = `-- name: CreateRunStep :one
INSERT INTO run_steps (id, run_id, enterprise_id, sequence, step_type, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_id, enterprise_id, sequence, step_type, status, attempt, version, created_at, updated_at
`

type CreateRunStepParams struct {
	ID           uuid.UUID `json:"id"`
	RunID        uuid.UUID `json:"run_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Sequence     int32     `json:"sequence"`
	StepType     string    `json:"step_type"`
	Status       string    `json:"status"`
}

func (q *Queries) CreateRunStep(ctx context.Context, arg CreateRunStepParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, createRunStep,
		arg.ID,
		arg.RunID,
		arg.EnterpriseID,
		arg.Sequence,
		arg.StepType,
		arg.Status,
	)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.EnterpriseID,
		&i.Sequence,
		&i.StepType,
		&i.Status,
		&i.Attempt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRuntimeTask = `-- name: CreateRuntimeTask :one
INSERT INTO runtime_tasks (id, enterprise_id, queue, run_id, step_id, payload, max_attempts, available_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, enterprise_id, queue, run_id, step_id, payload, status, attempt, max_attempts, lease_owner, lease_until, fence_token, available_at, last_error_code, created_at, updated_at
`

type CreateRuntimeTaskParams struct {
	ID           uuid.UUID          `json:"id"`
	EnterpriseID uuid.NullUUID      `json:"enterprise_id"`
	Queue        string             `json:"queue"`
	RunID        uuid.NullUUID      `json:"run_id"`
	StepID       uuid.NullUUID      `json:"step_id"`
	Payload      []byte             `json:"payload"`
	MaxAttempts  int32              `json:"max_attempts"`
	AvailableAt  pgtype.Timestamptz `json:"available_at"`
}

func (q *Queries) CreateRuntimeTask(ctx context.Context, arg CreateRuntimeTaskParams) (RuntimeTask, error) {
	row := q.db.QueryRow(ctx, createRuntimeTask,
		arg.ID,
		arg.EnterpriseID,
		arg.Queue,
		arg.RunID,
		arg.StepID,
		arg.Payload,
		arg.MaxAttempts,
		arg.AvailableAt,
	)
	var i RuntimeTask
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Queue,
		&i.RunID,
		&i.StepID,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createToolCall = `-- name: CreateToolCall :one
INSERT INTO tool_calls (id, call_id, enterprise_id, run_id, step_id, tool_id, input, input_hash, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, call_id, enterprise_id, run_id, step_id, tool_id, input, input_hash, status, error_code, created_at, updated_at
`

type CreateToolCallParams struct {
	ID           uuid.UUID `json:"id"`
	CallID       string    `json:"call_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	RunID        uuid.UUID `json:"run_id"`
	StepID       uuid.UUID `json:"step_id"`
	ToolID       string    `json:"tool_id"`
	Input        []byte    `json:"input"`
	InputHash    []byte    `json:"input_hash"`
	Status       string    `json:"status"`
}

func (q *Queries) CreateToolCall(ctx context.Context, arg CreateToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, createToolCall,
		arg.ID,
		arg.CallID,
		arg.EnterpriseID,
		arg.RunID,
		arg.StepID,
		arg.ToolID,
		arg.Input,
		arg.InputHash,
		arg.Status,
	)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.EnterpriseID,
		&i.RunID,
		&i.StepID,
		&i.ToolID,
		&i.Input,
		&i.InputHash,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createToolResult = `-- name: CreateToolResult :one
INSERT INTO tool_results (id, tool_call_id, enterprise_id, artifact_id, projection, projection_hash, projection_bytes, partial)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tool_call_id, enterprise_id, artifact_id, projection, projection_hash, projection_bytes, partial, created_at
`

type CreateToolResultParams struct {
	ID              uuid.UUID `json:"id"`
	ToolCallID      uuid.UUID `json:"tool_call_id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ArtifactID      uuid.UUID `json:"artifact_id"`
	Projection      []byte    `json:"projection"`
	ProjectionHash  []byte    `json:"projection_hash"`
	ProjectionBytes int32     `json:"projection_bytes"`
	Partial         bool      `json:"partial"`
}

func (q *Queries) CreateToolResult(ctx context.Context, arg CreateToolResultParams) (ToolResult, error) {
	row := q.db.QueryRow(ctx, createToolResult,
		arg.ID,
		arg.ToolCallID,
		arg.EnterpriseID,
		arg.ArtifactID,
		arg.Projection,
		arg.ProjectionHash,
		arg.ProjectionBytes,
		arg.Partial,
	)
	var i ToolResult
	err := row.Scan(
		&i.ID,
		&i.ToolCallID,
		&i.EnterpriseID,
		&i.ArtifactID,
		&i.Projection,
		&i.ProjectionHash,
		&i.ProjectionBytes,
		&i.Partial,
		&i.CreatedAt,
	)
	return i, err
}

const finishRunStep = `-- name: FinishRunStep :one
UPDATE run_steps SET status = $3, version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND status IN ('pending','leased','running','waiting_input','waiting_approval')
RETURNING id, run_id, enterprise_id, sequence, step_type, status, attempt, version, created_at, updated_at
`

type FinishRunStepParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Status       string    `json:"status"`
}

func (q *Queries) FinishRunStep(ctx context.Context, arg FinishRunStepParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, finishRunStep, arg.ID, arg.EnterpriseID, arg.Status)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.EnterpriseID,
		&i.Sequence,
		&i.StepType,
		&i.Status,
		&i.Attempt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishRuntimeTask = `-- name: FinishRuntimeTask :one
UPDATE runtime_tasks SET status = $4, last_error_code = $5, lease_owner = NULL, lease_until = NULL, updated_at = now()
WHERE id = $1 AND lease_owner = $2 AND fence_token = $3 AND status IN ('leased','running')
RETURNING id, enterprise_id, queue, run_id, step_id, payload, status, attempt, max_attempts, lease_owner, lease_until, fence_token, available_at, last_error_code, created_at, updated_at
`

type FinishRuntimeTaskParams struct {
	ID            uuid.UUID   `json:"id"`
	LeaseOwner    pgtype.Text `json:"lease_owner"`
	FenceToken    int64       `json:"fence_token"`
	Status        string      `json:"status"`
	LastErrorCode pgtype.Text `json:"last_error_code"`
}

func (q *Queries) FinishRuntimeTask(ctx context.Context, arg FinishRuntimeTaskParams) (RuntimeTask, error) {
	row := q.db.QueryRow(ctx, finishRuntimeTask,
		arg.ID,
		arg.LeaseOwner,
		arg.FenceToken,
		arg.Status,
		arg.LastErrorCode,
	)
	var i RuntimeTask
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Queue,
		&i.RunID,
		&i.StepID,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishToolCall = `-- name: FinishToolCall :one
UPDATE tool_calls SET status = $2, error_code = $3, updated_at = now() WHERE id = $1 RETURNING id, call_id, enterprise_id, run_id, step_id, tool_id, input, input_hash, status, error_code, created_at, updated_at
`

type FinishToolCallParams struct {
	ID        uuid.UUID   `json:"id"`
	Status    string      `json:"status"`
	ErrorCode pgtype.Text `json:"error_code"`
}

func (q *Queries) FinishToolCall(ctx context.Context, arg FinishToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, finishToolCall, arg.ID, arg.Status, arg.ErrorCode)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.EnterpriseID,
		&i.RunID,
		&i.StepID,
		&i.ToolID,
		&i.Input,
		&i.InputHash,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveContextSnapshot = `-- name: GetActiveContextSnapshot :one
SELECT id, enterprise_id, conversation_id, run_id, revision, source_from_sequence, source_through_sequence, first_kept_sequence, typed_checkpoint, narrative_summary, compaction_model_id, compaction_model_revision, prompt_version, estimated_tokens_before, actual_tokens_after, source_hash, snapshot_hash, status, error_code, created_at FROM context_snapshots WHERE run_id = $1 AND enterprise_id = $2 AND status = 'active'
`

type GetActiveContextSnapshotParams struct {
	RunID        uuid.UUID `json:"run_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetActiveContextSnapshot(ctx context.Context, arg GetActiveContextSnapshotParams) (ContextSnapshot, error) {
	row := q.db.QueryRow(ctx, getActiveContextSnapshot, arg.RunID, arg.EnterpriseID)
	var i ContextSnapshot
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.RunID,
		&i.Revision,
		&i.SourceFromSequence,
		&i.SourceThroughSequence,
		&i.FirstKeptSequence,
		&i.TypedCheckpoint,
		&i.NarrativeSummary,
		&i.CompactionModelID,
		&i.CompactionModelRevision,
		&i.PromptVersion,
		&i.EstimatedTokensBefore,
		&i.ActualTokensAfter,
		&i.SourceHash,
		&i.SnapshotHash,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveRunForConversation = `-- name: GetActiveRunForConversation :one
SELECT id, conversation_id, enterprise_id, actor_user_id, model_id, model_revision, locale, status, current_step_id, authorization_version, checkpoint, stop_reason, error_code, version, created_at, updated_at FROM runs
WHERE conversation_id = $1 AND enterprise_id = $2
  AND status IN ('pending','running','waiting_input','waiting_approval','waiting_system')
ORDER BY created_at DESC LIMIT 1
`

type GetActiveRunForConversationParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetActiveRunForConversation(ctx context.Context, arg GetActiveRunForConversationParams) (Run, error) {
	row := q.db.QueryRow(ctx, getActiveRunForConversation, arg.ConversationID, arg.EnterpriseID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ModelID,
		&i.ModelRevision,
		&i.Locale,
		&i.Status,
		&i.CurrentStepID,
		&i.AuthorizationVersion,
		&i.Checkpoint,
		&i.StopReason,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactByRef = `-- name: GetArtifactByRef :one
SELECT id, result_ref, enterprise_id, conversation_id, run_id, content_type, data_classification, content, content_hash, byte_size, created_at FROM artifacts WHERE result_ref = $1 AND enterprise_id = $2
`

type GetArtifactByRefParams struct {
	ResultRef    string    `json:"result_ref"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetArtifactByRef(ctx context.Context, arg GetArtifactByRefParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByRef, arg.ResultRef, arg.EnterpriseID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ResultRef,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.RunID,
		&i.ContentType,
		&i.DataClassification,
		&i.Content,
		&i.ContentHash,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, enterprise_id, owner_user_id, title, selected_model_id, status, version, created_at, updated_at FROM conversations WHERE id = $1 AND enterprise_id = $2 AND owner_user_id = $3
`

type GetConversationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	OwnerUserID  uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.EnterpriseID, arg.OwnerUserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.OwnerUserID,
		&i.Title,
		&i.SelectedModelID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, conversation_id, enterprise_id, actor_user_id, model_id, model_revision, locale, status, current_step_id, authorization_version, checkpoint, stop_reason, error_code, version, created_at, updated_at FROM runs WHERE id = $1 AND enterprise_id = $2
`

type GetRunParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.EnterpriseID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ModelID,
		&i.ModelRevision,
		&i.Locale,
		&i.Status,
		&i.CurrentStepID,
		&i.AuthorizationVersion,
		&i.Checkpoint,
		&i.StopReason,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolResultByArtifact = `-- name: GetToolResultByArtifact :one
SELECT result.id, result.tool_call_id, result.enterprise_id, result.artifact_id, result.projection, result.projection_hash, result.projection_bytes, result.partial, result.created_at, call.call_id, call.tool_id FROM tool_results result
JOIN tool_calls call ON call.id = result.tool_call_id
WHERE result.artifact_id = $1 AND result.enterprise_id = $2
`

type GetToolResultByArtifactParams struct {
	ArtifactID   uuid.UUID `json:"artifact_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

type GetToolResultByArtifactRow struct {
	ID              uuid.UUID          `json:"id"`
	ToolCallID      uuid.UUID          `json:"tool_call_id"`
	EnterpriseID    uuid.UUID          `json:"enterprise_id"`
	ArtifactID      uuid.UUID          `json:"artifact_id"`
	Projection      []byte             `json:"projection"`
	ProjectionHash  []byte             `json:"projection_hash"`
	ProjectionBytes int32              `json:"projection_bytes"`
	Partial         bool               `json:"partial"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CallID          string             `json:"call_id"`
	ToolID          string             `json:"tool_id"`
}

func (q *Queries) GetToolResultByArtifact(ctx context.Context, arg GetToolResultByArtifactParams) (GetToolResultByArtifactRow, error) {
	row := q.db.QueryRow(ctx, getToolResultByArtifact, arg.ArtifactID, arg.EnterpriseID)
	var i GetToolResultByArtifactRow
	err := row.Scan(
		&i.ID,
		&i.ToolCallID,
		&i.EnterpriseID,
		&i.ArtifactID,
		&i.Projection,
		&i.ProjectionHash,
		&i.ProjectionBytes,
		&i.Partial,
		&i.CreatedAt,
		&i.CallID,
		&i.ToolID,
	)
	return i, err
}

const listConversationEvents = `-- name: ListConversationEvents :many
SELECT id, enterprise_id, conversation_id, run_id, step_id, sequence, event_type, actor_type, actor_id, payload, content_hash, artifact_ref, data_classification, occurred_at FROM conversation_events
WHERE conversation_id = $1 AND enterprise_id = $2 AND sequence > $3
ORDER BY sequence LIMIT $4
`

type ListConversationEventsParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	Sequence       int64     `json:"sequence"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListConversationEvents(ctx context.Context, arg ListConversationEventsParams) ([]ConversationEvent, error) {
	rows, err := q.db.Query(ctx, listConversationEvents,
		arg.ConversationID,
		arg.EnterpriseID,
		arg.Sequence,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationEvent{}
	for rows.Next() {
		var i ConversationEvent
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.ConversationID,
			&i.RunID,
			&i.StepID,
			&i.Sequence,
			&i.EventType,
			&i.ActorType,
			&i.ActorID,
			&i.Payload,
			&i.ContentHash,
			&i.ArtifactRef,
			&i.DataClassification,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT id, enterprise_id, owner_user_id, title, selected_model_id, status, version, created_at, updated_at FROM conversations
WHERE enterprise_id = $1 AND owner_user_id = $2
ORDER BY updated_at DESC, id DESC LIMIT $3
`

type ListConversationsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	OwnerUserID  uuid.UUID `json:"owner_user_id"`
	Limit        int32     `json:"limit"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.EnterpriseID, arg.OwnerUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.OwnerUserID,
			&i.Title,
			&i.SelectedModelID,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunConversationEvents = `-- name: ListRunConversationEvents :many
SELECT id, enterprise_id, conversation_id, run_id, step_id, sequence, event_type, actor_type, actor_id, payload, content_hash, artifact_ref, data_classification, occurred_at FROM conversation_events WHERE run_id = $1 AND enterprise_id = $2 ORDER BY sequence
`

type ListRunConversationEventsParams struct {
	RunID        uuid.NullUUID `json:"run_id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
}

func (q *Queries) ListRunConversationEvents(ctx context.Context, arg ListRunConversationEventsParams) ([]ConversationEvent, error) {
	rows, err := q.db.Query(ctx, listRunConversationEvents, arg.RunID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationEvent{}
	for rows.Next() {
		var i ConversationEvent
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.ConversationID,
			&i.RunID,
			&i.StepID,
			&i.Sequence,
			&i.EventType,
			&i.ActorType,
			&i.ActorID,
			&i.Payload,
			&i.ContentHash,
			&i.ArtifactRef,
			&i.DataClassification,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConversation = `-- name: LockConversation :one
SELECT id, enterprise_id, owner_user_id, title, selected_model_id, status, version, created_at, updated_at FROM conversations WHERE id = $1 AND enterprise_id = $2 AND owner_user_id = $3 FOR UPDATE
`

type LockConversationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	OwnerUserID  uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) LockConversation(ctx context.Context, arg LockConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, lockConversation, arg.ID, arg.EnterpriseID, arg.OwnerUserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.OwnerUserID,
		&i.Title,
		&i.SelectedModelID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextContextSnapshotRevision = `-- name: NextContextSnapshotRevision :one
SELECT COALESCE(MAX(revision), 0)::integer + 1 FROM context_snapshots WHERE run_id = $1 AND enterprise_id = $2
`

type NextContextSnapshotRevisionParams struct {
	RunID        uuid.UUID `json:"run_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) NextContextSnapshotRevision(ctx context.Context, arg NextContextSnapshotRevisionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextContextSnapshotRevision, arg.RunID, arg.EnterpriseID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextConversationSequence = `-- name: NextConversationSequence :one
SELECT COALESCE(MAX(sequence), 0)::bigint + 1 AS sequence
FROM conversation_events WHERE conversation_id = $1
`

func (q *Queries) NextConversationSequence(ctx context.Context, conversationID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextConversationSequence, conversationID)
	var sequence int32
	err := row.Scan(&sequence)
	return sequence, err
}

const nextRunStepSequence = `-- name: NextRunStepSequence :one
SELECT COALESCE(MAX(sequence), 0)::integer + 1 FROM run_steps WHERE run_id = $1 AND enterprise_id = $2
`

type NextRunStepSequenceParams struct {
	RunID        uuid.UUID `json:"run_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) NextRunStepSequence(ctx context.Context, arg NextRunStepSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextRunStepSequence, arg.RunID, arg.EnterpriseID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const renewRuntimeTaskLease = `-- name: RenewRuntimeTaskLease :one
UPDATE runtime_tasks SET lease_until = now() + $4::interval, updated_at = now()
WHERE id = $1 AND lease_owner = $2 AND fence_token = $3 AND status IN ('leased','running')
RETURNING id, enterprise_id, queue, run_id, step_id, payload, status, attempt, max_attempts, lease_owner, lease_until, fence_token, available_at, last_error_code, created_at, updated_at
`

type RenewRuntimeTaskLeaseParams struct {
	ID         uuid.UUID       `json:"id"`
	LeaseOwner pgtype.Text     `json:"lease_owner"`
	FenceToken int64           `json:"fence_token"`
	Column4    pgtype.Interval `json:"column_4"`
}

func (q *Queries) RenewRuntimeTaskLease(ctx context.Context, arg RenewRuntimeTaskLeaseParams) (RuntimeTask, error) {
	row := q.db.QueryRow(ctx, renewRuntimeTaskLease,
		arg.ID,
		arg.LeaseOwner,
		arg.FenceToken,
		arg.Column4,
	)
	var i RuntimeTask
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Queue,
		&i.RunID,
		&i.StepID,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueRuntimeTask = `-- name: RequeueRuntimeTask :one
UPDATE runtime_tasks SET status = 'pending', last_error_code = $4, available_at = $5,
    lease_owner = NULL, lease_until = NULL, updated_at = now()
WHERE id = $1 AND lease_owner = $2 AND fence_token = $3
RETURNING id, enterprise_id, queue, run_id, step_id, payload, status, attempt, max_attempts, lease_owner, lease_until, fence_token, available_at, last_error_code, created_at, updated_at
`

type RequeueRuntimeTaskParams struct {
	ID            uuid.UUID          `json:"id"`
	LeaseOwner    pgtype.Text        `json:"lease_owner"`
	FenceToken    int64              `json:"fence_token"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
}

func (q *Queries) RequeueRuntimeTask(ctx context.Context, arg RequeueRuntimeTaskParams) (RuntimeTask, error) {
	row := q.db.QueryRow(ctx, requeueRuntimeTask,
		arg.ID,
		arg.LeaseOwner,
		arg.FenceToken,
		arg.LastErrorCode,
		arg.AvailableAt,
	)
	var i RuntimeTask
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Queue,
		&i.RunID,
		&i.StepID,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRunCurrentStep = `-- name: SetRunCurrentStep :one
UPDATE runs SET status = $3, current_step_id = $4, version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND version = $5
RETURNING id, conversation_id, enterprise_id, actor_user_id, model_id, model_revision, locale, status, current_step_id, authorization_version, checkpoint, stop_reason, error_code, version, created_at, updated_at
`

type SetRunCurrentStepParams struct {
	ID            uuid.UUID     `json:"id"`
	EnterpriseID  uuid.UUID     `json:"enterprise_id"`
	Status        string        `json:"status"`
	CurrentStepID uuid.NullUUID `json:"current_step_id"`
	Version       int64         `json:"version"`
}

func (q *Queries) SetRunCurrentStep(ctx context.Context, arg SetRunCurrentStepParams) (Run, error) {
	row := q.db.QueryRow(ctx, setRunCurrentStep,
		arg.ID,
		arg.EnterpriseID,
		arg.Status,
		arg.CurrentStepID,
		arg.Version,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ModelID,
		&i.ModelRevision,
		&i.Locale,
		&i.Status,
		&i.CurrentStepID,
		&i.AuthorizationVersion,
		&i.Checkpoint,
		&i.StopReason,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startRuntimeTask = `-- name: StartRuntimeTask :one
UPDATE runtime_tasks SET status = 'running', updated_at = now()
WHERE id = $1 AND lease_owner = $2 AND fence_token = $3 AND status = 'leased' AND lease_until > now()
RETURNING id, enterprise_id, queue, run_id, step_id, payload, status, attempt, max_attempts, lease_owner, lease_until, fence_token, available_at, last_error_code, created_at, updated_at
`

type StartRuntimeTaskParams struct {
	ID         uuid.UUID   `json:"id"`
	LeaseOwner pgtype.Text `json:"lease_owner"`
	FenceToken int64       `json:"fence_token"`
}

func (q *Queries) StartRuntimeTask(ctx context.Context, arg StartRuntimeTaskParams) (RuntimeTask, error) {
	row := q.db.QueryRow(ctx, startRuntimeTask, arg.ID, arg.LeaseOwner, arg.FenceToken)
	var i RuntimeTask
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Queue,
		&i.RunID,
		&i.StepID,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.AvailableAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const supersedeContextSnapshots = `-- name: SupersedeContextSnapshots :exec
UPDATE context_snapshots SET status = 'superseded'
WHERE run_id = $1 AND enterprise_id = $2 AND status = 'active'
`

type SupersedeContextSnapshotsParams struct {
	RunID        uuid.UUID `json:"run_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) SupersedeContextSnapshots(ctx context.Context, arg SupersedeContextSnapshotsParams) error {
	_, err := q.db.Exec(ctx, supersedeContextSnapshots, arg.RunID, arg.EnterpriseID)
	return err
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations SET
    title = COALESCE($1, title),
    selected_model_id = COALESCE($2, selected_model_id),
    status = COALESCE($3, status),
    version = version + 1, updated_at = now()
WHERE id = $4 AND enterprise_id = $5
  AND owner_user_id = $6 AND version = $7
RETURNING id, enterprise_id, owner_user_id, title, selected_model_id, status, version, created_at, updated_at
`

type UpdateConversationParams struct {
	Title           pgtype.Text   `json:"title"`
	SelectedModelID uuid.NullUUID `json:"selected_model_id"`
	Status          pgtype.Text   `json:"status"`
	ID              uuid.UUID     `json:"id"`
	EnterpriseID    uuid.UUID     `json:"enterprise_id"`
	OwnerUserID     uuid.UUID     `json:"owner_user_id"`
	ExpectedVersion int64         `json:"expected_version"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversation,
		arg.Title,
		arg.SelectedModelID,
		arg.Status,
		arg.ID,
		arg.EnterpriseID,
		arg.OwnerUserID,
		arg.ExpectedVersion,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.OwnerUserID,
		&i.Title,
		&i.SelectedModelID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs SET status = $3, stop_reason = $4, error_code = $5, version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND version = $6
RETURNING id, conversation_id, enterprise_id, actor_user_id, model_id, model_revision, locale, status, current_step_id, authorization_version, checkpoint, stop_reason, error_code, version, created_at, updated_at
`

type UpdateRunStatusParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	Status       string      `json:"status"`
	StopReason   pgtype.Text `json:"stop_reason"`
	ErrorCode    pgtype.Text `json:"error_code"`
	Version      int64       `json:"version"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunStatus,
		arg.ID,
		arg.EnterpriseID,
		arg.Status,
		arg.StopReason,
		arg.ErrorCode,
		arg.Version,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ModelID,
		&i.ModelRevision,
		&i.Locale,
		&i.Status,
		&i.CurrentStepID,
		&i.AuthorizationVersion,
		&i.Checkpoint,
		&i.StopReason,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
