// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSecretVersion = `-- name: AdvanceSecretVersion :one
UPDATE secrets SET current_version = current_version + 1, version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND version = $3 RETURNING id, enterprise_id, name, type, description, status, current_version, last_accessed_at, version, created_by, created_at, updated_at
`

type AdvanceSecretVersionParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Version      int64     `json:"version"`
}

func (q *Queries) AdvanceSecretVersion(ctx context.Context, arg AdvanceSecretVersionParams) (Secret, error) {
	row := q.db.QueryRow(ctx, advanceSecretVersion, arg.ID, arg.EnterpriseID, arg.Version)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.CurrentVersion,
		&i.LastAccessedAt,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeCredentialLease = `-- name: ConsumeCredentialLease :execrows
UPDATE credential_leases SET status = 'consumed', consumed_at = now()
WHERE id = $1 AND enterprise_id = $2 AND status = 'active' AND expires_at > now()
`

type ConsumeCredentialLeaseParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ConsumeCredentialLease(ctx context.Context, arg ConsumeCredentialLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeCredentialLease, arg.ID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (id, enterprise_id, name, protocol, username, secret_id)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, enterprise_id, name, protocol, username, secret_id, status, version, created_at, updated_at
`

type CreateCredentialParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Name         string    `json:"name"`
	Protocol     string    `json:"protocol"`
	Username     string    `json:"username"`
	SecretID     uuid.UUID `json:"secret_id"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.EnterpriseID,
		arg.Name,
		arg.Protocol,
		arg.Username,
		arg.SecretID,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Protocol,
		&i.Username,
		&i.SecretID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCredentialLease = `-- name: CreateCredentialLease :one
INSERT INTO credential_leases (id, enterprise_id, credential_id, secret_version_id, operation_ref, target_resource_type, target_resource_id, recipient_type, recipient_id, protocol, expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id, enterprise_id, credential_id, secret_version_id, operation_ref, target_resource_type, target_resource_id, recipient_type, recipient_id, protocol, status, expires_at, consumed_at, created_at
`

type CreateCredentialLeaseParams struct {
	ID                 uuid.UUID          `json:"id"`
	EnterpriseID       uuid.UUID          `json:"enterprise_id"`
	CredentialID       uuid.UUID          `json:"credential_id"`
	SecretVersionID    uuid.UUID          `json:"secret_version_id"`
	OperationRef       string             `json:"operation_ref"`
	TargetResourceType string             `json:"target_resource_type"`
	TargetResourceID   uuid.UUID          `json:"target_resource_id"`
	RecipientType      string             `json:"recipient_type"`
	RecipientID        string             `json:"recipient_id"`
	Protocol           string             `json:"protocol"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCredentialLease(ctx context.Context, arg CreateCredentialLeaseParams) (CredentialLease, error) {
	row := q.db.QueryRow(ctx, createCredentialLease,
		arg.ID,
		arg.EnterpriseID,
		arg.CredentialID,
		arg.SecretVersionID,
		arg.OperationRef,
		arg.TargetResourceType,
		arg.TargetResourceID,
		arg.RecipientType,
		arg.RecipientID,
		arg.Protocol,
		arg.ExpiresAt,
	)
	var i CredentialLease
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CredentialID,
		&i.SecretVersionID,
		&i.OperationRef,
		&i.TargetResourceType,
		&i.TargetResourceID,
		&i.RecipientType,
		&i.RecipientID,
		&i.Protocol,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createManagedAccount = `-- name: CreateManagedAccount :one
INSERT INTO managed_accounts (id, enterprise_id, host_id, username, privilege_level, credential_id, allowed_protocols)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, enterprise_id, host_id, username, privilege_level, credential_id, allowed_protocols, status, version, created_at, updated_at
`

type CreateManagedAccountParams struct {
	ID               uuid.UUID `json:"id"`
	EnterpriseID     uuid.UUID `json:"enterprise_id"`
	HostID           uuid.UUID `json:"host_id"`
	Username         string    `json:"username"`
	PrivilegeLevel   string    `json:"privilege_level"`
	CredentialID     uuid.UUID `json:"credential_id"`
	AllowedProtocols []string  `json:"allowed_protocols"`
}

func (q *Queries) CreateManagedAccount(ctx context.Context, arg CreateManagedAccountParams) (ManagedAccount, error) {
	row := q.db.QueryRow(ctx, createManagedAccount,
		arg.ID,
		arg.EnterpriseID,
		arg.HostID,
		arg.Username,
		arg.PrivilegeLevel,
		arg.CredentialID,
		arg.AllowedProtocols,
	)
	var i ManagedAccount
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.Username,
		&i.PrivilegeLevel,
		&i.CredentialID,
		&i.AllowedProtocols,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (id, enterprise_id, name, type, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, enterprise_id, name, type, description, status, current_version, last_accessed_at, version, created_by, created_at, updated_at
`

type CreateSecretParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Name         string    `json:"name"`
	Type         string    `json:"type"`
	Description  string    `json:"description"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.ID,
		arg.EnterpriseID,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.CreatedBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.CurrentVersion,
		&i.LastAccessedAt,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSecretVersion = `-- name: CreateSecretVersion :one
INSERT INTO secret_versions (id, secret_id, enterprise_id, version, provider, key_id, key_version, wrapped_dek, wrap_nonce, nonce, ciphertext, value_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING id, secret_id, enterprise_id, version, provider, key_id, key_version, wrapped_dek, wrap_nonce, nonce, ciphertext, value_hash, created_at
`

type CreateSecretVersionParams struct {
	ID           uuid.UUID `json:"id"`
	SecretID     uuid.UUID `json:"secret_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Version      int32     `json:"version"`
	Provider     string    `json:"provider"`
	KeyID        string    `json:"key_id"`
	KeyVersion   int32     `json:"key_version"`
	WrappedDek   []byte    `json:"wrapped_dek"`
	WrapNonce    []byte    `json:"wrap_nonce"`
	Nonce        []byte    `json:"nonce"`
	Ciphertext   []byte    `json:"ciphertext"`
	ValueHash    []byte    `json:"value_hash"`
}

func (q *Queries) CreateSecretVersion(ctx context.Context, arg CreateSecretVersionParams) (SecretVersion, error) {
	row := q.db.QueryRow(ctx, createSecretVersion,
		arg.ID,
		arg.SecretID,
		arg.EnterpriseID,
		arg.Version,
		arg.Provider,
		arg.KeyID,
		arg.KeyVersion,
		arg.WrappedDek,
		arg.WrapNonce,
		arg.Nonce,
		arg.Ciphertext,
		arg.ValueHash,
	)
	var i SecretVersion
	err := row.Scan(
		&i.ID,
		&i.SecretID,
		&i.EnterpriseID,
		&i.Version,
		&i.Provider,
		&i.KeyID,
		&i.KeyVersion,
		&i.WrappedDek,
		&i.WrapNonce,
		&i.Nonce,
		&i.Ciphertext,
		&i.ValueHash,
		&i.CreatedAt,
	)
	return i, err
}

const disableSecret = `-- name: DisableSecret :execrows
UPDATE secrets AS secret SET status = 'disabled', version = secret.version + 1, updated_at = now()
WHERE secret.id = $1 AND secret.enterprise_id = $2 AND secret.version = $3 AND secret.status = 'active'
  AND NOT EXISTS (SELECT 1 FROM credentials AS credential WHERE credential.secret_id = secret.id AND credential.status = 'active')
`

type DisableSecretParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Version      int64     `json:"version"`
}

func (q *Queries) DisableSecret(ctx context.Context, arg DisableSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableSecret, arg.ID, arg.EnterpriseID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireCredentialLeases = `-- name: ExpireCredentialLeases :execrows
UPDATE credential_leases SET status = 'expired'
WHERE status = 'active' AND expires_at <= now()
`

func (q *Queries) ExpireCredentialLeases(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireCredentialLeases)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCredential = `-- name: GetCredential :one
SELECT id, enterprise_id, name, protocol, username, secret_id, status, version, created_at, updated_at FROM credentials WHERE id = $1 AND enterprise_id = $2
`

type GetCredentialParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredential, arg.ID, arg.EnterpriseID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Protocol,
		&i.Username,
		&i.SecretID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialLease = `-- name: GetCredentialLease :one
SELECT id, enterprise_id, credential_id, secret_version_id, operation_ref, target_resource_type, target_resource_id, recipient_type, recipient_id, protocol, status, expires_at, consumed_at, created_at FROM credential_leases WHERE id = $1 AND enterprise_id = $2
`

type GetCredentialLeaseParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetCredentialLease(ctx context.Context, arg GetCredentialLeaseParams) (CredentialLease, error) {
	row := q.db.QueryRow(ctx, getCredentialLease, arg.ID, arg.EnterpriseID)
	var i CredentialLease
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CredentialID,
		&i.SecretVersionID,
		&i.OperationRef,
		&i.TargetResourceType,
		&i.TargetResourceID,
		&i.RecipientType,
		&i.RecipientID,
		&i.Protocol,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentSecretVersion = `-- name: GetCurrentSecretVersion :one
SELECT v.id, v.secret_id, v.enterprise_id, v.version, v.provider, v.key_id, v.key_version, v.wrapped_dek, v.wrap_nonce, v.nonce, v.ciphertext, v.value_hash, v.created_at FROM secret_versions v JOIN secrets s ON s.id = v.secret_id
WHERE v.secret_id = $1 AND v.enterprise_id = $2 AND v.version = s.current_version
`

type GetCurrentSecretVersionParams struct {
	SecretID     uuid.UUID `json:"secret_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetCurrentSecretVersion(ctx context.Context, arg GetCurrentSecretVersionParams) (SecretVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentSecretVersion, arg.SecretID, arg.EnterpriseID)
	var i SecretVersion
	err := row.Scan(
		&i.ID,
		&i.SecretID,
		&i.EnterpriseID,
		&i.Version,
		&i.Provider,
		&i.KeyID,
		&i.KeyVersion,
		&i.WrappedDek,
		&i.WrapNonce,
		&i.Nonce,
		&i.Ciphertext,
		&i.ValueHash,
		&i.CreatedAt,
	)
	return i, err
}

const getManagedAccount = `-- name: GetManagedAccount :one
SELECT id, enterprise_id, host_id, username, privilege_level, credential_id, allowed_protocols, status, version, created_at, updated_at FROM managed_accounts WHERE id = $1 AND enterprise_id = $2
`

type GetManagedAccountParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetManagedAccount(ctx context.Context, arg GetManagedAccountParams) (ManagedAccount, error) {
	row := q.db.QueryRow(ctx, getManagedAccount, arg.ID, arg.EnterpriseID)
	var i ManagedAccount
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.Username,
		&i.PrivilegeLevel,
		&i.CredentialID,
		&i.AllowedProtocols,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecret = `-- name: GetSecret :one
SELECT s.id, s.enterprise_id, s.name, s.type, s.description, s.status, s.current_version, s.last_accessed_at, s.version, s.created_by, s.created_at, s.updated_at, (SELECT count(*) FROM credentials c WHERE c.secret_id = s.id AND c.status = 'active')::bigint AS reference_count
FROM secrets s WHERE s.id = $1 AND s.enterprise_id = $2
`

type GetSecretParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

type GetSecretRow struct {
	ID             uuid.UUID          `json:"id"`
	EnterpriseID   uuid.UUID          `json:"enterprise_id"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	Description    string             `json:"description"`
	Status         string             `json:"status"`
	CurrentVersion int32              `json:"current_version"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	Version        int64              `json:"version"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ReferenceCount int64              `json:"reference_count"`
}

func (q *Queries) GetSecret(ctx context.Context, arg GetSecretParams) (GetSecretRow, error) {
	row := q.db.QueryRow(ctx, getSecret, arg.ID, arg.EnterpriseID)
	var i GetSecretRow
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.CurrentVersion,
		&i.LastAccessedAt,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferenceCount,
	)
	return i, err
}

const getSecretVersionByID = `-- name: GetSecretVersionByID :one
SELECT id, secret_id, enterprise_id, version, provider, key_id, key_version, wrapped_dek, wrap_nonce, nonce, ciphertext, value_hash, created_at FROM secret_versions WHERE id = $1 AND enterprise_id = $2
`

type GetSecretVersionByIDParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetSecretVersionByID(ctx context.Context, arg GetSecretVersionByIDParams) (SecretVersion, error) {
	row := q.db.QueryRow(ctx, getSecretVersionByID, arg.ID, arg.EnterpriseID)
	var i SecretVersion
	err := row.Scan(
		&i.ID,
		&i.SecretID,
		&i.EnterpriseID,
		&i.Version,
		&i.Provider,
		&i.KeyID,
		&i.KeyVersion,
		&i.WrappedDek,
		&i.WrapNonce,
		&i.Nonce,
		&i.Ciphertext,
		&i.ValueHash,
		&i.CreatedAt,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, enterprise_id, name, protocol, username, secret_id, status, version, created_at, updated_at FROM credentials WHERE enterprise_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListCredentials(ctx context.Context, enterpriseID uuid.UUID) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentials, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.Name,
			&i.Protocol,
			&i.Username,
			&i.SecretID,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedAccounts = `-- name: ListManagedAccounts :many
SELECT id, enterprise_id, host_id, username, privilege_level, credential_id, allowed_protocols, status, version, created_at, updated_at FROM managed_accounts WHERE enterprise_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListManagedAccounts(ctx context.Context, enterpriseID uuid.UUID) ([]ManagedAccount, error) {
	rows, err := q.db.Query(ctx, listManagedAccounts, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagedAccount{}
	for rows.Next() {
		var i ManagedAccount
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.HostID,
			&i.Username,
			&i.PrivilegeLevel,
			&i.CredentialID,
			&i.AllowedProtocols,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
SELECT s.id, s.enterprise_id, s.name, s.type, s.description, s.status, s.current_version, s.last_accessed_at, s.version, s.created_by, s.created_at, s.updated_at, (SELECT count(*) FROM credentials c WHERE c.secret_id = s.id AND c.status = 'active')::bigint AS reference_count
FROM secrets s WHERE s.enterprise_id = $1 ORDER BY s.created_at, s.id
`

type ListSecretsRow struct {
	ID             uuid.UUID          `json:"id"`
	EnterpriseID   uuid.UUID          `json:"enterprise_id"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	Description    string             `json:"description"`
	Status         string             `json:"status"`
	CurrentVersion int32              `json:"current_version"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	Version        int64              `json:"version"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ReferenceCount int64              `json:"reference_count"`
}

func (q *Queries) ListSecrets(ctx context.Context, enterpriseID uuid.UUID) ([]ListSecretsRow, error) {
	rows, err := q.db.Query(ctx, listSecrets, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsRow{}
	for rows.Next() {
		var i ListSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.Status,
			&i.CurrentVersion,
			&i.LastAccessedAt,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReferenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSecretAccessed = `-- name: MarkSecretAccessed :exec
UPDATE secrets SET last_accessed_at = now(), updated_at = now() WHERE id = $1 AND enterprise_id = $2
`

type MarkSecretAccessedParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) MarkSecretAccessed(ctx context.Context, arg MarkSecretAccessedParams) error {
	_, err := q.db.Exec(ctx, markSecretAccessed, arg.ID, arg.EnterpriseID)
	return err
}

const renewCredentialLease = `-- name: RenewCredentialLease :one
UPDATE credential_leases AS lease SET
  expires_at = $1
FROM credentials AS credential
WHERE lease.id = $2
  AND lease.enterprise_id = $3
  AND lease.status = 'active'
  AND lease.expires_at > now()
  AND lease.recipient_type = $4
  AND lease.recipient_id = $5
  AND credential.id = lease.credential_id
  AND credential.enterprise_id = lease.enterprise_id
  AND credential.status = 'active'
  AND credential.version = $6
RETURNING lease.id, lease.enterprise_id, lease.credential_id, lease.secret_version_id, lease.operation_ref, lease.target_resource_type, lease.target_resource_id, lease.recipient_type, lease.recipient_id, lease.protocol, lease.status, lease.expires_at, lease.consumed_at, lease.created_at
`

type RenewCredentialLeaseParams struct {
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ID                uuid.UUID          `json:"id"`
	EnterpriseID      uuid.UUID          `json:"enterprise_id"`
	RecipientType     string             `json:"recipient_type"`
	RecipientID       string             `json:"recipient_id"`
	CredentialVersion int64              `json:"credential_version"`
}

func (q *Queries) RenewCredentialLease(ctx context.Context, arg RenewCredentialLeaseParams) (CredentialLease, error) {
	row := q.db.QueryRow(ctx, renewCredentialLease,
		arg.ExpiresAt,
		arg.ID,
		arg.EnterpriseID,
		arg.RecipientType,
		arg.RecipientID,
		arg.CredentialVersion,
	)
	var i CredentialLease
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CredentialID,
		&i.SecretVersionID,
		&i.OperationRef,
		&i.TargetResourceType,
		&i.TargetResourceID,
		&i.RecipientType,
		&i.RecipientID,
		&i.Protocol,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeCredentialLease = `-- name: RevokeCredentialLease :exec
UPDATE credential_leases SET status = 'revoked'
WHERE id = $1 AND enterprise_id = $2 AND status = 'active'
`

type RevokeCredentialLeaseParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) RevokeCredentialLease(ctx context.Context, arg RevokeCredentialLeaseParams) error {
	_, err := q.db.Exec(ctx, revokeCredentialLease, arg.ID, arg.EnterpriseID)
	return err
}

const revokeCredentialLeasesByCredential = `-- name: RevokeCredentialLeasesByCredential :execrows
UPDATE credential_leases SET status = 'revoked'
WHERE credential_id = $1 AND enterprise_id = $2 AND status = 'active'
`

type RevokeCredentialLeasesByCredentialParams struct {
	CredentialID uuid.UUID `json:"credential_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) RevokeCredentialLeasesByCredential(ctx context.Context, arg RevokeCredentialLeasesByCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeCredentialLeasesByCredential, arg.CredentialID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeCredentialLeasesBySecret = `-- name: RevokeCredentialLeasesBySecret :exec
UPDATE credential_leases AS lease SET status = 'revoked' WHERE lease.enterprise_id = $1 AND lease.status = 'active'
AND lease.credential_id IN (SELECT credential.id FROM credentials AS credential WHERE credential.secret_id = $2 AND credential.enterprise_id = $1)
`

type RevokeCredentialLeasesBySecretParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	SecretID     uuid.UUID `json:"secret_id"`
}

func (q *Queries) RevokeCredentialLeasesBySecret(ctx context.Context, arg RevokeCredentialLeasesBySecretParams) error {
	_, err := q.db.Exec(ctx, revokeCredentialLeasesBySecret, arg.EnterpriseID, arg.SecretID)
	return err
}

const updateCredential = `-- name: UpdateCredential :one
UPDATE credentials SET
  name = COALESCE($4, name), username = COALESCE($5, username),
  secret_id = COALESCE($6, secret_id), status = COALESCE($7, status),
  version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND version = $3 RETURNING id, enterprise_id, name, protocol, username, secret_id, status, version, created_at, updated_at
`

type UpdateCredentialParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	Version      int64         `json:"version"`
	Name         pgtype.Text   `json:"name"`
	Username     pgtype.Text   `json:"username"`
	SecretID     uuid.NullUUID `json:"secret_id"`
	Status       pgtype.Text   `json:"status"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, updateCredential,
		arg.ID,
		arg.EnterpriseID,
		arg.Version,
		arg.Name,
		arg.Username,
		arg.SecretID,
		arg.Status,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Protocol,
		&i.Username,
		&i.SecretID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateManagedAccount = `-- name: UpdateManagedAccount :one
UPDATE managed_accounts SET
  username = COALESCE($4, username), privilege_level = COALESCE($5, privilege_level),
  credential_id = COALESCE($6, credential_id), allowed_protocols = COALESCE($7, allowed_protocols),
  status = COALESCE($8, status), version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND version = $3 RETURNING id, enterprise_id, host_id, username, privilege_level, credential_id, allowed_protocols, status, version, created_at, updated_at
`

type UpdateManagedAccountParams struct {
	ID               uuid.UUID     `json:"id"`
	EnterpriseID     uuid.UUID     `json:"enterprise_id"`
	Version          int64         `json:"version"`
	Username         pgtype.Text   `json:"username"`
	PrivilegeLevel   pgtype.Text   `json:"privilege_level"`
	CredentialID     uuid.NullUUID `json:"credential_id"`
	AllowedProtocols []string      `json:"allowed_protocols"`
	Status           pgtype.Text   `json:"status"`
}

func (q *Queries) UpdateManagedAccount(ctx context.Context, arg UpdateManagedAccountParams) (ManagedAccount, error) {
	row := q.db.QueryRow(ctx, updateManagedAccount,
		arg.ID,
		arg.EnterpriseID,
		arg.Version,
		arg.Username,
		arg.PrivilegeLevel,
		arg.CredentialID,
		arg.AllowedProtocols,
		arg.Status,
	)
	var i ManagedAccount
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.Username,
		&i.PrivilegeLevel,
		&i.CredentialID,
		&i.AllowedProtocols,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSecretMetadata = `-- name: UpdateSecretMetadata :one
UPDATE secrets SET
  name = COALESCE($4, name),
  description = COALESCE($5, description),
  status = COALESCE($6, status),
  version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND version = $3 RETURNING id, enterprise_id, name, type, description, status, current_version, last_accessed_at, version, created_by, created_at, updated_at
`

type UpdateSecretMetadataParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	Version      int64       `json:"version"`
	Name         pgtype.Text `json:"name"`
	Description  pgtype.Text `json:"description"`
	Status       pgtype.Text `json:"status"`
}

func (q *Queries) UpdateSecretMetadata(ctx context.Context, arg UpdateSecretMetadataParams) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecretMetadata,
		arg.ID,
		arg.EnterpriseID,
		arg.Version,
		arg.Name,
		arg.Description,
		arg.Status,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.CurrentVersion,
		&i.LastAccessedAt,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
