// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telemetry_tenant.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEnterpriseTelemetryTables = `-- name: GetEnterpriseTelemetryTables :one
SELECT enterprise_id, schema_version, status, ready_at, last_error, updated_at
FROM enterprise_telemetry_tables
WHERE enterprise_id = $1
`

func (q *Queries) GetEnterpriseTelemetryTables(ctx context.Context, enterpriseID uuid.UUID) (EnterpriseTelemetryTable, error) {
	row := q.db.QueryRow(ctx, getEnterpriseTelemetryTables, enterpriseID)
	var i EnterpriseTelemetryTable
	err := row.Scan(
		&i.EnterpriseID,
		&i.SchemaVersion,
		&i.Status,
		&i.ReadyAt,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const markEnterpriseTelemetryDeleting = `-- name: MarkEnterpriseTelemetryDeleting :exec
UPDATE enterprise_telemetry_tables SET status = 'deleting', updated_at = now() WHERE enterprise_id = $1
`

func (q *Queries) MarkEnterpriseTelemetryDeleting(ctx context.Context, enterpriseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEnterpriseTelemetryDeleting, enterpriseID)
	return err
}

const upsertEnterpriseTelemetryTables = `-- name: UpsertEnterpriseTelemetryTables :exec
INSERT INTO enterprise_telemetry_tables (enterprise_id, schema_version, status, ready_at, last_error, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (enterprise_id) DO UPDATE SET schema_version = EXCLUDED.schema_version, status = EXCLUDED.status, ready_at = EXCLUDED.ready_at, last_error = EXCLUDED.last_error, updated_at = now()
`

type UpsertEnterpriseTelemetryTablesParams struct {
	EnterpriseID  uuid.UUID          `json:"enterprise_id"`
	SchemaVersion int32              `json:"schema_version"`
	Status        string             `json:"status"`
	ReadyAt       pgtype.Timestamptz `json:"ready_at"`
	LastError     pgtype.Text        `json:"last_error"`
}

func (q *Queries) UpsertEnterpriseTelemetryTables(ctx context.Context, arg UpsertEnterpriseTelemetryTablesParams) error {
	_, err := q.db.Exec(ctx, upsertEnterpriseTelemetryTables,
		arg.EnterpriseID,
		arg.SchemaVersion,
		arg.Status,
		arg.ReadyAt,
		arg.LastError,
	)
	return err
}
