// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telemetry_control.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyCollectorOperationFailure = `-- name: ApplyCollectorOperationFailure :execrows
UPDATE collector_instances SET status = $3, version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2
`

type ApplyCollectorOperationFailureParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Status       string    `json:"status"`
}

func (q *Queries) ApplyCollectorOperationFailure(ctx context.Context, arg ApplyCollectorOperationFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyCollectorOperationFailure, arg.ID, arg.EnterpriseID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyCollectorOperationSuccess = `-- name: ApplyCollectorOperationSuccess :execrows
UPDATE collector_instances SET
  status = CASE WHEN $3 = 'uninstall' THEN 'uninstalled' ELSE 'converged' END,
  effective_revision = CASE WHEN $3 = 'uninstall' THEN effective_revision ELSE desired_revision END,
  version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2
`

type ApplyCollectorOperationSuccessParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	Column3      interface{} `json:"column_3"`
}

func (q *Queries) ApplyCollectorOperationSuccess(ctx context.Context, arg ApplyCollectorOperationSuccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyCollectorOperationSuccess, arg.ID, arg.EnterpriseID, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimTelemetryCollectorOperation = `-- name: ClaimTelemetryCollectorOperation :one
UPDATE telemetry_collector_operations SET
  status = 'running', lease_owner = $2, fence = fence + 1,
  lease_expires_at = now() + interval '2 minutes', attempts = attempts + 1, updated_at = now()
WHERE id = $1 AND status = 'queued' AND expires_at > now()
RETURNING id, enterprise_id, collector_id, pending_action_id, operation, executor_kind, status, plan, plan_hash, lease_owner, fence, lease_expires_at, result_hash, error_code, attempts, expires_at, created_at, updated_at, completed_at
`

type ClaimTelemetryCollectorOperationParams struct {
	ID         uuid.UUID   `json:"id"`
	LeaseOwner pgtype.Text `json:"lease_owner"`
}

func (q *Queries) ClaimTelemetryCollectorOperation(ctx context.Context, arg ClaimTelemetryCollectorOperationParams) (TelemetryCollectorOperation, error) {
	row := q.db.QueryRow(ctx, claimTelemetryCollectorOperation, arg.ID, arg.LeaseOwner)
	var i TelemetryCollectorOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CollectorID,
		&i.PendingActionID,
		&i.Operation,
		&i.ExecutorKind,
		&i.Status,
		&i.Plan,
		&i.PlanHash,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ResultHash,
		&i.ErrorCode,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const claimTelemetryCollectorOperations = `-- name: ClaimTelemetryCollectorOperations :many
WITH claimed AS (
  SELECT id FROM telemetry_collector_operations
  WHERE status = 'queued' AND expires_at > now()
  ORDER BY created_at, id
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE telemetry_collector_operations AS operation SET
  status = 'running', lease_owner = $2, fence = fence + 1,
  lease_expires_at = now() + interval '2 minutes', attempts = attempts + 1, updated_at = now()
FROM claimed WHERE operation.id = claimed.id
RETURNING operation.id, operation.enterprise_id, operation.collector_id, operation.pending_action_id, operation.operation, operation.executor_kind, operation.status, operation.plan, operation.plan_hash, operation.lease_owner, operation.fence, operation.lease_expires_at, operation.result_hash, operation.error_code, operation.attempts, operation.expires_at, operation.created_at, operation.updated_at, operation.completed_at
`

type ClaimTelemetryCollectorOperationsParams struct {
	Limit      int32       `json:"limit"`
	LeaseOwner pgtype.Text `json:"lease_owner"`
}

func (q *Queries) ClaimTelemetryCollectorOperations(ctx context.Context, arg ClaimTelemetryCollectorOperationsParams) ([]TelemetryCollectorOperation, error) {
	rows, err := q.db.Query(ctx, claimTelemetryCollectorOperations, arg.Limit, arg.LeaseOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelemetryCollectorOperation{}
	for rows.Next() {
		var i TelemetryCollectorOperation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.CollectorID,
			&i.PendingActionID,
			&i.Operation,
			&i.ExecutorKind,
			&i.Status,
			&i.Plan,
			&i.PlanHash,
			&i.LeaseOwner,
			&i.Fence,
			&i.LeaseExpiresAt,
			&i.ResultHash,
			&i.ErrorCode,
			&i.Attempts,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimTelemetryDLQReplay = `-- name: ClaimTelemetryDLQReplay :one
UPDATE telemetry_dlq_records SET status = 'replaying'
WHERE id = $1 AND status IN ('pending','failed')
RETURNING id, signal, topic, partition, source_offset, dlq_topic, dlq_partition, dlq_offset, record_hash, error_code, status, first_seen_at, replayed_at
`

func (q *Queries) ClaimTelemetryDLQReplay(ctx context.Context, id uuid.UUID) (TelemetryDlqRecord, error) {
	row := q.db.QueryRow(ctx, claimTelemetryDLQReplay, id)
	var i TelemetryDlqRecord
	err := row.Scan(
		&i.ID,
		&i.Signal,
		&i.Topic,
		&i.Partition,
		&i.SourceOffset,
		&i.DlqTopic,
		&i.DlqPartition,
		&i.DlqOffset,
		&i.RecordHash,
		&i.ErrorCode,
		&i.Status,
		&i.FirstSeenAt,
		&i.ReplayedAt,
	)
	return i, err
}

const completeTelemetryRouteTest = `-- name: CompleteTelemetryRouteTest :one
UPDATE telemetry_route_tests SET
  status = $3,
  result_code = $4,
  result_hash = $5,
  completed_at = now()
WHERE id = $1 AND enterprise_id = $2 AND status = 'queued'
RETURNING id, enterprise_id, route_id, status, result_code, result_hash, expires_at, created_at, completed_at
`

type CompleteTelemetryRouteTestParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	Status       string      `json:"status"`
	ResultCode   pgtype.Text `json:"result_code"`
	ResultHash   []byte      `json:"result_hash"`
}

func (q *Queries) CompleteTelemetryRouteTest(ctx context.Context, arg CompleteTelemetryRouteTestParams) (TelemetryRouteTest, error) {
	row := q.db.QueryRow(ctx, completeTelemetryRouteTest,
		arg.ID,
		arg.EnterpriseID,
		arg.Status,
		arg.ResultCode,
		arg.ResultHash,
	)
	var i TelemetryRouteTest
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.RouteID,
		&i.Status,
		&i.ResultCode,
		&i.ResultHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const confirmKubernetesNodeHostBinding = `-- name: ConfirmKubernetesNodeHostBinding :one
UPDATE kubernetes_node_host_bindings SET
  host_id = $3, matched_by = 'manual', status = 'verified', version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND version = $4 AND evidence_hash = $5
	AND status = 'proposed'
RETURNING id, enterprise_id, kubernetes_cluster_id, node_uid, node_name, host_id, matched_by, evidence, evidence_hash, confidence, status, version, created_at, updated_at
`

type ConfirmKubernetesNodeHostBindingParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	HostID       uuid.NullUUID `json:"host_id"`
	Version      int64         `json:"version"`
	EvidenceHash []byte        `json:"evidence_hash"`
}

func (q *Queries) ConfirmKubernetesNodeHostBinding(ctx context.Context, arg ConfirmKubernetesNodeHostBindingParams) (KubernetesNodeHostBinding, error) {
	row := q.db.QueryRow(ctx, confirmKubernetesNodeHostBinding,
		arg.ID,
		arg.EnterpriseID,
		arg.HostID,
		arg.Version,
		arg.EvidenceHash,
	)
	var i KubernetesNodeHostBinding
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.KubernetesClusterID,
		&i.NodeUid,
		&i.NodeName,
		&i.HostID,
		&i.MatchedBy,
		&i.Evidence,
		&i.EvidenceHash,
		&i.Confidence,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeTelemetryEnrollmentToken = `-- name: ConsumeTelemetryEnrollmentToken :one
UPDATE telemetry_enrollment_tokens SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING id, collector_id, token_hash, expires_at, consumed_at, created_at
`

func (q *Queries) ConsumeTelemetryEnrollmentToken(ctx context.Context, id uuid.UUID) (TelemetryEnrollmentToken, error) {
	row := q.db.QueryRow(ctx, consumeTelemetryEnrollmentToken, id)
	var i TelemetryEnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCollectionClaim = `-- name: CreateCollectionClaim :one
INSERT INTO collection_claims (
  id, enterprise_id, physical_resource_ref, collector_id, profile_id,
  claim_type, signal, selector, selector_hash, ownership, status
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'primary','active') RETURNING id, enterprise_id, physical_resource_ref, collector_id, profile_id, claim_type, signal, selector, selector_hash, ownership, status, primary_claim_id, rollback_plan, expires_at, created_at
`

type CreateCollectionClaimParams struct {
	ID                  uuid.UUID     `json:"id"`
	EnterpriseID        uuid.UUID     `json:"enterprise_id"`
	PhysicalResourceRef string        `json:"physical_resource_ref"`
	CollectorID         uuid.UUID     `json:"collector_id"`
	ProfileID           uuid.NullUUID `json:"profile_id"`
	ClaimType           string        `json:"claim_type"`
	Signal              string        `json:"signal"`
	Selector            []byte        `json:"selector"`
	SelectorHash        []byte        `json:"selector_hash"`
}

func (q *Queries) CreateCollectionClaim(ctx context.Context, arg CreateCollectionClaimParams) (CollectionClaim, error) {
	row := q.db.QueryRow(ctx, createCollectionClaim,
		arg.ID,
		arg.EnterpriseID,
		arg.PhysicalResourceRef,
		arg.CollectorID,
		arg.ProfileID,
		arg.ClaimType,
		arg.Signal,
		arg.Selector,
		arg.SelectorHash,
	)
	var i CollectionClaim
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.PhysicalResourceRef,
		&i.CollectorID,
		&i.ProfileID,
		&i.ClaimType,
		&i.Signal,
		&i.Selector,
		&i.SelectorHash,
		&i.Ownership,
		&i.Status,
		&i.PrimaryClaimID,
		&i.RollbackPlan,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCollectorConfigRevision = `-- name: CreateCollectorConfigRevision :one
INSERT INTO collector_config_revisions (
  id, collector_id, revision, profile_ids, rendered_config, config_hash, status
) VALUES ($1,$2,$3,$4,$5,$6,'prepared') RETURNING id, collector_id, revision, profile_ids, rendered_config, config_hash, status, failure_code, rollback_revision, created_at, applied_at
`

type CreateCollectorConfigRevisionParams struct {
	ID             uuid.UUID   `json:"id"`
	CollectorID    uuid.UUID   `json:"collector_id"`
	Revision       int64       `json:"revision"`
	ProfileIds     []uuid.UUID `json:"profile_ids"`
	RenderedConfig []byte      `json:"rendered_config"`
	ConfigHash     []byte      `json:"config_hash"`
}

func (q *Queries) CreateCollectorConfigRevision(ctx context.Context, arg CreateCollectorConfigRevisionParams) (CollectorConfigRevision, error) {
	row := q.db.QueryRow(ctx, createCollectorConfigRevision,
		arg.ID,
		arg.CollectorID,
		arg.Revision,
		arg.ProfileIds,
		arg.RenderedConfig,
		arg.ConfigHash,
	)
	var i CollectorConfigRevision
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.Revision,
		&i.ProfileIds,
		&i.RenderedConfig,
		&i.ConfigHash,
		&i.Status,
		&i.FailureCode,
		&i.RollbackRevision,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const createMigrationCollectionClaim = `-- name: CreateMigrationCollectionClaim :one
INSERT INTO collection_claims (
  id, enterprise_id, physical_resource_ref, collector_id, profile_id,
  claim_type, signal, selector, selector_hash, ownership, status,
  primary_claim_id, rollback_plan, expires_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'migration','active',$10,$11,$12) RETURNING id, enterprise_id, physical_resource_ref, collector_id, profile_id, claim_type, signal, selector, selector_hash, ownership, status, primary_claim_id, rollback_plan, expires_at, created_at
`

type CreateMigrationCollectionClaimParams struct {
	ID                  uuid.UUID          `json:"id"`
	EnterpriseID        uuid.UUID          `json:"enterprise_id"`
	PhysicalResourceRef string             `json:"physical_resource_ref"`
	CollectorID         uuid.UUID          `json:"collector_id"`
	ProfileID           uuid.NullUUID      `json:"profile_id"`
	ClaimType           string             `json:"claim_type"`
	Signal              string             `json:"signal"`
	Selector            []byte             `json:"selector"`
	SelectorHash        []byte             `json:"selector_hash"`
	PrimaryClaimID      uuid.NullUUID      `json:"primary_claim_id"`
	RollbackPlan        []byte             `json:"rollback_plan"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMigrationCollectionClaim(ctx context.Context, arg CreateMigrationCollectionClaimParams) (CollectionClaim, error) {
	row := q.db.QueryRow(ctx, createMigrationCollectionClaim,
		arg.ID,
		arg.EnterpriseID,
		arg.PhysicalResourceRef,
		arg.CollectorID,
		arg.ProfileID,
		arg.ClaimType,
		arg.Signal,
		arg.Selector,
		arg.SelectorHash,
		arg.PrimaryClaimID,
		arg.RollbackPlan,
		arg.ExpiresAt,
	)
	var i CollectionClaim
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.PhysicalResourceRef,
		&i.CollectorID,
		&i.ProfileID,
		&i.ClaimType,
		&i.Signal,
		&i.Selector,
		&i.SelectorHash,
		&i.Ownership,
		&i.Status,
		&i.PrimaryClaimID,
		&i.RollbackPlan,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTelemetryCertificate = `-- name: CreateTelemetryCertificate :one
INSERT INTO telemetry_certificates (
  id, collector_id, serial_number, uri_san, csr_hash, certificate_hash,
  certificate_request_name, issuer_generation, not_before, not_after
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, collector_id, serial_number, uri_san, csr_hash, certificate_hash, certificate_request_name, issuer_generation, not_before, not_after, revoked_at, revoke_reason, created_at
`

type CreateTelemetryCertificateParams struct {
	ID                     uuid.UUID          `json:"id"`
	CollectorID            uuid.UUID          `json:"collector_id"`
	SerialNumber           string             `json:"serial_number"`
	UriSan                 string             `json:"uri_san"`
	CsrHash                []byte             `json:"csr_hash"`
	CertificateHash        []byte             `json:"certificate_hash"`
	CertificateRequestName string             `json:"certificate_request_name"`
	IssuerGeneration       int32              `json:"issuer_generation"`
	NotBefore              pgtype.Timestamptz `json:"not_before"`
	NotAfter               pgtype.Timestamptz `json:"not_after"`
}

func (q *Queries) CreateTelemetryCertificate(ctx context.Context, arg CreateTelemetryCertificateParams) (TelemetryCertificate, error) {
	row := q.db.QueryRow(ctx, createTelemetryCertificate,
		arg.ID,
		arg.CollectorID,
		arg.SerialNumber,
		arg.UriSan,
		arg.CsrHash,
		arg.CertificateHash,
		arg.CertificateRequestName,
		arg.IssuerGeneration,
		arg.NotBefore,
		arg.NotAfter,
	)
	var i TelemetryCertificate
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.SerialNumber,
		&i.UriSan,
		&i.CsrHash,
		&i.CertificateHash,
		&i.CertificateRequestName,
		&i.IssuerGeneration,
		&i.NotBefore,
		&i.NotAfter,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
	)
	return i, err
}

const createTelemetryCollectorOperation = `-- name: CreateTelemetryCollectorOperation :one
INSERT INTO telemetry_collector_operations (
  id, enterprise_id, collector_id, pending_action_id, operation, executor_kind,
  plan, plan_hash, expires_at
) VALUES ($1,$2,$3,$4,$5,'direct',$6,$7,$8)
RETURNING id, enterprise_id, collector_id, pending_action_id, operation, executor_kind, status, plan, plan_hash, lease_owner, fence, lease_expires_at, result_hash, error_code, attempts, expires_at, created_at, updated_at, completed_at
`

type CreateTelemetryCollectorOperationParams struct {
	ID              uuid.UUID          `json:"id"`
	EnterpriseID    uuid.UUID          `json:"enterprise_id"`
	CollectorID     uuid.UUID          `json:"collector_id"`
	PendingActionID uuid.UUID          `json:"pending_action_id"`
	Operation       string             `json:"operation"`
	Plan            []byte             `json:"plan"`
	PlanHash        []byte             `json:"plan_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTelemetryCollectorOperation(ctx context.Context, arg CreateTelemetryCollectorOperationParams) (TelemetryCollectorOperation, error) {
	row := q.db.QueryRow(ctx, createTelemetryCollectorOperation,
		arg.ID,
		arg.EnterpriseID,
		arg.CollectorID,
		arg.PendingActionID,
		arg.Operation,
		arg.Plan,
		arg.PlanHash,
		arg.ExpiresAt,
	)
	var i TelemetryCollectorOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CollectorID,
		&i.PendingActionID,
		&i.Operation,
		&i.ExecutorKind,
		&i.Status,
		&i.Plan,
		&i.PlanHash,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ResultHash,
		&i.ErrorCode,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createTelemetryEnrollmentToken = `-- name: CreateTelemetryEnrollmentToken :one
INSERT INTO telemetry_enrollment_tokens (id, collector_id, token_hash, expires_at)
VALUES ($1,$2,$3,$4) RETURNING id, collector_id, token_hash, expires_at, consumed_at, created_at
`

type CreateTelemetryEnrollmentTokenParams struct {
	ID          uuid.UUID          `json:"id"`
	CollectorID uuid.UUID          `json:"collector_id"`
	TokenHash   []byte             `json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTelemetryEnrollmentToken(ctx context.Context, arg CreateTelemetryEnrollmentTokenParams) (TelemetryEnrollmentToken, error) {
	row := q.db.QueryRow(ctx, createTelemetryEnrollmentToken,
		arg.ID,
		arg.CollectorID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i TelemetryEnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTelemetryRouteTest = `-- name: CreateTelemetryRouteTest :one
INSERT INTO telemetry_route_tests (id, enterprise_id, route_id, status, expires_at)
VALUES ($1,$2,$3,'queued',$4) RETURNING id, enterprise_id, route_id, status, result_code, result_hash, expires_at, created_at, completed_at
`

type CreateTelemetryRouteTestParams struct {
	ID           uuid.UUID          `json:"id"`
	EnterpriseID uuid.UUID          `json:"enterprise_id"`
	RouteID      uuid.UUID          `json:"route_id"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTelemetryRouteTest(ctx context.Context, arg CreateTelemetryRouteTestParams) (TelemetryRouteTest, error) {
	row := q.db.QueryRow(ctx, createTelemetryRouteTest,
		arg.ID,
		arg.EnterpriseID,
		arg.RouteID,
		arg.ExpiresAt,
	)
	var i TelemetryRouteTest
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.RouteID,
		&i.Status,
		&i.ResultCode,
		&i.ResultHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const ensureTelemetryRetentionPolicy = `-- name: EnsureTelemetryRetentionPolicy :one
INSERT INTO telemetry_retention_policies (enterprise_id) VALUES ($1)
ON CONFLICT (enterprise_id) DO UPDATE SET enterprise_id = EXCLUDED.enterprise_id
RETURNING enterprise_id, metrics_days, logs_days, traces_days, max_rows, max_scan_bytes, max_execution_ms, version, updated_at
`

func (q *Queries) EnsureTelemetryRetentionPolicy(ctx context.Context, enterpriseID uuid.UUID) (TelemetryRetentionPolicy, error) {
	row := q.db.QueryRow(ctx, ensureTelemetryRetentionPolicy, enterpriseID)
	var i TelemetryRetentionPolicy
	err := row.Scan(
		&i.EnterpriseID,
		&i.MetricsDays,
		&i.LogsDays,
		&i.TracesDays,
		&i.MaxRows,
		&i.MaxScanBytes,
		&i.MaxExecutionMs,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const expireCollectionClaimMigrations = `-- name: ExpireCollectionClaimMigrations :execrows
UPDATE collection_claims SET status = 'expired'
WHERE ownership = 'migration' AND status = 'active' AND expires_at <= now()
`

func (q *Queries) ExpireCollectionClaimMigrations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireCollectionClaimMigrations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireTelemetryCollectorOperations = `-- name: ExpireTelemetryCollectorOperations :execrows
UPDATE telemetry_collector_operations SET status = 'expired', error_code = 'COLLECTOR_OPERATION_EXPIRED', completed_at = now(), updated_at = now()
WHERE status = 'queued' AND expires_at <= now()
`

func (q *Queries) ExpireTelemetryCollectorOperations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireTelemetryCollectorOperations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeCollectorClaimMigrations = `-- name: FinalizeCollectorClaimMigrations :execrows
WITH migrations AS (
  SELECT claims.id, claims.primary_claim_id FROM collection_claims AS claims
  WHERE claims.enterprise_id = $1 AND claims.collector_id = $2 AND claims.ownership = 'migration' AND claims.status = 'active' AND claims.expires_at > now()
), released AS (
  UPDATE collection_claims AS primary_claim SET status = 'released'
  WHERE primary_claim.id IN (SELECT migration.primary_claim_id FROM migrations AS migration) AND primary_claim.status = 'active'
)
UPDATE collection_claims AS migration_claim SET ownership = 'primary', primary_claim_id = NULL, rollback_plan = NULL, expires_at = NULL
WHERE migration_claim.id IN (SELECT migration.id FROM migrations AS migration)
`

type FinalizeCollectorClaimMigrationsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	CollectorID  uuid.UUID `json:"collector_id"`
}

func (q *Queries) FinalizeCollectorClaimMigrations(ctx context.Context, arg FinalizeCollectorClaimMigrationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeCollectorClaimMigrations, arg.EnterpriseID, arg.CollectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishTelemetryCollectorOperation = `-- name: FinishTelemetryCollectorOperation :one
UPDATE telemetry_collector_operations SET status = $4, result_hash = $5, error_code = $6,
  lease_owner = NULL, lease_expires_at = NULL, completed_at = now(), updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND fence = $3 AND status IN ('running','result_unknown')
RETURNING id, enterprise_id, collector_id, pending_action_id, operation, executor_kind, status, plan, plan_hash, lease_owner, fence, lease_expires_at, result_hash, error_code, attempts, expires_at, created_at, updated_at, completed_at
`

type FinishTelemetryCollectorOperationParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	Fence        int64       `json:"fence"`
	Status       string      `json:"status"`
	ResultHash   []byte      `json:"result_hash"`
	ErrorCode    pgtype.Text `json:"error_code"`
}

func (q *Queries) FinishTelemetryCollectorOperation(ctx context.Context, arg FinishTelemetryCollectorOperationParams) (TelemetryCollectorOperation, error) {
	row := q.db.QueryRow(ctx, finishTelemetryCollectorOperation,
		arg.ID,
		arg.EnterpriseID,
		arg.Fence,
		arg.Status,
		arg.ResultHash,
		arg.ErrorCode,
	)
	var i TelemetryCollectorOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CollectorID,
		&i.PendingActionID,
		&i.Operation,
		&i.ExecutorKind,
		&i.Status,
		&i.Plan,
		&i.PlanHash,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ResultHash,
		&i.ErrorCode,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getActivePrimaryCollectionClaim = `-- name: GetActivePrimaryCollectionClaim :one
SELECT id, enterprise_id, physical_resource_ref, collector_id, profile_id, claim_type, signal, selector, selector_hash, ownership, status, primary_claim_id, rollback_plan, expires_at, created_at FROM collection_claims
WHERE enterprise_id = $1 AND physical_resource_ref = $2 AND claim_type = $3
  AND selector_hash = $4 AND ownership = 'primary' AND status = 'active'
FOR UPDATE
`

type GetActivePrimaryCollectionClaimParams struct {
	EnterpriseID        uuid.UUID `json:"enterprise_id"`
	PhysicalResourceRef string    `json:"physical_resource_ref"`
	ClaimType           string    `json:"claim_type"`
	SelectorHash        []byte    `json:"selector_hash"`
}

func (q *Queries) GetActivePrimaryCollectionClaim(ctx context.Context, arg GetActivePrimaryCollectionClaimParams) (CollectionClaim, error) {
	row := q.db.QueryRow(ctx, getActivePrimaryCollectionClaim,
		arg.EnterpriseID,
		arg.PhysicalResourceRef,
		arg.ClaimType,
		arg.SelectorHash,
	)
	var i CollectionClaim
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.PhysicalResourceRef,
		&i.CollectorID,
		&i.ProfileID,
		&i.ClaimType,
		&i.Signal,
		&i.Selector,
		&i.SelectorHash,
		&i.Ownership,
		&i.Status,
		&i.PrimaryClaimID,
		&i.RollbackPlan,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCollectorForResource = `-- name: GetCollectorForResource :one
SELECT id, enterprise_id, resource_type, resource_id, distribution_version_id, platform, role, status, desired_revision, effective_revision, authorization_version, last_seen_at, version, created_at, updated_at FROM collector_instances WHERE enterprise_id = $1 AND resource_type = $2 AND resource_id = $3
`

type GetCollectorForResourceParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
}

func (q *Queries) GetCollectorForResource(ctx context.Context, arg GetCollectorForResourceParams) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, getCollectorForResource, arg.EnterpriseID, arg.ResourceType, arg.ResourceID)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ResourceType,
		&i.ResourceID,
		&i.DistributionVersionID,
		&i.Platform,
		&i.Role,
		&i.Status,
		&i.DesiredRevision,
		&i.EffectiveRevision,
		&i.AuthorizationVersion,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectorInstance = `-- name: GetCollectorInstance :one
SELECT id, enterprise_id, resource_type, resource_id, distribution_version_id, platform, role, status, desired_revision, effective_revision, authorization_version, last_seen_at, version, created_at, updated_at FROM collector_instances WHERE id = $1 AND enterprise_id = $2
`

type GetCollectorInstanceParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetCollectorInstance(ctx context.Context, arg GetCollectorInstanceParams) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, getCollectorInstance, arg.ID, arg.EnterpriseID)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ResourceType,
		&i.ResourceID,
		&i.DistributionVersionID,
		&i.Platform,
		&i.Role,
		&i.Status,
		&i.DesiredRevision,
		&i.EffectiveRevision,
		&i.AuthorizationVersion,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectorInstanceByID = `-- name: GetCollectorInstanceByID :one
SELECT id, enterprise_id, resource_type, resource_id, distribution_version_id, platform, role, status, desired_revision, effective_revision, authorization_version, last_seen_at, version, created_at, updated_at FROM collector_instances WHERE id = $1
`

func (q *Queries) GetCollectorInstanceByID(ctx context.Context, id uuid.UUID) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, getCollectorInstanceByID, id)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ResourceType,
		&i.ResourceID,
		&i.DistributionVersionID,
		&i.Platform,
		&i.Role,
		&i.Status,
		&i.DesiredRevision,
		&i.EffectiveRevision,
		&i.AuthorizationVersion,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKubernetesNodeHostBinding = `-- name: GetKubernetesNodeHostBinding :one
SELECT id, enterprise_id, kubernetes_cluster_id, node_uid, node_name, host_id, matched_by, evidence, evidence_hash, confidence, status, version, created_at, updated_at FROM kubernetes_node_host_bindings WHERE id = $1 AND enterprise_id = $2
`

type GetKubernetesNodeHostBindingParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetKubernetesNodeHostBinding(ctx context.Context, arg GetKubernetesNodeHostBindingParams) (KubernetesNodeHostBinding, error) {
	row := q.db.QueryRow(ctx, getKubernetesNodeHostBinding, arg.ID, arg.EnterpriseID)
	var i KubernetesNodeHostBinding
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.KubernetesClusterID,
		&i.NodeUid,
		&i.NodeName,
		&i.HostID,
		&i.MatchedBy,
		&i.Evidence,
		&i.EvidenceHash,
		&i.Confidence,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestCollectorOperation = `-- name: GetLatestCollectorOperation :one
SELECT id, enterprise_id, collector_id, pending_action_id, operation, executor_kind, status, plan, plan_hash, lease_owner, fence, lease_expires_at, result_hash, error_code, attempts, expires_at, created_at, updated_at, completed_at FROM telemetry_collector_operations
WHERE collector_id = $1 AND enterprise_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestCollectorOperationParams struct {
	CollectorID  uuid.UUID `json:"collector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetLatestCollectorOperation(ctx context.Context, arg GetLatestCollectorOperationParams) (TelemetryCollectorOperation, error) {
	row := q.db.QueryRow(ctx, getLatestCollectorOperation, arg.CollectorID, arg.EnterpriseID)
	var i TelemetryCollectorOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CollectorID,
		&i.PendingActionID,
		&i.Operation,
		&i.ExecutorKind,
		&i.Status,
		&i.Plan,
		&i.PlanHash,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ResultHash,
		&i.ErrorCode,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTelemetryCollectorIdentity = `-- name: GetTelemetryCollectorIdentity :one
SELECT id, enterprise_id, resource_type, resource_id, distribution_version_id, platform, role, status, desired_revision, effective_revision, authorization_version, last_seen_at, version, created_at, updated_at FROM collector_instances WHERE id = $1 AND status NOT IN ('uninstalled','uninstalling')
`

func (q *Queries) GetTelemetryCollectorIdentity(ctx context.Context, id uuid.UUID) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, getTelemetryCollectorIdentity, id)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ResourceType,
		&i.ResourceID,
		&i.DistributionVersionID,
		&i.Platform,
		&i.Role,
		&i.Status,
		&i.DesiredRevision,
		&i.EffectiveRevision,
		&i.AuthorizationVersion,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTelemetryCollectorIdentityBySerial = `-- name: GetTelemetryCollectorIdentityBySerial :one
SELECT ci.id, ci.enterprise_id, ci.resource_type, ci.resource_id, ci.distribution_version_id, ci.platform, ci.role, ci.status, ci.desired_revision, ci.effective_revision, ci.authorization_version, ci.last_seen_at, ci.version, ci.created_at, ci.updated_at, tc.serial_number, tc.uri_san, tc.not_after
FROM telemetry_certificates tc
JOIN collector_instances ci ON ci.id = tc.collector_id
WHERE tc.serial_number = $1 AND tc.revoked_at IS NULL AND tc.not_before <= now() AND tc.not_after > now()
  AND ci.status NOT IN ('uninstalled','uninstalling')
`

type GetTelemetryCollectorIdentityBySerialRow struct {
	ID                    uuid.UUID          `json:"id"`
	EnterpriseID          uuid.UUID          `json:"enterprise_id"`
	ResourceType          string             `json:"resource_type"`
	ResourceID            uuid.UUID          `json:"resource_id"`
	DistributionVersionID uuid.UUID          `json:"distribution_version_id"`
	Platform              string             `json:"platform"`
	Role                  string             `json:"role"`
	Status                string             `json:"status"`
	DesiredRevision       int64              `json:"desired_revision"`
	EffectiveRevision     int64              `json:"effective_revision"`
	AuthorizationVersion  int64              `json:"authorization_version"`
	LastSeenAt            pgtype.Timestamptz `json:"last_seen_at"`
	Version               int64              `json:"version"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	SerialNumber          string             `json:"serial_number"`
	UriSan                string             `json:"uri_san"`
	NotAfter              pgtype.Timestamptz `json:"not_after"`
}

func (q *Queries) GetTelemetryCollectorIdentityBySerial(ctx context.Context, serialNumber string) (GetTelemetryCollectorIdentityBySerialRow, error) {
	row := q.db.QueryRow(ctx, getTelemetryCollectorIdentityBySerial, serialNumber)
	var i GetTelemetryCollectorIdentityBySerialRow
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ResourceType,
		&i.ResourceID,
		&i.DistributionVersionID,
		&i.Platform,
		&i.Role,
		&i.Status,
		&i.DesiredRevision,
		&i.EffectiveRevision,
		&i.AuthorizationVersion,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SerialNumber,
		&i.UriSan,
		&i.NotAfter,
	)
	return i, err
}

const getTelemetryCollectorOperation = `-- name: GetTelemetryCollectorOperation :one
SELECT id, enterprise_id, collector_id, pending_action_id, operation, executor_kind, status, plan, plan_hash, lease_owner, fence, lease_expires_at, result_hash, error_code, attempts, expires_at, created_at, updated_at, completed_at FROM telemetry_collector_operations WHERE id = $1 AND enterprise_id = $2
`

type GetTelemetryCollectorOperationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetTelemetryCollectorOperation(ctx context.Context, arg GetTelemetryCollectorOperationParams) (TelemetryCollectorOperation, error) {
	row := q.db.QueryRow(ctx, getTelemetryCollectorOperation, arg.ID, arg.EnterpriseID)
	var i TelemetryCollectorOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CollectorID,
		&i.PendingActionID,
		&i.Operation,
		&i.ExecutorKind,
		&i.Status,
		&i.Plan,
		&i.PlanHash,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ResultHash,
		&i.ErrorCode,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTelemetryEnrollmentTokenForUpdate = `-- name: GetTelemetryEnrollmentTokenForUpdate :one
SELECT id, collector_id, token_hash, expires_at, consumed_at, created_at FROM telemetry_enrollment_tokens WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetTelemetryEnrollmentTokenForUpdate(ctx context.Context, tokenHash []byte) (TelemetryEnrollmentToken, error) {
	row := q.db.QueryRow(ctx, getTelemetryEnrollmentTokenForUpdate, tokenHash)
	var i TelemetryEnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTelemetryRetentionPolicy = `-- name: GetTelemetryRetentionPolicy :one
SELECT enterprise_id, metrics_days, logs_days, traces_days, max_rows, max_scan_bytes, max_execution_ms, version, updated_at FROM telemetry_retention_policies WHERE enterprise_id = $1
`

func (q *Queries) GetTelemetryRetentionPolicy(ctx context.Context, enterpriseID uuid.UUID) (TelemetryRetentionPolicy, error) {
	row := q.db.QueryRow(ctx, getTelemetryRetentionPolicy, enterpriseID)
	var i TelemetryRetentionPolicy
	err := row.Scan(
		&i.EnterpriseID,
		&i.MetricsDays,
		&i.LogsDays,
		&i.TracesDays,
		&i.MaxRows,
		&i.MaxScanBytes,
		&i.MaxExecutionMs,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getTelemetryRoute = `-- name: GetTelemetryRoute :one
SELECT id, enterprise_id, collector_id, kind, gateway_collector_id, status, version, last_tested_at, created_at, updated_at FROM telemetry_routes WHERE id = $1 AND enterprise_id = $2
`

type GetTelemetryRouteParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetTelemetryRoute(ctx context.Context, arg GetTelemetryRouteParams) (TelemetryRoute, error) {
	row := q.db.QueryRow(ctx, getTelemetryRoute, arg.ID, arg.EnterpriseID)
	var i TelemetryRoute
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CollectorID,
		&i.Kind,
		&i.GatewayCollectorID,
		&i.Status,
		&i.Version,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTelemetryRouteByCollector = `-- name: GetTelemetryRouteByCollector :one
SELECT id, enterprise_id, collector_id, kind, gateway_collector_id, status, version, last_tested_at, created_at, updated_at FROM telemetry_routes WHERE collector_id = $1 AND enterprise_id = $2
`

type GetTelemetryRouteByCollectorParams struct {
	CollectorID  uuid.UUID `json:"collector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetTelemetryRouteByCollector(ctx context.Context, arg GetTelemetryRouteByCollectorParams) (TelemetryRoute, error) {
	row := q.db.QueryRow(ctx, getTelemetryRouteByCollector, arg.CollectorID, arg.EnterpriseID)
	var i TelemetryRoute
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CollectorID,
		&i.Kind,
		&i.GatewayCollectorID,
		&i.Status,
		&i.Version,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTelemetryUsage = `-- name: GetTelemetryUsage :one
SELECT
    coalesce(sum(ingested_bytes), 0)::bigint AS ingested_bytes,
    coalesce(sum(metric_points), 0)::bigint AS metric_points,
    coalesce(sum(log_records), 0)::bigint AS log_records,
    coalesce(sum(spans), 0)::bigint AS spans,
    coalesce(sum(estimated_storage_bytes), 0)::bigint AS estimated_storage_bytes
FROM telemetry_usage_daily
WHERE enterprise_id = $1 AND usage_date >= $2 AND usage_date <= $3
`

type GetTelemetryUsageParams struct {
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	UsageDate    pgtype.Date `json:"usage_date"`
	UsageDate_2  pgtype.Date `json:"usage_date_2"`
}

type GetTelemetryUsageRow struct {
	IngestedBytes         int64 `json:"ingested_bytes"`
	MetricPoints          int64 `json:"metric_points"`
	LogRecords            int64 `json:"log_records"`
	Spans                 int64 `json:"spans"`
	EstimatedStorageBytes int64 `json:"estimated_storage_bytes"`
}

func (q *Queries) GetTelemetryUsage(ctx context.Context, arg GetTelemetryUsageParams) (GetTelemetryUsageRow, error) {
	row := q.db.QueryRow(ctx, getTelemetryUsage, arg.EnterpriseID, arg.UsageDate, arg.UsageDate_2)
	var i GetTelemetryUsageRow
	err := row.Scan(
		&i.IngestedBytes,
		&i.MetricPoints,
		&i.LogRecords,
		&i.Spans,
		&i.EstimatedStorageBytes,
	)
	return i, err
}

const getValidTelemetryCertificateBySerial = `-- name: GetValidTelemetryCertificateBySerial :one
SELECT id, collector_id, serial_number, uri_san, csr_hash, certificate_hash, certificate_request_name, issuer_generation, not_before, not_after, revoked_at, revoke_reason, created_at FROM telemetry_certificates
WHERE collector_id = $1 AND serial_number = $2 AND revoked_at IS NULL AND not_after > now()
`

type GetValidTelemetryCertificateBySerialParams struct {
	CollectorID  uuid.UUID `json:"collector_id"`
	SerialNumber string    `json:"serial_number"`
}

func (q *Queries) GetValidTelemetryCertificateBySerial(ctx context.Context, arg GetValidTelemetryCertificateBySerialParams) (TelemetryCertificate, error) {
	row := q.db.QueryRow(ctx, getValidTelemetryCertificateBySerial, arg.CollectorID, arg.SerialNumber)
	var i TelemetryCertificate
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.SerialNumber,
		&i.UriSan,
		&i.CsrHash,
		&i.CertificateHash,
		&i.CertificateRequestName,
		&i.IssuerGeneration,
		&i.NotBefore,
		&i.NotAfter,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
	)
	return i, err
}

const incrementTelemetryUsage = `-- name: IncrementTelemetryUsage :exec
INSERT INTO telemetry_usage_daily (enterprise_id, usage_date, ingested_bytes, metric_points, log_records, spans, estimated_storage_bytes)
VALUES ($1, current_date, $2, $3, $4, $5, $6)
ON CONFLICT (enterprise_id, usage_date) DO UPDATE SET
  ingested_bytes = telemetry_usage_daily.ingested_bytes + EXCLUDED.ingested_bytes,
  metric_points = telemetry_usage_daily.metric_points + EXCLUDED.metric_points,
  log_records = telemetry_usage_daily.log_records + EXCLUDED.log_records,
  spans = telemetry_usage_daily.spans + EXCLUDED.spans,
  estimated_storage_bytes = telemetry_usage_daily.estimated_storage_bytes + EXCLUDED.estimated_storage_bytes,
  updated_at = now()
`

type IncrementTelemetryUsageParams struct {
	EnterpriseID          uuid.UUID `json:"enterprise_id"`
	IngestedBytes         int64     `json:"ingested_bytes"`
	MetricPoints          int64     `json:"metric_points"`
	LogRecords            int64     `json:"log_records"`
	Spans                 int64     `json:"spans"`
	EstimatedStorageBytes int64     `json:"estimated_storage_bytes"`
}

func (q *Queries) IncrementTelemetryUsage(ctx context.Context, arg IncrementTelemetryUsageParams) error {
	_, err := q.db.Exec(ctx, incrementTelemetryUsage,
		arg.EnterpriseID,
		arg.IngestedBytes,
		arg.MetricPoints,
		arg.LogRecords,
		arg.Spans,
		arg.EstimatedStorageBytes,
	)
	return err
}

const limitTelemetryCertificateOverlap = `-- name: LimitTelemetryCertificateOverlap :exec
UPDATE telemetry_certificates
SET not_after = LEAST(not_after, now() + interval '15 minutes')
WHERE collector_id = $1 AND revoked_at IS NULL AND serial_number <> $2
`

type LimitTelemetryCertificateOverlapParams struct {
	CollectorID  uuid.UUID `json:"collector_id"`
	SerialNumber string    `json:"serial_number"`
}

func (q *Queries) LimitTelemetryCertificateOverlap(ctx context.Context, arg LimitTelemetryCertificateOverlapParams) error {
	_, err := q.db.Exec(ctx, limitTelemetryCertificateOverlap, arg.CollectorID, arg.SerialNumber)
	return err
}

const listCollectionClaims = `-- name: ListCollectionClaims :many
SELECT id, enterprise_id, physical_resource_ref, collector_id, profile_id, claim_type, signal, selector, selector_hash, ownership, status, primary_claim_id, rollback_plan, expires_at, created_at FROM collection_claims
WHERE enterprise_id = $1
	AND ($2::text IS NULL
		OR physical_resource_ref = 'host:' || $2
		OR physical_resource_ref = 'kubernetes_cluster:' || $2)
ORDER BY created_at DESC, id
`

type ListCollectionClaimsParams struct {
	EnterpriseID        uuid.UUID   `json:"enterprise_id"`
	PhysicalResourceRef pgtype.Text `json:"physical_resource_ref"`
}

func (q *Queries) ListCollectionClaims(ctx context.Context, arg ListCollectionClaimsParams) ([]CollectionClaim, error) {
	rows, err := q.db.Query(ctx, listCollectionClaims, arg.EnterpriseID, arg.PhysicalResourceRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionClaim{}
	for rows.Next() {
		var i CollectionClaim
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.PhysicalResourceRef,
			&i.CollectorID,
			&i.ProfileID,
			&i.ClaimType,
			&i.Signal,
			&i.Selector,
			&i.SelectorHash,
			&i.Ownership,
			&i.Status,
			&i.PrimaryClaimID,
			&i.RollbackPlan,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectorInstances = `-- name: ListCollectorInstances :many
SELECT id, enterprise_id, resource_type, resource_id, distribution_version_id, platform, role, status, desired_revision, effective_revision, authorization_version, last_seen_at, version, created_at, updated_at FROM collector_instances
WHERE enterprise_id = $1
  AND ($3::text IS NULL OR resource_type = $3)
  AND ($4::uuid IS NULL OR resource_id = $4)
ORDER BY updated_at DESC, id
LIMIT $2
`

type ListCollectorInstancesParams struct {
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	Limit        int32         `json:"limit"`
	ResourceType pgtype.Text   `json:"resource_type"`
	ResourceID   uuid.NullUUID `json:"resource_id"`
}

func (q *Queries) ListCollectorInstances(ctx context.Context, arg ListCollectorInstancesParams) ([]CollectorInstance, error) {
	rows, err := q.db.Query(ctx, listCollectorInstances,
		arg.EnterpriseID,
		arg.Limit,
		arg.ResourceType,
		arg.ResourceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectorInstance{}
	for rows.Next() {
		var i CollectorInstance
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.ResourceType,
			&i.ResourceID,
			&i.DistributionVersionID,
			&i.Platform,
			&i.Role,
			&i.Status,
			&i.DesiredRevision,
			&i.EffectiveRevision,
			&i.AuthorizationVersion,
			&i.LastSeenAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKubernetesNodeHostBindings = `-- name: ListKubernetesNodeHostBindings :many
SELECT id, enterprise_id, kubernetes_cluster_id, node_uid, node_name, host_id, matched_by, evidence, evidence_hash, confidence, status, version, created_at, updated_at FROM kubernetes_node_host_bindings
WHERE enterprise_id = $1 AND kubernetes_cluster_id = $2
ORDER BY node_name, id
`

type ListKubernetesNodeHostBindingsParams struct {
	EnterpriseID        uuid.UUID `json:"enterprise_id"`
	KubernetesClusterID uuid.UUID `json:"kubernetes_cluster_id"`
}

func (q *Queries) ListKubernetesNodeHostBindings(ctx context.Context, arg ListKubernetesNodeHostBindingsParams) ([]KubernetesNodeHostBinding, error) {
	rows, err := q.db.Query(ctx, listKubernetesNodeHostBindings, arg.EnterpriseID, arg.KubernetesClusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KubernetesNodeHostBinding{}
	for rows.Next() {
		var i KubernetesNodeHostBinding
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.KubernetesClusterID,
			&i.NodeUid,
			&i.NodeName,
			&i.HostID,
			&i.MatchedBy,
			&i.Evidence,
			&i.EvidenceHash,
			&i.Confidence,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTelemetryRoutes = `-- name: ListTelemetryRoutes :many
SELECT id, enterprise_id, collector_id, kind, gateway_collector_id, status, version, last_tested_at, created_at, updated_at FROM telemetry_routes WHERE enterprise_id = $1 ORDER BY updated_at DESC, id
`

func (q *Queries) ListTelemetryRoutes(ctx context.Context, enterpriseID uuid.UUID) ([]TelemetryRoute, error) {
	rows, err := q.db.Query(ctx, listTelemetryRoutes, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelemetryRoute{}
	for rows.Next() {
		var i TelemetryRoute
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.CollectorID,
			&i.Kind,
			&i.GatewayCollectorID,
			&i.Status,
			&i.Version,
			&i.LastTestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCollectorConfigApplying = `-- name: MarkCollectorConfigApplying :execrows
UPDATE collector_config_revisions SET status = 'applying'
WHERE collector_id = $1 AND revision = $2 AND status = 'prepared'
`

type MarkCollectorConfigApplyingParams struct {
	CollectorID uuid.UUID `json:"collector_id"`
	Revision    int64     `json:"revision"`
}

func (q *Queries) MarkCollectorConfigApplying(ctx context.Context, arg MarkCollectorConfigApplyingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCollectorConfigApplying, arg.CollectorID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCollectorConfigEffective = `-- name: MarkCollectorConfigEffective :execrows
UPDATE collector_config_revisions SET status = 'effective', applied_at = now()
WHERE collector_id = $1 AND revision = $2 AND status IN ('prepared','applying')
`

type MarkCollectorConfigEffectiveParams struct {
	CollectorID uuid.UUID `json:"collector_id"`
	Revision    int64     `json:"revision"`
}

func (q *Queries) MarkCollectorConfigEffective(ctx context.Context, arg MarkCollectorConfigEffectiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCollectorConfigEffective, arg.CollectorID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCollectorConfigFailed = `-- name: MarkCollectorConfigFailed :execrows
UPDATE collector_config_revisions SET status = 'failed', failure_code = $3
WHERE collector_id = $1 AND revision = $2 AND status IN ('prepared','applying')
`

type MarkCollectorConfigFailedParams struct {
	CollectorID uuid.UUID   `json:"collector_id"`
	Revision    int64       `json:"revision"`
	FailureCode pgtype.Text `json:"failure_code"`
}

func (q *Queries) MarkCollectorConfigFailed(ctx context.Context, arg MarkCollectorConfigFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCollectorConfigFailed, arg.CollectorID, arg.Revision, arg.FailureCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCollectorUninstalling = `-- name: MarkCollectorUninstalling :one
UPDATE collector_instances SET status = 'uninstalling', desired_revision = desired_revision + 1,
  version = version + 1, updated_at = now()
WHERE enterprise_id = $1 AND resource_type = $2 AND resource_id = $3
  AND ($4::bigint = 0 OR version = $4)
RETURNING id, enterprise_id, resource_type, resource_id, distribution_version_id, platform, role, status, desired_revision, effective_revision, authorization_version, last_seen_at, version, created_at, updated_at
`

type MarkCollectorUninstallingParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	Column4      int64     `json:"column_4"`
}

func (q *Queries) MarkCollectorUninstalling(ctx context.Context, arg MarkCollectorUninstallingParams) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, markCollectorUninstalling,
		arg.EnterpriseID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Column4,
	)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ResourceType,
		&i.ResourceID,
		&i.DistributionVersionID,
		&i.Platform,
		&i.Role,
		&i.Status,
		&i.DesiredRevision,
		&i.EffectiveRevision,
		&i.AuthorizationVersion,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTelemetryDLQReplayFailed = `-- name: MarkTelemetryDLQReplayFailed :exec
UPDATE telemetry_dlq_records SET status = 'failed' WHERE id = $1 AND status = 'replaying'
`

func (q *Queries) MarkTelemetryDLQReplayFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTelemetryDLQReplayFailed, id)
	return err
}

const markTelemetryDLQReplayed = `-- name: MarkTelemetryDLQReplayed :exec
UPDATE telemetry_dlq_records SET status = 'replayed', replayed_at = now() WHERE id = $1 AND status = 'replaying'
`

func (q *Queries) MarkTelemetryDLQReplayed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTelemetryDLQReplayed, id)
	return err
}

const markTelemetryRouteActive = `-- name: MarkTelemetryRouteActive :execrows
UPDATE telemetry_routes SET status = 'active', last_tested_at = now(), version = version + 1, updated_at = now()
WHERE collector_id = $1 AND enterprise_id = $2 AND status IN ('pending','testing','degraded')
`

type MarkTelemetryRouteActiveParams struct {
	CollectorID  uuid.UUID `json:"collector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) MarkTelemetryRouteActive(ctx context.Context, arg MarkTelemetryRouteActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTelemetryRouteActive, arg.CollectorID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTelemetryRouteDegraded = `-- name: MarkTelemetryRouteDegraded :execrows
UPDATE telemetry_routes SET status = 'degraded', version = version + 1, updated_at = now()
WHERE collector_id = $1 AND enterprise_id = $2 AND status <> 'invalidated'
`

type MarkTelemetryRouteDegradedParams struct {
	CollectorID  uuid.UUID `json:"collector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) MarkTelemetryRouteDegraded(ctx context.Context, arg MarkTelemetryRouteDegradedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTelemetryRouteDegraded, arg.CollectorID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordTelemetryDLQ = `-- name: RecordTelemetryDLQ :one
INSERT INTO telemetry_dlq_records (id, signal, topic, partition, source_offset, dlq_topic, dlq_partition, dlq_offset, record_hash, error_code)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT (topic, partition, source_offset, record_hash) DO UPDATE SET error_code = EXCLUDED.error_code
RETURNING id, signal, topic, partition, source_offset, dlq_topic, dlq_partition, dlq_offset, record_hash, error_code, status, first_seen_at, replayed_at
`

type RecordTelemetryDLQParams struct {
	ID           uuid.UUID `json:"id"`
	Signal       string    `json:"signal"`
	Topic        string    `json:"topic"`
	Partition    int32     `json:"partition"`
	SourceOffset int64     `json:"source_offset"`
	DlqTopic     string    `json:"dlq_topic"`
	DlqPartition int32     `json:"dlq_partition"`
	DlqOffset    int64     `json:"dlq_offset"`
	RecordHash   []byte    `json:"record_hash"`
	ErrorCode    string    `json:"error_code"`
}

func (q *Queries) RecordTelemetryDLQ(ctx context.Context, arg RecordTelemetryDLQParams) (TelemetryDlqRecord, error) {
	row := q.db.QueryRow(ctx, recordTelemetryDLQ,
		arg.ID,
		arg.Signal,
		arg.Topic,
		arg.Partition,
		arg.SourceOffset,
		arg.DlqTopic,
		arg.DlqPartition,
		arg.DlqOffset,
		arg.RecordHash,
		arg.ErrorCode,
	)
	var i TelemetryDlqRecord
	err := row.Scan(
		&i.ID,
		&i.Signal,
		&i.Topic,
		&i.Partition,
		&i.SourceOffset,
		&i.DlqTopic,
		&i.DlqPartition,
		&i.DlqOffset,
		&i.RecordHash,
		&i.ErrorCode,
		&i.Status,
		&i.FirstSeenAt,
		&i.ReplayedAt,
	)
	return i, err
}

const recoverTelemetryCollectorOperations = `-- name: RecoverTelemetryCollectorOperations :execrows
UPDATE telemetry_collector_operations SET status = 'result_unknown', lease_owner = NULL,
  lease_expires_at = NULL, error_code = 'EXECUTION_RESULT_UNKNOWN', updated_at = now()
WHERE status = 'running' AND lease_expires_at <= now()
`

func (q *Queries) RecoverTelemetryCollectorOperations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverTelemetryCollectorOperations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseCollectorClaims = `-- name: ReleaseCollectorClaims :exec
UPDATE collection_claims SET status = 'released'
WHERE enterprise_id = $1 AND collector_id = $2 AND status IN ('active','conflict')
`

type ReleaseCollectorClaimsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	CollectorID  uuid.UUID `json:"collector_id"`
}

func (q *Queries) ReleaseCollectorClaims(ctx context.Context, arg ReleaseCollectorClaimsParams) error {
	_, err := q.db.Exec(ctx, releaseCollectorClaims, arg.EnterpriseID, arg.CollectorID)
	return err
}

const revokeCollectorCertificates = `-- name: RevokeCollectorCertificates :exec
UPDATE telemetry_certificates SET revoked_at = now(), revoke_reason = $2
WHERE collector_id = $1 AND revoked_at IS NULL
`

type RevokeCollectorCertificatesParams struct {
	CollectorID  uuid.UUID   `json:"collector_id"`
	RevokeReason pgtype.Text `json:"revoke_reason"`
}

func (q *Queries) RevokeCollectorCertificates(ctx context.Context, arg RevokeCollectorCertificatesParams) error {
	_, err := q.db.Exec(ctx, revokeCollectorCertificates, arg.CollectorID, arg.RevokeReason)
	return err
}

const rollbackCollectorClaimMigrations = `-- name: RollbackCollectorClaimMigrations :execrows
UPDATE collection_claims SET status = 'expired'
WHERE enterprise_id = $1 AND collector_id = $2 AND ownership = 'migration' AND status = 'active'
`

type RollbackCollectorClaimMigrationsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	CollectorID  uuid.UUID `json:"collector_id"`
}

func (q *Queries) RollbackCollectorClaimMigrations(ctx context.Context, arg RollbackCollectorClaimMigrationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, rollbackCollectorClaimMigrations, arg.EnterpriseID, arg.CollectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeCollectorConfigRevisions = `-- name: SupersedeCollectorConfigRevisions :exec
UPDATE collector_config_revisions SET status = 'superseded'
WHERE collector_id = $1 AND status IN ('prepared','applying','effective')
`

func (q *Queries) SupersedeCollectorConfigRevisions(ctx context.Context, collectorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, supersedeCollectorConfigRevisions, collectorID)
	return err
}

const upsertCollectorForAction = `-- name: UpsertCollectorForAction :one
INSERT INTO collector_instances (
  id, enterprise_id, resource_type, resource_id, distribution_version_id,
  platform, role, status, desired_revision, effective_revision
) VALUES ($1,$2,$3,$4,$5,$6,$7,'installing',1,0)
ON CONFLICT (enterprise_id, resource_type, resource_id) DO UPDATE SET
  distribution_version_id = EXCLUDED.distribution_version_id,
  platform = EXCLUDED.platform,
  role = EXCLUDED.role,
  status = 'installing',
  desired_revision = collector_instances.desired_revision + 1,
  version = collector_instances.version + 1,
  updated_at = now()
RETURNING id, enterprise_id, resource_type, resource_id, distribution_version_id, platform, role, status, desired_revision, effective_revision, authorization_version, last_seen_at, version, created_at, updated_at
`

type UpsertCollectorForActionParams struct {
	ID                    uuid.UUID `json:"id"`
	EnterpriseID          uuid.UUID `json:"enterprise_id"`
	ResourceType          string    `json:"resource_type"`
	ResourceID            uuid.UUID `json:"resource_id"`
	DistributionVersionID uuid.UUID `json:"distribution_version_id"`
	Platform              string    `json:"platform"`
	Role                  string    `json:"role"`
}

func (q *Queries) UpsertCollectorForAction(ctx context.Context, arg UpsertCollectorForActionParams) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, upsertCollectorForAction,
		arg.ID,
		arg.EnterpriseID,
		arg.ResourceType,
		arg.ResourceID,
		arg.DistributionVersionID,
		arg.Platform,
		arg.Role,
	)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ResourceType,
		&i.ResourceID,
		&i.DistributionVersionID,
		&i.Platform,
		&i.Role,
		&i.Status,
		&i.DesiredRevision,
		&i.EffectiveRevision,
		&i.AuthorizationVersion,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertKubernetesNodeHostBindingProposal = `-- name: UpsertKubernetesNodeHostBindingProposal :one
INSERT INTO kubernetes_node_host_bindings (
  id, enterprise_id, kubernetes_cluster_id, node_uid, node_name, host_id,
  matched_by, evidence, evidence_hash, confidence, status
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'proposed')
ON CONFLICT (enterprise_id, kubernetes_cluster_id, node_uid) DO UPDATE SET
  node_name = EXCLUDED.node_name,
	host_id = CASE
		WHEN kubernetes_node_host_bindings.status = 'verified' AND kubernetes_node_host_bindings.evidence_hash = EXCLUDED.evidence_hash
		THEN kubernetes_node_host_bindings.host_id ELSE EXCLUDED.host_id END,
  evidence = EXCLUDED.evidence,
  evidence_hash = EXCLUDED.evidence_hash,
	matched_by = CASE
		WHEN kubernetes_node_host_bindings.status = 'verified' AND kubernetes_node_host_bindings.evidence_hash = EXCLUDED.evidence_hash
		THEN kubernetes_node_host_bindings.matched_by ELSE EXCLUDED.matched_by END,
	confidence = CASE
		WHEN kubernetes_node_host_bindings.status = 'verified' AND kubernetes_node_host_bindings.evidence_hash = EXCLUDED.evidence_hash
		THEN kubernetes_node_host_bindings.confidence ELSE EXCLUDED.confidence END,
  status = CASE WHEN kubernetes_node_host_bindings.status = 'verified' AND kubernetes_node_host_bindings.evidence_hash = EXCLUDED.evidence_hash THEN 'verified' ELSE 'proposed' END,
  version = kubernetes_node_host_bindings.version + 1,
  updated_at = now()
RETURNING id, enterprise_id, kubernetes_cluster_id, node_uid, node_name, host_id, matched_by, evidence, evidence_hash, confidence, status, version, created_at, updated_at
`

type UpsertKubernetesNodeHostBindingProposalParams struct {
	ID                  uuid.UUID     `json:"id"`
	EnterpriseID        uuid.UUID     `json:"enterprise_id"`
	KubernetesClusterID uuid.UUID     `json:"kubernetes_cluster_id"`
	NodeUid             string        `json:"node_uid"`
	NodeName            string        `json:"node_name"`
	HostID              uuid.NullUUID `json:"host_id"`
	MatchedBy           string        `json:"matched_by"`
	Evidence            []byte        `json:"evidence"`
	EvidenceHash        []byte        `json:"evidence_hash"`
	Confidence          int32         `json:"confidence"`
}

func (q *Queries) UpsertKubernetesNodeHostBindingProposal(ctx context.Context, arg UpsertKubernetesNodeHostBindingProposalParams) (KubernetesNodeHostBinding, error) {
	row := q.db.QueryRow(ctx, upsertKubernetesNodeHostBindingProposal,
		arg.ID,
		arg.EnterpriseID,
		arg.KubernetesClusterID,
		arg.NodeUid,
		arg.NodeName,
		arg.HostID,
		arg.MatchedBy,
		arg.Evidence,
		arg.EvidenceHash,
		arg.Confidence,
	)
	var i KubernetesNodeHostBinding
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.KubernetesClusterID,
		&i.NodeUid,
		&i.NodeName,
		&i.HostID,
		&i.MatchedBy,
		&i.Evidence,
		&i.EvidenceHash,
		&i.Confidence,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTelemetryRoute = `-- name: UpsertTelemetryRoute :one
INSERT INTO telemetry_routes (
  id, enterprise_id, collector_id, kind, gateway_collector_id, status
) VALUES ($1,$2,$3,$4,$5,'pending')
ON CONFLICT (collector_id) DO UPDATE SET
  kind = EXCLUDED.kind,
  gateway_collector_id = EXCLUDED.gateway_collector_id,
  status = 'pending',
  version = telemetry_routes.version + 1,
  updated_at = now()
RETURNING id, enterprise_id, collector_id, kind, gateway_collector_id, status, version, last_tested_at, created_at, updated_at
`

type UpsertTelemetryRouteParams struct {
	ID                 uuid.UUID     `json:"id"`
	EnterpriseID       uuid.UUID     `json:"enterprise_id"`
	CollectorID        uuid.UUID     `json:"collector_id"`
	Kind               string        `json:"kind"`
	GatewayCollectorID uuid.NullUUID `json:"gateway_collector_id"`
}

func (q *Queries) UpsertTelemetryRoute(ctx context.Context, arg UpsertTelemetryRouteParams) (TelemetryRoute, error) {
	row := q.db.QueryRow(ctx, upsertTelemetryRoute,
		arg.ID,
		arg.EnterpriseID,
		arg.CollectorID,
		arg.Kind,
		arg.GatewayCollectorID,
	)
	var i TelemetryRoute
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CollectorID,
		&i.Kind,
		&i.GatewayCollectorID,
		&i.Status,
		&i.Version,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
