// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telemetry_catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listCollectionProfiles = `-- name: ListCollectionProfiles :many
SELECT id, profile_key, version, name, description, signals, required_components, supported_platforms, claim_types, config_schema_version, support_status, catalog_revision, created_at FROM collection_profiles ORDER BY profile_key, version
`

func (q *Queries) ListCollectionProfiles(ctx context.Context) ([]CollectionProfile, error) {
	rows, err := q.db.Query(ctx, listCollectionProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionProfile{}
	for rows.Next() {
		var i CollectionProfile
		if err := rows.Scan(
			&i.ID,
			&i.ProfileKey,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Signals,
			&i.RequiredComponents,
			&i.SupportedPlatforms,
			&i.ClaimTypes,
			&i.ConfigSchemaVersion,
			&i.SupportStatus,
			&i.CatalogRevision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectorDistributionVersions = `-- name: ListCollectorDistributionVersions :many
SELECT id, name, version, collector_version, config_schema_version, support_status, components, artifact_manifest, catalog_revision, created_at FROM collector_distribution_versions ORDER BY catalog_revision DESC, name, version
`

func (q *Queries) ListCollectorDistributionVersions(ctx context.Context) ([]CollectorDistributionVersion, error) {
	rows, err := q.db.Query(ctx, listCollectorDistributionVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectorDistributionVersion{}
	for rows.Next() {
		var i CollectorDistributionVersion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.CollectorVersion,
			&i.ConfigSchemaVersion,
			&i.SupportStatus,
			&i.Components,
			&i.ArtifactManifest,
			&i.CatalogRevision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCollectionProfile = `-- name: UpsertCollectionProfile :one
INSERT INTO collection_profiles (
    id, profile_key, version, name, description, signals, required_components, supported_platforms, claim_types,
    config_schema_version, support_status, catalog_revision
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
ON CONFLICT (profile_key, version) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    signals = EXCLUDED.signals,
    required_components = EXCLUDED.required_components,
    supported_platforms = EXCLUDED.supported_platforms,
    claim_types = EXCLUDED.claim_types,
    config_schema_version = EXCLUDED.config_schema_version,
    support_status = EXCLUDED.support_status,
    catalog_revision = EXCLUDED.catalog_revision
RETURNING id, profile_key, version, name, description, signals, required_components, supported_platforms, claim_types, config_schema_version, support_status, catalog_revision, created_at
`

type UpsertCollectionProfileParams struct {
	ID                  uuid.UUID `json:"id"`
	ProfileKey          string    `json:"profile_key"`
	Version             string    `json:"version"`
	Name                string    `json:"name"`
	Description         string    `json:"description"`
	Signals             []string  `json:"signals"`
	RequiredComponents  []string  `json:"required_components"`
	SupportedPlatforms  []string  `json:"supported_platforms"`
	ClaimTypes          []string  `json:"claim_types"`
	ConfigSchemaVersion string    `json:"config_schema_version"`
	SupportStatus       string    `json:"support_status"`
	CatalogRevision     int32     `json:"catalog_revision"`
}

func (q *Queries) UpsertCollectionProfile(ctx context.Context, arg UpsertCollectionProfileParams) (CollectionProfile, error) {
	row := q.db.QueryRow(ctx, upsertCollectionProfile,
		arg.ID,
		arg.ProfileKey,
		arg.Version,
		arg.Name,
		arg.Description,
		arg.Signals,
		arg.RequiredComponents,
		arg.SupportedPlatforms,
		arg.ClaimTypes,
		arg.ConfigSchemaVersion,
		arg.SupportStatus,
		arg.CatalogRevision,
	)
	var i CollectionProfile
	err := row.Scan(
		&i.ID,
		&i.ProfileKey,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Signals,
		&i.RequiredComponents,
		&i.SupportedPlatforms,
		&i.ClaimTypes,
		&i.ConfigSchemaVersion,
		&i.SupportStatus,
		&i.CatalogRevision,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCollectorDistributionVersion = `-- name: UpsertCollectorDistributionVersion :one
INSERT INTO collector_distribution_versions (
    id, name, version, collector_version, config_schema_version, support_status, components, artifact_manifest, catalog_revision
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT (name, version) DO UPDATE SET
    collector_version = EXCLUDED.collector_version,
    config_schema_version = EXCLUDED.config_schema_version,
    support_status = EXCLUDED.support_status,
    components = EXCLUDED.components,
    artifact_manifest = EXCLUDED.artifact_manifest,
    catalog_revision = EXCLUDED.catalog_revision
RETURNING id, name, version, collector_version, config_schema_version, support_status, components, artifact_manifest, catalog_revision, created_at
`

type UpsertCollectorDistributionVersionParams struct {
	ID                  uuid.UUID `json:"id"`
	Name                string    `json:"name"`
	Version             string    `json:"version"`
	CollectorVersion    string    `json:"collector_version"`
	ConfigSchemaVersion string    `json:"config_schema_version"`
	SupportStatus       string    `json:"support_status"`
	Components          []string  `json:"components"`
	ArtifactManifest    []byte    `json:"artifact_manifest"`
	CatalogRevision     int32     `json:"catalog_revision"`
}

func (q *Queries) UpsertCollectorDistributionVersion(ctx context.Context, arg UpsertCollectorDistributionVersionParams) (CollectorDistributionVersion, error) {
	row := q.db.QueryRow(ctx, upsertCollectorDistributionVersion,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.CollectorVersion,
		arg.ConfigSchemaVersion,
		arg.SupportStatus,
		arg.Components,
		arg.ArtifactManifest,
		arg.CatalogRevision,
	)
	var i CollectorDistributionVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CollectorVersion,
		&i.ConfigSchemaVersion,
		&i.SupportStatus,
		&i.Components,
		&i.ArtifactManifest,
		&i.CatalogRevision,
		&i.CreatedAt,
	)
	return i, err
}
