// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telemetry_tunnels.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimConnectorTelemetryTunnels = `-- name: ClaimConnectorTelemetryTunnels :many
WITH claimed AS (
  SELECT candidate.id FROM telemetry_tunnels AS candidate
  JOIN credentials AS credential ON credential.id = candidate.credential_id
    AND credential.enterprise_id = candidate.enterprise_id
  WHERE candidate.initiator = 'connector'
    AND candidate.connector_id = $3
    AND candidate.enterprise_id = $4
    AND candidate.status <> 'removed'
    AND credential.status = 'active' AND credential.version = candidate.credential_version
    AND (candidate.status IN ('desired','degraded','down')
      OR candidate.owner_connection_epoch < $2)
    AND (candidate.next_claim_at IS NULL OR candidate.next_claim_at <= now()
      OR candidate.owner_connection_epoch < $2)
  ORDER BY candidate.last_claim_at ASC NULLS FIRST, candidate.id
  LIMIT $5 FOR UPDATE SKIP LOCKED
)
UPDATE telemetry_tunnels AS tunnel SET
  status = 'establishing', lease_owner = $1,
  owner_connection_epoch = $2,
  fence = fence + 1, epoch = epoch + 1,
  lease_expires_at = now() + interval '90 seconds', last_claim_at = now(), updated_at = now()
FROM claimed WHERE tunnel.id = claimed.id RETURNING tunnel.id, tunnel.enterprise_id, tunnel.host_id, tunnel.collector_id, tunnel.connector_id, tunnel.credential_id, tunnel.credential_version, tunnel.target_address, tunnel.target_port, tunnel.target_username, tunnel.pinned_host_key, tunnel.initiator, tunnel.transport, tunnel.loopback_port, tunnel.forward_target, tunnel.status, tunnel.epoch, tunnel.lease_owner, tunnel.owner_connection_epoch, tunnel.fence, tunnel.lease_expires_at, tunnel.last_claim_at, tunnel.last_established_at, tunnel.last_heartbeat_at, tunnel.last_drop_reason, tunnel.reconnect_attempt, tunnel.next_claim_at, tunnel.bytes_relayed, tunnel.throttled_events, tunnel.created_at, tunnel.updated_at
`

type ClaimConnectorTelemetryTunnelsParams struct {
	LeaseOwner      string        `json:"lease_owner"`
	ConnectionEpoch int64         `json:"connection_epoch"`
	ConnectorID     uuid.NullUUID `json:"connector_id"`
	EnterpriseID    uuid.UUID     `json:"enterprise_id"`
	Limit           int32         `json:"limit"`
}

func (q *Queries) ClaimConnectorTelemetryTunnels(ctx context.Context, arg ClaimConnectorTelemetryTunnelsParams) ([]TelemetryTunnel, error) {
	rows, err := q.db.Query(ctx, claimConnectorTelemetryTunnels,
		arg.LeaseOwner,
		arg.ConnectionEpoch,
		arg.ConnectorID,
		arg.EnterpriseID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelemetryTunnel{}
	for rows.Next() {
		var i TelemetryTunnel
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.HostID,
			&i.CollectorID,
			&i.ConnectorID,
			&i.CredentialID,
			&i.CredentialVersion,
			&i.TargetAddress,
			&i.TargetPort,
			&i.TargetUsername,
			&i.PinnedHostKey,
			&i.Initiator,
			&i.Transport,
			&i.LoopbackPort,
			&i.ForwardTarget,
			&i.Status,
			&i.Epoch,
			&i.LeaseOwner,
			&i.OwnerConnectionEpoch,
			&i.Fence,
			&i.LeaseExpiresAt,
			&i.LastClaimAt,
			&i.LastEstablishedAt,
			&i.LastHeartbeatAt,
			&i.LastDropReason,
			&i.ReconnectAttempt,
			&i.NextClaimAt,
			&i.BytesRelayed,
			&i.ThrottledEvents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimTelemetryTunnelBatch = `-- name: ClaimTelemetryTunnelBatch :many
WITH claimed AS (
  SELECT id FROM telemetry_tunnels
  WHERE initiator = 'direct_executor' AND status IN ('desired','establishing','degraded','down')
    AND (lease_expires_at IS NULL OR lease_expires_at < now())
    AND (next_claim_at IS NULL OR next_claim_at <= now())
  ORDER BY last_claim_at ASC NULLS FIRST, id
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE telemetry_tunnels AS tunnel SET
  status = 'establishing', lease_owner = $2, fence = fence + 1,
  epoch = epoch + 1, owner_connection_epoch = 0,
  lease_expires_at = now() + interval '90 seconds', last_claim_at = now(), updated_at = now()
FROM claimed WHERE tunnel.id = claimed.id
RETURNING tunnel.id, tunnel.enterprise_id, tunnel.host_id, tunnel.collector_id, tunnel.connector_id, tunnel.credential_id, tunnel.credential_version, tunnel.target_address, tunnel.target_port, tunnel.target_username, tunnel.pinned_host_key, tunnel.initiator, tunnel.transport, tunnel.loopback_port, tunnel.forward_target, tunnel.status, tunnel.epoch, tunnel.lease_owner, tunnel.owner_connection_epoch, tunnel.fence, tunnel.lease_expires_at, tunnel.last_claim_at, tunnel.last_established_at, tunnel.last_heartbeat_at, tunnel.last_drop_reason, tunnel.reconnect_attempt, tunnel.next_claim_at, tunnel.bytes_relayed, tunnel.throttled_events, tunnel.created_at, tunnel.updated_at
`

type ClaimTelemetryTunnelBatchParams struct {
	Limit      int32  `json:"limit"`
	LeaseOwner string `json:"lease_owner"`
}

// Direct Executor 只认领由它发起的隧道；Connector 隧道由活跃控制会话认领。
func (q *Queries) ClaimTelemetryTunnelBatch(ctx context.Context, arg ClaimTelemetryTunnelBatchParams) ([]TelemetryTunnel, error) {
	rows, err := q.db.Query(ctx, claimTelemetryTunnelBatch, arg.Limit, arg.LeaseOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelemetryTunnel{}
	for rows.Next() {
		var i TelemetryTunnel
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.HostID,
			&i.CollectorID,
			&i.ConnectorID,
			&i.CredentialID,
			&i.CredentialVersion,
			&i.TargetAddress,
			&i.TargetPort,
			&i.TargetUsername,
			&i.PinnedHostKey,
			&i.Initiator,
			&i.Transport,
			&i.LoopbackPort,
			&i.ForwardTarget,
			&i.Status,
			&i.Epoch,
			&i.LeaseOwner,
			&i.OwnerConnectionEpoch,
			&i.Fence,
			&i.LeaseExpiresAt,
			&i.LastClaimAt,
			&i.LastEstablishedAt,
			&i.LastHeartbeatAt,
			&i.LastDropReason,
			&i.ReconnectAttempt,
			&i.NextClaimAt,
			&i.BytesRelayed,
			&i.ThrottledEvents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveTunnelsByEnterprise = `-- name: CountActiveTunnelsByEnterprise :one
SELECT count(*)::bigint FROM telemetry_tunnels
WHERE enterprise_id = $1 AND status <> 'removed'
`

func (q *Queries) CountActiveTunnelsByEnterprise(ctx context.Context, enterpriseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTunnelsByEnterprise, enterpriseID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTelemetryTunnel = `-- name: CreateTelemetryTunnel :one

INSERT INTO telemetry_tunnels (
  id, enterprise_id, host_id, collector_id, connector_id, credential_id,
  credential_version, target_address, target_port, target_username,
  pinned_host_key, initiator, transport, loopback_port, forward_target, status
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,'desired')
ON CONFLICT (collector_id) DO UPDATE SET
  connector_id = EXCLUDED.connector_id,
  credential_id = EXCLUDED.credential_id,
  credential_version = EXCLUDED.credential_version,
  target_address = EXCLUDED.target_address,
  target_port = EXCLUDED.target_port,
  target_username = EXCLUDED.target_username,
  pinned_host_key = EXCLUDED.pinned_host_key,
  initiator = EXCLUDED.initiator,
  transport = EXCLUDED.transport,
  loopback_port = EXCLUDED.loopback_port,
  forward_target = EXCLUDED.forward_target,
  status = 'desired',
  epoch = telemetry_tunnels.epoch + 1,
  lease_owner = '',
  owner_connection_epoch = 0,
  lease_expires_at = NULL,
  last_drop_reason = '',
  reconnect_attempt = 0,
  next_claim_at = NULL,
  updated_at = now()
RETURNING id, enterprise_id, host_id, collector_id, connector_id, credential_id, credential_version, target_address, target_port, target_username, pinned_host_key, initiator, transport, loopback_port, forward_target, status, epoch, lease_owner, owner_connection_epoch, fence, lease_expires_at, last_claim_at, last_established_at, last_heartbeat_at, last_drop_reason, reconnect_attempt, next_claim_at, bytes_relayed, throttled_events, created_at, updated_at
`

type CreateTelemetryTunnelParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	HostID            uuid.UUID     `json:"host_id"`
	CollectorID       uuid.UUID     `json:"collector_id"`
	ConnectorID       uuid.NullUUID `json:"connector_id"`
	CredentialID      uuid.UUID     `json:"credential_id"`
	CredentialVersion int64         `json:"credential_version"`
	TargetAddress     string        `json:"target_address"`
	TargetPort        int32         `json:"target_port"`
	TargetUsername    string        `json:"target_username"`
	PinnedHostKey     string        `json:"pinned_host_key"`
	Initiator         string        `json:"initiator"`
	Transport         string        `json:"transport"`
	LoopbackPort      int32         `json:"loopback_port"`
	ForwardTarget     string        `json:"forward_target"`
}

// PlanV4 反向隧道权威状态。认领/租约/fence 模式与 telemetry_collector_operations
// 同构:SKIP LOCKED 批量认领,fence 随认领递增,epoch 在每次重建连接时递增。
func (q *Queries) CreateTelemetryTunnel(ctx context.Context, arg CreateTelemetryTunnelParams) (TelemetryTunnel, error) {
	row := q.db.QueryRow(ctx, createTelemetryTunnel,
		arg.ID,
		arg.EnterpriseID,
		arg.HostID,
		arg.CollectorID,
		arg.ConnectorID,
		arg.CredentialID,
		arg.CredentialVersion,
		arg.TargetAddress,
		arg.TargetPort,
		arg.TargetUsername,
		arg.PinnedHostKey,
		arg.Initiator,
		arg.Transport,
		arg.LoopbackPort,
		arg.ForwardTarget,
	)
	var i TelemetryTunnel
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.CollectorID,
		&i.ConnectorID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.TargetAddress,
		&i.TargetPort,
		&i.TargetUsername,
		&i.PinnedHostKey,
		&i.Initiator,
		&i.Transport,
		&i.LoopbackPort,
		&i.ForwardTarget,
		&i.Status,
		&i.Epoch,
		&i.LeaseOwner,
		&i.OwnerConnectionEpoch,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.LastClaimAt,
		&i.LastEstablishedAt,
		&i.LastHeartbeatAt,
		&i.LastDropReason,
		&i.ReconnectAttempt,
		&i.NextClaimAt,
		&i.BytesRelayed,
		&i.ThrottledEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dropOwnedConnectorTelemetryTunnels = `-- name: DropOwnedConnectorTelemetryTunnels :execrows
UPDATE telemetry_tunnels SET status = 'down', last_drop_reason = $4, epoch = epoch + 1,
  lease_owner = '', owner_connection_epoch = 0, lease_expires_at = NULL,
  reconnect_attempt = LEAST(reconnect_attempt + 1, 30), next_claim_at = now() + interval '1 second', updated_at = now()
WHERE connector_id = $1 AND enterprise_id = $2 AND lease_owner = $3
  AND status IN ('establishing','established')
`

type DropOwnedConnectorTelemetryTunnelsParams struct {
	ConnectorID    uuid.NullUUID `json:"connector_id"`
	EnterpriseID   uuid.UUID     `json:"enterprise_id"`
	LeaseOwner     string        `json:"lease_owner"`
	LastDropReason string        `json:"last_drop_reason"`
}

func (q *Queries) DropOwnedConnectorTelemetryTunnels(ctx context.Context, arg DropOwnedConnectorTelemetryTunnelsParams) (int64, error) {
	result, err := q.db.Exec(ctx, dropOwnedConnectorTelemetryTunnels,
		arg.ConnectorID,
		arg.EnterpriseID,
		arg.LeaseOwner,
		arg.LastDropReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fenceInvalidConnectorTelemetryTunnels = `-- name: FenceInvalidConnectorTelemetryTunnels :execrows
UPDATE telemetry_tunnels AS tunnel SET
  status = 'down', last_drop_reason = 'credential_revoked', epoch = epoch + 1,
  lease_owner = '', owner_connection_epoch = 0, lease_expires_at = NULL,
  next_claim_at = NULL, updated_at = now()
WHERE tunnel.connector_id = $1 AND tunnel.enterprise_id = $2 AND tunnel.status <> 'removed'
  AND NOT EXISTS (
    SELECT 1 FROM credentials AS credential
    WHERE credential.id = tunnel.credential_id AND credential.enterprise_id = tunnel.enterprise_id
      AND credential.status = 'active' AND credential.version = tunnel.credential_version
  )
`

type FenceInvalidConnectorTelemetryTunnelsParams struct {
	ConnectorID  uuid.NullUUID `json:"connector_id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
}

func (q *Queries) FenceInvalidConnectorTelemetryTunnels(ctx context.Context, arg FenceInvalidConnectorTelemetryTunnelsParams) (int64, error) {
	result, err := q.db.Exec(ctx, fenceInvalidConnectorTelemetryTunnels, arg.ConnectorID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTelemetryTunnel = `-- name: GetTelemetryTunnel :one
SELECT id, enterprise_id, host_id, collector_id, connector_id, credential_id, credential_version, target_address, target_port, target_username, pinned_host_key, initiator, transport, loopback_port, forward_target, status, epoch, lease_owner, owner_connection_epoch, fence, lease_expires_at, last_claim_at, last_established_at, last_heartbeat_at, last_drop_reason, reconnect_attempt, next_claim_at, bytes_relayed, throttled_events, created_at, updated_at FROM telemetry_tunnels WHERE id = $1 AND enterprise_id = $2
`

type GetTelemetryTunnelParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetTelemetryTunnel(ctx context.Context, arg GetTelemetryTunnelParams) (TelemetryTunnel, error) {
	row := q.db.QueryRow(ctx, getTelemetryTunnel, arg.ID, arg.EnterpriseID)
	var i TelemetryTunnel
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.CollectorID,
		&i.ConnectorID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.TargetAddress,
		&i.TargetPort,
		&i.TargetUsername,
		&i.PinnedHostKey,
		&i.Initiator,
		&i.Transport,
		&i.LoopbackPort,
		&i.ForwardTarget,
		&i.Status,
		&i.Epoch,
		&i.LeaseOwner,
		&i.OwnerConnectionEpoch,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.LastClaimAt,
		&i.LastEstablishedAt,
		&i.LastHeartbeatAt,
		&i.LastDropReason,
		&i.ReconnectAttempt,
		&i.NextClaimAt,
		&i.BytesRelayed,
		&i.ThrottledEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTelemetryTunnelByCollector = `-- name: GetTelemetryTunnelByCollector :one
SELECT id, enterprise_id, host_id, collector_id, connector_id, credential_id, credential_version, target_address, target_port, target_username, pinned_host_key, initiator, transport, loopback_port, forward_target, status, epoch, lease_owner, owner_connection_epoch, fence, lease_expires_at, last_claim_at, last_established_at, last_heartbeat_at, last_drop_reason, reconnect_attempt, next_claim_at, bytes_relayed, throttled_events, created_at, updated_at FROM telemetry_tunnels WHERE collector_id = $1
`

func (q *Queries) GetTelemetryTunnelByCollector(ctx context.Context, collectorID uuid.UUID) (TelemetryTunnel, error) {
	row := q.db.QueryRow(ctx, getTelemetryTunnelByCollector, collectorID)
	var i TelemetryTunnel
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.CollectorID,
		&i.ConnectorID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.TargetAddress,
		&i.TargetPort,
		&i.TargetUsername,
		&i.PinnedHostKey,
		&i.Initiator,
		&i.Transport,
		&i.LoopbackPort,
		&i.ForwardTarget,
		&i.Status,
		&i.Epoch,
		&i.LeaseOwner,
		&i.OwnerConnectionEpoch,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.LastClaimAt,
		&i.LastEstablishedAt,
		&i.LastHeartbeatAt,
		&i.LastDropReason,
		&i.ReconnectAttempt,
		&i.NextClaimAt,
		&i.BytesRelayed,
		&i.ThrottledEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatConnectorTelemetryTunnel = `-- name: HeartbeatConnectorTelemetryTunnel :execrows
UPDATE telemetry_tunnels SET
  status = $1, last_heartbeat_at = now(), lease_expires_at = now() + interval '90 seconds',
  bytes_relayed = bytes_relayed + $2,
  throttled_events = throttled_events + $3,
  last_drop_reason = $4,
  reconnect_attempt = CASE WHEN $1 = 'established' THEN 0 ELSE reconnect_attempt END,
  next_claim_at = CASE WHEN $1 = 'established' THEN NULL ELSE next_claim_at END,
  last_established_at = CASE WHEN $1 = 'established' THEN COALESCE(last_established_at, now()) ELSE last_established_at END,
  updated_at = now()
WHERE id = $5 AND enterprise_id = $6
  AND connector_id = $7 AND epoch = $8 AND fence = $9
  AND lease_owner = $10 AND owner_connection_epoch > 0
  AND status IN ('establishing','established')
`

type HeartbeatConnectorTelemetryTunnelParams struct {
	Status          string        `json:"status"`
	BytesRelayed    int64         `json:"bytes_relayed"`
	ThrottledEvents int64         `json:"throttled_events"`
	LastDropReason  string        `json:"last_drop_reason"`
	ID              uuid.UUID     `json:"id"`
	EnterpriseID    uuid.UUID     `json:"enterprise_id"`
	ConnectorID     uuid.NullUUID `json:"connector_id"`
	Epoch           int64         `json:"epoch"`
	Fence           int64         `json:"fence"`
	LeaseOwner      string        `json:"lease_owner"`
}

func (q *Queries) HeartbeatConnectorTelemetryTunnel(ctx context.Context, arg HeartbeatConnectorTelemetryTunnelParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatConnectorTelemetryTunnel,
		arg.Status,
		arg.BytesRelayed,
		arg.ThrottledEvents,
		arg.LastDropReason,
		arg.ID,
		arg.EnterpriseID,
		arg.ConnectorID,
		arg.Epoch,
		arg.Fence,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const heartbeatTelemetryTunnel = `-- name: HeartbeatTelemetryTunnel :execrows
UPDATE telemetry_tunnels SET
  last_heartbeat_at = now(),
  lease_expires_at = now() + interval '90 seconds',
  bytes_relayed = bytes_relayed + $1,
  throttled_events = throttled_events + $2,
  updated_at = now()
WHERE id = $3 AND fence = $4 AND lease_owner = $5
  AND status IN ('established','establishing')
`

type HeartbeatTelemetryTunnelParams struct {
	BytesRelayed    int64     `json:"bytes_relayed"`
	ThrottledEvents int64     `json:"throttled_events"`
	ID              uuid.UUID `json:"id"`
	Fence           int64     `json:"fence"`
	LeaseOwner      string    `json:"lease_owner"`
}

func (q *Queries) HeartbeatTelemetryTunnel(ctx context.Context, arg HeartbeatTelemetryTunnelParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatTelemetryTunnel,
		arg.BytesRelayed,
		arg.ThrottledEvents,
		arg.ID,
		arg.Fence,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOwnedConnectorTelemetryTunnels = `-- name: ListOwnedConnectorTelemetryTunnels :many
SELECT tunnel.id, tunnel.enterprise_id, tunnel.host_id, tunnel.collector_id, tunnel.connector_id, tunnel.credential_id, tunnel.credential_version, tunnel.target_address, tunnel.target_port, tunnel.target_username, tunnel.pinned_host_key, tunnel.initiator, tunnel.transport, tunnel.loopback_port, tunnel.forward_target, tunnel.status, tunnel.epoch, tunnel.lease_owner, tunnel.owner_connection_epoch, tunnel.fence, tunnel.lease_expires_at, tunnel.last_claim_at, tunnel.last_established_at, tunnel.last_heartbeat_at, tunnel.last_drop_reason, tunnel.reconnect_attempt, tunnel.next_claim_at, tunnel.bytes_relayed, tunnel.throttled_events, tunnel.created_at, tunnel.updated_at FROM telemetry_tunnels AS tunnel
JOIN credentials AS credential ON credential.id = tunnel.credential_id AND credential.enterprise_id = tunnel.enterprise_id
WHERE tunnel.connector_id = $1 AND tunnel.enterprise_id = $2 AND tunnel.lease_owner = $3
  AND tunnel.owner_connection_epoch = $4 AND tunnel.status IN ('establishing','established')
  AND tunnel.lease_expires_at > now() AND credential.status = 'active'
  AND credential.version = tunnel.credential_version
ORDER BY tunnel.id
`

type ListOwnedConnectorTelemetryTunnelsParams struct {
	ConnectorID          uuid.NullUUID `json:"connector_id"`
	EnterpriseID         uuid.UUID     `json:"enterprise_id"`
	LeaseOwner           string        `json:"lease_owner"`
	OwnerConnectionEpoch int64         `json:"owner_connection_epoch"`
}

func (q *Queries) ListOwnedConnectorTelemetryTunnels(ctx context.Context, arg ListOwnedConnectorTelemetryTunnelsParams) ([]TelemetryTunnel, error) {
	rows, err := q.db.Query(ctx, listOwnedConnectorTelemetryTunnels,
		arg.ConnectorID,
		arg.EnterpriseID,
		arg.LeaseOwner,
		arg.OwnerConnectionEpoch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelemetryTunnel{}
	for rows.Next() {
		var i TelemetryTunnel
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.HostID,
			&i.CollectorID,
			&i.ConnectorID,
			&i.CredentialID,
			&i.CredentialVersion,
			&i.TargetAddress,
			&i.TargetPort,
			&i.TargetUsername,
			&i.PinnedHostKey,
			&i.Initiator,
			&i.Transport,
			&i.LoopbackPort,
			&i.ForwardTarget,
			&i.Status,
			&i.Epoch,
			&i.LeaseOwner,
			&i.OwnerConnectionEpoch,
			&i.Fence,
			&i.LeaseExpiresAt,
			&i.LastClaimAt,
			&i.LastEstablishedAt,
			&i.LastHeartbeatAt,
			&i.LastDropReason,
			&i.ReconnectAttempt,
			&i.NextClaimAt,
			&i.BytesRelayed,
			&i.ThrottledEvents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTelemetryTunnelsByHosts = `-- name: ListTelemetryTunnelsByHosts :many
SELECT id, enterprise_id, host_id, collector_id, connector_id, credential_id, credential_version, target_address, target_port, target_username, pinned_host_key, initiator, transport, loopback_port, forward_target, status, epoch, lease_owner, owner_connection_epoch, fence, lease_expires_at, last_claim_at, last_established_at, last_heartbeat_at, last_drop_reason, reconnect_attempt, next_claim_at, bytes_relayed, throttled_events, created_at, updated_at FROM telemetry_tunnels WHERE host_id = ANY($1::uuid[])
`

func (q *Queries) ListTelemetryTunnelsByHosts(ctx context.Context, dollar_1 []uuid.UUID) ([]TelemetryTunnel, error) {
	rows, err := q.db.Query(ctx, listTelemetryTunnelsByHosts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelemetryTunnel{}
	for rows.Next() {
		var i TelemetryTunnel
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.HostID,
			&i.CollectorID,
			&i.ConnectorID,
			&i.CredentialID,
			&i.CredentialVersion,
			&i.TargetAddress,
			&i.TargetPort,
			&i.TargetUsername,
			&i.PinnedHostKey,
			&i.Initiator,
			&i.Transport,
			&i.LoopbackPort,
			&i.ForwardTarget,
			&i.Status,
			&i.Epoch,
			&i.LeaseOwner,
			&i.OwnerConnectionEpoch,
			&i.Fence,
			&i.LeaseExpiresAt,
			&i.LastClaimAt,
			&i.LastEstablishedAt,
			&i.LastHeartbeatAt,
			&i.LastDropReason,
			&i.ReconnectAttempt,
			&i.NextClaimAt,
			&i.BytesRelayed,
			&i.ThrottledEvents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOverdueTelemetryTunnelQuota = `-- name: MarkOverdueTelemetryTunnelQuota :execrows
WITH candidate AS (
  SELECT id FROM telemetry_tunnels
  WHERE initiator = 'direct_executor' AND status IN ('desired','down')
    AND lease_owner = '' AND created_at < now() - interval '30 seconds'
    AND (next_claim_at IS NULL OR next_claim_at <= now())
  ORDER BY created_at, id LIMIT 1 FOR UPDATE SKIP LOCKED
)
UPDATE telemetry_tunnels AS tunnel SET status = 'down', last_drop_reason = 'tunnel_quota_exceeded',
  reconnect_attempt = LEAST(reconnect_attempt + 1, 30), next_claim_at = now() + interval '30 seconds', updated_at = now()
FROM candidate WHERE tunnel.id = candidate.id
`

func (q *Queries) MarkOverdueTelemetryTunnelQuota(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markOverdueTelemetryTunnelQuota)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTelemetryTunnelDropped = `-- name: MarkTelemetryTunnelDropped :execrows
UPDATE telemetry_tunnels SET
  status = $4, last_drop_reason = $5, epoch = epoch + 1,
  reconnect_attempt = LEAST(reconnect_attempt + 1, 30),
  next_claim_at = now() + make_interval(secs => CASE LEAST(reconnect_attempt + 1, 6)
    WHEN 1 THEN 1 WHEN 2 THEN 2 WHEN 3 THEN 4 WHEN 4 THEN 8 WHEN 5 THEN 16 ELSE 30 END),
  lease_owner = '', owner_connection_epoch = 0, lease_expires_at = NULL, updated_at = now()
WHERE id = $1 AND fence = $2 AND lease_owner = $3
`

type MarkTelemetryTunnelDroppedParams struct {
	ID             uuid.UUID `json:"id"`
	Fence          int64     `json:"fence"`
	LeaseOwner     string    `json:"lease_owner"`
	Status         string    `json:"status"`
	LastDropReason string    `json:"last_drop_reason"`
}

// fence 守卫:只有当前持租约的副本能写断开状态,防止旧副本覆盖新副本。
func (q *Queries) MarkTelemetryTunnelDropped(ctx context.Context, arg MarkTelemetryTunnelDroppedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTelemetryTunnelDropped,
		arg.ID,
		arg.Fence,
		arg.LeaseOwner,
		arg.Status,
		arg.LastDropReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTelemetryTunnelEstablished = `-- name: MarkTelemetryTunnelEstablished :one
UPDATE telemetry_tunnels SET
  status = 'established', last_established_at = now(), last_heartbeat_at = now(),
  lease_expires_at = now() + interval '90 seconds', last_drop_reason = '',
  reconnect_attempt = 0, next_claim_at = NULL, updated_at = now()
WHERE id = $1 AND fence = $2 AND lease_owner = $3
RETURNING id, enterprise_id, host_id, collector_id, connector_id, credential_id, credential_version, target_address, target_port, target_username, pinned_host_key, initiator, transport, loopback_port, forward_target, status, epoch, lease_owner, owner_connection_epoch, fence, lease_expires_at, last_claim_at, last_established_at, last_heartbeat_at, last_drop_reason, reconnect_attempt, next_claim_at, bytes_relayed, throttled_events, created_at, updated_at
`

type MarkTelemetryTunnelEstablishedParams struct {
	ID         uuid.UUID `json:"id"`
	Fence      int64     `json:"fence"`
	LeaseOwner string    `json:"lease_owner"`
}

func (q *Queries) MarkTelemetryTunnelEstablished(ctx context.Context, arg MarkTelemetryTunnelEstablishedParams) (TelemetryTunnel, error) {
	row := q.db.QueryRow(ctx, markTelemetryTunnelEstablished, arg.ID, arg.Fence, arg.LeaseOwner)
	var i TelemetryTunnel
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.CollectorID,
		&i.ConnectorID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.TargetAddress,
		&i.TargetPort,
		&i.TargetUsername,
		&i.PinnedHostKey,
		&i.Initiator,
		&i.Transport,
		&i.LoopbackPort,
		&i.ForwardTarget,
		&i.Status,
		&i.Epoch,
		&i.LeaseOwner,
		&i.OwnerConnectionEpoch,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.LastClaimAt,
		&i.LastEstablishedAt,
		&i.LastHeartbeatAt,
		&i.LastDropReason,
		&i.ReconnectAttempt,
		&i.NextClaimAt,
		&i.BytesRelayed,
		&i.ThrottledEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTelemetryTunnelRemoved = `-- name: MarkTelemetryTunnelRemoved :execrows
UPDATE telemetry_tunnels SET
  status = 'removed', last_drop_reason = $4, epoch = epoch + 1,
  lease_owner = '', owner_connection_epoch = 0, lease_expires_at = NULL, next_claim_at = NULL, updated_at = now()
WHERE collector_id = $1 AND enterprise_id = $2 AND status <> 'removed'
  AND ($3::text = '' OR lease_owner = $3 OR lease_owner = '')
`

type MarkTelemetryTunnelRemovedParams struct {
	CollectorID    uuid.UUID `json:"collector_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	Column3        string    `json:"column_3"`
	LastDropReason string    `json:"last_drop_reason"`
}

func (q *Queries) MarkTelemetryTunnelRemoved(ctx context.Context, arg MarkTelemetryTunnelRemovedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTelemetryTunnelRemoved,
		arg.CollectorID,
		arg.EnterpriseID,
		arg.Column3,
		arg.LastDropReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recoverExpiredTelemetryTunnels = `-- name: RecoverExpiredTelemetryTunnels :execrows
UPDATE telemetry_tunnels SET
  status = 'down', last_drop_reason = 'lease_expired',
  lease_owner = '', owner_connection_epoch = 0, lease_expires_at = NULL, epoch = epoch + 1,
  reconnect_attempt = LEAST(reconnect_attempt + 1, 30), next_claim_at = now() + interval '1 second', updated_at = now()
WHERE status IN ('establishing','established') AND lease_expires_at < now()
`

// 租约过期的 establishing/established 行回退为 down,等待重新认领。
func (q *Queries) RecoverExpiredTelemetryTunnels(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverExpiredTelemetryTunnels)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
