export const AUDIT_ACTION_CODES = [
  "setup.initialize",
  "enterprise.create",
  "enterprise.update",
  "enterprise.suspend",
  "enterprise.activate",
  "enterprise.disable",
  "platform.enterprise.create",
  "platform.enterprise.update",
  "platform.enterprise.suspend",
  "platform.enterprise.activate",
  "platform.enterprise.disable",
  "enterprise_admin.create",
  "enterprise_admin.disable",
  "enterprise_admin.reset_password",
  "platform.enterprise_admin.create",
  "platform.enterprise_admin.reset_auth",
  "platform.enterprise_admin.disable",
  "identity.create",
  "identity.update",
  "org.user.invite",
  "department.create",
  "department.update",
  "role.create",
  "role.update",
  "org.role.create",
  "data_scope.create",
  "data_scope.update",
  "role_binding.create",
  "role_binding.update",
  "service_account.create",
  "service_account.update",
  "api_key.create",
  "api_key.rotate",
  "api_key.revoke",
  "secret.create",
  "secret.update",
  "secret.rotate",
  "secret.disable",
  "credential.create",
  "credential.update",
  "credential.use",
  "managed_account.create",
  "managed_account.update",
  "ai_model.update",
  "automation.pending_action",
  "pending_action.confirm",
  "pending_action.cancel",
  "approval.approve",
  "approval.reject",
  "host.create.commit",
  "host.create.preview",
  "host.update.preview",
  "host.delete.preview",
  "host.connection_test.create",
  "kubernetes.create.preview",
  "kubernetes.update.preview",
  "kubernetes.delete.preview",
  "kubernetes.connection_test.create",
  "connector.enroll",
  "connector.cert.rotate",
  "execution.one_time_result.claim",
  "telemetry.query.execute",
  "telemetry.dlq.replay",
  "interactive_card.create",
  "interactive_card.revise",
  "interactive_card.validate",
  "interactive_card.activate",
  "interactive_card.disable",
  "interactive_card.rollback",
  "interactive_card.deprecate",
  "remote_access.grant.create",
  "remote_access.grant.update",
  "remote_access.grant.disable",
  "remote_access.policy.create",
  "remote_access.policy.update",
  "remote_access.policy.disable",
  "remote_access.request.create",
  "remote_access.request.decide",
  "remote_access.lease.revoke",
  "remote_access.session.create",
  "remote_access.session.terminate",
  "remote_access.ticket.issue",
  "platform.sandbox_session.terminate",
  "platform.sandbox_backend.create",
  "platform.sandbox_backend.update",
  "platform.sandbox_image.manage",
  "platform.sandbox_profile.manage",
  "platform.sandbox_quota.manage",
  "auth.login",
  "auth.logout",
  "auth.password_change",
] as const;

export const AUDIT_RESOURCE_TYPE_CODES = [
  "platform",
  "enterprise",
  "enterprise_user",
  "enterprise_admin",
  "user",
  "department",
  "role",
  "data_scope",
  "role_binding",
  "service_account",
  "api_key",
  "secret",
  "credential",
  "managed_account",
  "host",
  "kubernetes_cluster",
  "connector",
  "connection_test",
  "bastion_scope",
  "ai_model",
  "approval_policy",
  "pending_action",
  "execution",
  "interactive_card",
  "sandbox_backend",
  "sandbox_image",
  "sandbox_profile",
  "sandbox_session",
  "remote_access_session",
  "remote_access_grant",
  "remote_access_policy",
  "remote_access_request",
  "remote_access_lease",
  "telemetry_query",
  "telemetry_dlq_record",
  "authentication",
  "task",
] as const;

export const AUDIT_ACTOR_TYPE_CODES = [
  "platform_user",
  "enterprise_user",
  "service_account",
  "connector",
  "direct_executor",
  "remote_access_gateway",
  "system",
] as const;

export type AuditPresentationKind =
  | "actions"
  | "resourceTypes"
  | "actorTypes";

export function auditCodeKey(code: string): string {
  return code.replaceAll(".", "_").replaceAll("-", "_");
}

export function auditPresentationKey(
  namespace: string,
  kind: AuditPresentationKind,
  code: string,
): string {
  return `${namespace}.${kind}.${auditCodeKey(code)}`;
}

export function humanizeAuditCode(code: string): string {
  return code
    .split(/[._-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
