{{- range $topic := list "otlp-logs" "otlp-metrics" "otlp-traces" }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ $topic }}
  namespace: {{ $.Values.namespace }}
  labels:
    strimzi.io/cluster: argus-kafka
    app.kubernetes.io/part-of: argus
    argus.io/release-id: {{ $.Values.releaseId | quote }}
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
{{- end }}
{{- range $topic := list "otlp-logs-dlq" "otlp-metrics-dlq" "otlp-traces-dlq" }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ $topic }}
  namespace: {{ $.Values.namespace }}
  labels:
    strimzi.io/cluster: argus-kafka
    app.kubernetes.io/part-of: argus
    argus.io/release-id: {{ $.Values.releaseId | quote }}
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
{{- end }}
