apiVersion: install.argus.io/v1alpha1
kind: ArgusInstallConfig
metadata:
  name: argus-local-formal
spec:
  profile: evaluation
  kubeContext: docker-desktop
  releaseId: argus
  namespaces:
    system: argus-system
    sandbox: argus-sandbox
    observability: argus-observability
  storageClass: standard
  images:
    mode: local-registry
    registry: host.docker.internal:5001
    tag: dev
    pullPolicy: Never
  exposure:
    ingressClassName: nginx
    enterpriseHost: argus.dev
    platformHost: platform.argus.dev
    connectorHost: connector.argus.dev
    tls:
      enabled: true
      mode: cert-manager-selfsigned
  security:
    platformMfaRequired: false
  openSandbox:
    runtimeClassName: ""
    allowSharedRuntime: true
  telemetry:
    collectorVersion: 0.1.0-m7
    linuxArm64Uri: https://artifacts.argus.local/argus-otelcol/0.1.0-m7/linux-arm64.tar.gz
    linuxArm64Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    linuxArm64Signature: ZADUlWDG+q0NxibHhlT6TEaLacc3/LFwv/LnuDTtQtaCBjMUQbgT+c1TzVkZdhtwiTyAWxgrdwS6Y7lBGsM+Dw
    linuxArm64ByteSize: 1
    windowsAmd64Uri: https://artifacts.argus.local/argus-otelcol/0.1.0-m7/windows-amd64.zip
    windowsAmd64Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    windowsAmd64Signature: ZADUlWDG+q0NxibHhlT6TEaLacc3/LFwv/LnuDTtQtaCBjMUQbgT+c1TzVkZdhtwiTyAWxgrdwS6Y7lBGsM+Dw
    windowsAmd64ByteSize: 1
    signingKeyId: argus-evaluation-collector-signing-v1
    signingPublicKey: KipqW8DuwdLu1utyo6JbL5u+vtVT/4ZFVKSjOuK8s64
    kubernetesImage: docker.io/kakj-go/argus-otelcol:0.1.0-m7
    artifactTLSMode: insecure
  persistence:
    postgresql: 2Gi
    redis: 1Gi
    minio: 5Gi
    kafka: 4Gi
    clickhouse: 6Gi
    keeper: 1Gi
